### ISSUE TITLE
VNC Client Options

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#100]
Is there any option to set default encoding method of all VNC clients at server level. For example if I want all client to use "Tight+Medium Quality JPEG" encoding method for all users by default, can we set this at server level. 

Also is there any option to enable "Interframe Compression" for all users by default. 

VNC version :- TurboVNC 2.1

**Comment by dcommander** [comment]
Since you're using Java Web Start, all you have to do is add appropriate `<argument>` tags to **/opt/TurboVNC/java/VncViewer.jnlp**.  For instance:

```
  <application-desc main-class="com.turbovnc.vncviewer.VncViewer">
    <argument>$DISPLAY</argument>
    $PARAMS
    <argument>-samp=2x</argument>
    <argument>-quality=80</argument>
    <argument>-compresslevel=6</argument>
  </application-desc>
```

Those arguments will be passed to every viewer instance launched in that manner.

If you want to force-enable interframe compression, you can do so by starting the server with an argument of `-interframe` (which can be accomplished by setting the argument in **/etc/sysconfig/tvncservers**).

**Comment by amitkumars1985** [comment]
Thanks a lot..!! 
I will try this option and share the feedback.

**Comment by amitkumars1985** [comment]
The solution provided seems to work fine by downlaoding jnlp  with Java WebStart method. 
We are also trying to create a desktop client by using VncViewer.jar. We have copied the content of java dir in /opt/TurboVNC/java and calling the jar file using below command :  

`java` -cp ".;.\TurboVNC\VncViewer.jar;..\TurboVNC\turbovnchelper-win64.jar;.\TurboVNC\ljtwin64.jar" com.turbovnc.vncviewer.VncViewer `2>connection.log`

using this method we are unable to set the default encoding method. Is there any way to accomplish this.

**Comment by dcommander** [comment]
Why would you go to that trouble?  We provide Windows installers that already have everything you need, including launch scripts that automatically start the Java viewer with the helper library.  You can start the viewer with a different encoding method by passing the same command-line arguments that you included in the .jnlp file above.

**Comment by amitkumars1985** [comment]
There are 2 reasons to use this method :
1. We have more than 1200 users across the globe and we don't want to run into trouble asking users to install exe client.
2. Not all users have Admin access to their machine so installation of exe is not possible.

This is the reason we decided to use a wrapper over Java Client which can be distributed to users easily and they don't need to do any installation.

**Comment by mauigna06** [comment]
> Since you're using Java Web Start, all you have to do is add appropriate `<argument>` tags to **/opt/TurboVNC/java/VncViewer.jnlp**. For instance:
> 
> ```
>   <application-desc main-class="com.turbovnc.vncviewer.VncViewer">
>     <argument>$DISPLAY</argument>
>     $PARAMS
>     <argument>-samp=2x</argument>
>     <argument>-quality=80</argument>
>     <argument>-compresslevel=6</argument>
>   </application-desc>
> ```
> 
> Those arguments will be passed to every viewer instance launched in that manner.
> 
> If you want to force-enable interframe compression, you can do so by starting the server with an argument of `-interframe` (which can be accomplished by setting the argument in **/etc/sysconfig/tvncservers**).

Hi. Thanks for the great software. 

How to do this for novnc? It has quality levels and compression levels from 0 to 9. What does these numbers mean? are they mapped to the range 1% to 100%? 

My main interest is how to set up “Tight + Low-Quality JPEG” preset on novnc since I'll be using ARL option on the vncserver.

I searched examples on the issues of TurboVNC and noVNC without success.

**Comment by dcommander** [comment]
@mauigna06 In the future, please create a new issue rather than commenting on an existing issue that is not related.  This issue was related to Java Web Start, not noVNC.

To answer your question, the second figure in the [TurboVNC User's Guide, Section 10.1](https://rawcdn.githack.com/TurboVNC/turbovnc/3.0beta1/doc/index.html#hd0010001), entitled "TigerVNC JPEG Quality Levels", shows how the TurboVNC Server will map Quality Levels 0-9 to actual JPEG quality and chrominance subsampling.   [Table 7.2](https://rawcdn.githack.com/TurboVNC/turbovnc/3.0beta1/doc/index.html#hd007002) describes the differences in the various compression levels.  The rough equivalents to the TurboVNC presets are:

| TurboVNC preset | Actual JPEG quality/subsampling enabled by preset | Compression Level | Roughly equivalent quality level | Actual JPEG quality/subsampling enabled by quality level |
| -- | -- | -- | -- | -- |
Tight + Perceptually Lossless JPEG | 4:4:4 Q95 | 1 |  8 | 4:4:4 Q92 |
Tight + Medium-Quality JPEG | 4:2:2 Q80 | 6 (same as CL 1 + interframe comparison) | 5 | 4:2:2 Q77 |
Tight + Low-Quality JPEG | 4:2:0 Q30 | 7 (same as CL 2 + interframe comparison) | 1 | 4:2:0 Q29 |
