### ISSUE TITLE
Encryption Support for TurboVNC Native Client

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#107]
TurboVNC : 2.1.1

IT seems current TurboVNC Native Client doesn't support Encryption. With using below security types, it gives following error :

permitted-security-types = TLSPlain, X509Plain

Error : "No suitable Authentication Scheme Found" 

Do we know, when native client will be available to support Encryption. 

Using TigerVNC native viewer 1.8, we don't get such error.

**Comment by dcommander** [comment]
Please check existing issues before posting a new one.  This is a duplicate of #8.  It will not happen anytime soon without funding or a well-written code contribution.  I have worked something like 300 hours in the past month-- mostly unpaid-- trying to shore up bugs in TurboVNC 2.1.x and get the next release (2.2) kick-started.  Cendio has a whole team of people, and they are making money off of direct sales of their product.  I have just me, and I only make money from support and funded development opportunities.  There are times when I have been willing to implement a feature pro bono in order to move the project forward, but I have to be extremely judicious about that.  I can't give away so much free milk that no one wants to buy the cow.  This particular feature is not the highest priority for three reasons:

(1) The biggest enterprise consumers of the Windows native TurboVNC Viewer are either using it without encryption (with one-time passwords, which are harmless if snooped) over a corporate intranet, or they are wrapping it with SSH.

(2) My understanding is that Java 9 modules will give us the ability to embed just the JRE components we need into a standalone application bundle, so I intend to investigate the possibility of a standalone cross-platform viewer based on the Java code base with Java 9.  Our Java viewer code base is much more modern and easy to maintain than the Windows viewer code base.  This proposed "unified viewer" won't happen in 2.2, but it is a possibility for 2.3 (which might become 3.0, depending on how things progress.)

(3) Our Java viewer has as good as or better performance than the native viewer.  There is basically no advantage to using the native viewer, other than not having to install a JRE.  The native viewer is maintained primarily for the benefit of enterprise customers who might have objections to installing a JRE on their corporate desktops, but now that the Java plugin is no longer a thing, there should be fewer objections in general to installing a JRE.

BTW, can you please tell me which organization you represent?
