### ISSUE TITLE
Alt gr oddities

### ISSUE THREAD

**Issue by FredrIQ** [TurboVNC/turbovnc#109]
When using TurboVNC viewer on Windows 7 connected to a TurboVNC server running Arch (version info: TurboVNC Server (Xvnc) 64-bit v2.0.1 (build 20160314)), using alt gr + anything (for example, alt gr+2 for @) will make the Alt key "stuck". Holding down both Alt + Alt gr and releasing undos the sticking, but it makes it painful to use alt gr stuff. Swedish keyboard layout.

Using a TightVNC client on the same server will not produce this error.

**Comment by dcommander** [comment]
Please try the 2.1.2 release candidate and let me know if the issue still exists:
https://turbovnc.org/News/20170916

**Comment by FredrIQ** [comment]
I attempted to run the 2.1.2 RC. It had the same issue, but unlike the older client, holding down alt + alt gr and releasing did *not* "unstick" Alt, forcing me to exit the client completely if used.

**Comment by dcommander** [comment]
There are two viewers on Windows.  Are you using the native or the Java viewer?

**Comment by FredrIQ** [comment]
I am using the native version.

**Comment by dcommander** [comment]
Unfortunately, I can't reproduce the problem.  I tried every AltGr and dead key combination on the Swedish keyboard layout, and no issues.  I use a test program on the server to verify whether there are any stuck keys after sending various keystrokes from the viewer, and it didn't detect any.  Is there any further information you can provide that might help me reproduce the problem?  Unfortunately, since I can't reproduce it, it missed the cutoff for 2.1.2, but if it's a legitimate issue, I can fix it in 2.2 beta, which should be out within the next 6 weeks.

**Comment by dcommander** [comment]
@FredrIQ Can you provide any additional information to help me reproduce this problem?

**Comment by FredrIQ** [comment]
Not currently no, sorry. I noticed that the problem went away after a reboot of Windows and I know it has been rather inconsistent in reproduction like that since before. I cannot further investigate at the moment (I only use this VNC setup when at a certain place where I am at only occasionally).

**Comment by FredrIQ** [comment]
I will close this for now. If I can find means to realibly reproduce this issue later on, I'll see if I can reopen.
