### ISSUE TITLE
Defocussing a key-grabbing TurboVNC client

### ISSUE THREAD

**Issue by phi-mah** [TurboVNC/turbovnc#110]
I really like the turbovnc key grabbing feature. But when using it in windowed mode, it prevents me from interacting with any other window.

That means, I am unable to focus other applications or pass characters to them without leaving the key-grabbing mode. It's obvious that Alt-Tab can't be used to focus another window (and in fact it shouldn't), but TurboVNC viewer even suppresses focussing other windows by clicking on them. Also Keystrokes are still sent to the remote sever, regardless of the mouse pointers position).

Even a key-grabbingTurboVNC Viewer should let the user interact with other applications.
At the moment, the only way out is to press Ctrl-Alt-Shift-G, your work in the other window, come back and press Ctrl-Alt-Shift-G again. 

Im using TurboVNC 2.1.2 together with Arch Linux and KDE Plasma 5.11

**Comment by dcommander** [comment]
Are you using a Linux client? If so, have you tried disabling pointer grabbing? On Linux, you can control keyboard and pointer grabbing separately. Pointer grabbing is enabled by default whenever the keyboard is grabbed, because it allows passing certain keyboard+pointer sequences (such as Alt+<mouse drag> to move a window) to the server, but you can pass `-nograbpointer` to vncviewer to disable only pointer grabbing without affecting keyboard grabbing.

**Comment by phi-mah** [comment]
Thank's a lot, the `-nograbpointer` helps definetely. Sadly, I also use the Alt+left/right mouse drag combinations to modify windows within the VNC session, but let's so how well I can work around them.

An automatic pointer un- and regrabbing feature when the mouse cursor leaves the VNC window area on the screen could help here (but maybe its also overcomplicating things..)

**Comment by dcommander** [comment]
There's unfortunately no easy way around that.  Attempting to automatically disable pointer grabbing when the mouse left the window would probably create worse usability issues, because a user might accidentally Alt-drag something too close to the TurboVNC Viewer window boundary and then become confused when suddenly Alt-drag stopped working.  A better solution would be to disable pointer grabbing temporarily if the window is de-focused, but as you discovered, the window can't be de-focused if pointer grabbing is enabled.  It's probably a moot point anyhow, because we would have to rely on Java to send us the appropriate events in order to detect that the pointer had left the window, and I don't think those events are sent if the pointer is grabbed.  IIRC, the mouse coordinates are clamped to the window coordinates as long as the window has focus, but I haven't tested that recently.

In reality, most daily users of TurboVNC use keyboard/pointer grabbing only in full-screen mode.  They'll enable `-FSAltEnter` and then Alt-Enter into full-screen mode when they're ready to do work in the server-side applications, then they'll Alt-Enter out of full-screen mode when they need to do work in client-side applications.  That's why the default is to grab the KB/mouse only in full-screen mode.  Using Alt-Tab to switch between client-side applications and Alt-Enter to switch TurboVNC into and out of full-screen mode is a pretty natural workflow once you get used to it.
