### ISSUE TITLE
Add UTF-8 clipboard support

### ISSUE THREAD

**Issue by zentarim** [TurboVNC/turbovnc#113]
I have a problem with copy UTF symbols through TurboVNC clipboard. Copy direction (client to server or server to client ) does not matter. Two files in attachment represent the problem:
1) [before_copy.txt](https://github.com/TurboVNC/turbovnc/files/1481428/before_copy.txt) represent original text with English and Russian text.
2) [after_copy.txt](https://github.com/TurboVNC/turbovnc/files/1481427/after_copy.txt) represent text after copy through TurboVNC clipboard.

TurboVNC ver. 2.1.2
Thanks in advance!

**Comment by dcommander** [comment]
Unfortunately the standard ClientCutText RFB message only supports ISO-8859-1.  More than likely, we will need to implement the [Extended Clipboard Pseudo-Encoding](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extended-clipboard-pseudo-encoding) in order to support UTF-8 clipboard transfers.  I will look into it.

**Comment by zentarim** [comment]
Thanks for the explanation. This is not bug in this case, i suppose.
Anyway, it could be nicely to see that feature in further releases.

**Comment by jernejs** [comment]
TigerVNC recently added support for this, maybe it could be ported from there?

**Comment by dcommander** [comment]
@jernejs Yes, that is the plan.  I have very limited funding to work on TurboVNC, however, so I have to prioritize.  This and other features are marked "funding needed" in hopes that an organization that needs the feature will be willing to pay for it to be implemented sooner rather than later.

**Comment by insomnia417** [comment]
I have the same demand. It seems that I can't support Chinese at present?

**Comment by dcommander** [comment]
This has been implemented in the dev branch and is now available in the 3.1 evolving pre-release builds (https://turbovnc.org/DeveloperInfo/PreReleases).  Our implementation should be compatible with that of UltraVNC, TigerVNC, and LibVNCServer.

Please test thoroughly.

**Comment by sjtuross** [comment]
Thank you for bringing love to the Unicode clipboard. I want to report that 3.1 evolving pre-release works well together with NoVNC 1.3.0 according to some dev work here https://github.com/ich777/docker-novnc-baseimage/issues/1.

I'm wondering if you could release a minor or patch release with this fix included because stable 3.1 may take months.

**Comment by dcommander** [comment]
The dev/3.1 evolving pre-release builds contain the feature. See above for the links. Those builds have the same packages as an official release.

**Comment by sjtuross** [comment]
Thanks. Yes, I saw the link and it worked well as I reported. I was asking if you could consider a patch release like 3.0.2 with just this fix because it might take months for 3.1 stable with some other changes.

**Comment by dcommander** [comment]
@sjtuross No, the feature is too disruptive for a bug-fix release.  It needs to go through a beta cycle.
