### ISSUE TITLE
Display orientation support

### ISSUE THREAD

**Issue by ThomasKjoernes** [TurboVNC/turbovnc#116]
Ability to manually set rotation of display if server/display driver (?) does not report this correctly.

**Comment by dcommander** [comment]
Not sure if I understand.  Please clarify.

**Comment by ThomasKjoernes** [comment]
Well I have actually not tried this With TurboVNC as the server (if this is possible?)
But only with TightVNC as server and TurboVNC as client.

It seems that the orientation of the display is not reported correctly. If I set my display to portrait mode, the VNC session is not rotated properly and/or there is a mismatch between the mouse orientation vs. The actual transmitted desktop image.


Thomas

Fra: DRC
Sendt: søndag 14. januar 2018 kl. 19:23
Til: TurboVNC/turbovnc
Kopi: ThomasKjoernes; Author
Emne: Re: [TurboVNC/turbovnc] Display orientation support (#116)

Not sure if I understand. Please clarify.

**Comment by dcommander** [comment]
Everyone needs to stop using the Un\*x TightVNC Server.  That product is long obsolete, and the TurboVNC Server has subsumed all of the features that used to exist in the Un*x TightVNC Server.

What you're trying might work with the TurboVNC Server, because of our automatic desktop resize feature.  It definitely will not work with the TightVNC Server.  With the TurboVNC Server and Viewer, the remote desktop should at least resize to the correct window dimensions whenever the display is rotated.  It might properly handle the new rotation as well, but I'm not sure, because I'm not sure how that rotation is communicated to existing windows.  If the window size doesn't change as a result of changing the rotation, then you may have to use Ctrl-Alt-Shift-Z to reset the window to its default size and force an automatic desktop resize.

**Comment by ThomasKjoernes** [comment]
Hello again, I was actually referring to the Windows Version of TightVNC Server. I can’t find any Windows Version of TurboVNC Server?

Thomas

Fra: DRC
Sendt: søndag 14. januar 2018 kl. 20:11
Til: TurboVNC/turbovnc
Kopi: ThomasKjoernes; Author
Emne: Re: [TurboVNC/turbovnc] Display orientation support (#116)

Everyone needs to stop using the Un*x TightVNC Server. That product is long obsolete, and the TurboVNC Server has subsumed all of the features that used to exist in the Un*x TightVNC Server.
What you're trying might work with the TurboVNC Server, because of our automatic desktop resize feature. It definitely will not work with the TightVNC Server. With the TurboVNC Server and Viewer, the remote desktop should at least resize to the correct window dimensions whenever the display is rotated. It might properly handle the new rotation as well, but I'm not sure, because I'm not sure how that rotation is communicated to existing windows. If the window size doesn't change as a result of changing the rotation, then you may have to use Ctrl-Alt-Shift-Z to reset the window to its default size and force an automatic desktop resize.

**Comment by dcommander** [comment]
In that case, I have no idea.  I provide limited support for the Windows UltraVNC Server, but the advanced TurboVNC features, like remote desktop resizing, aren't going to work with it.  Since none of my paying customers use Windows servers, TurboVNC is primarily focused on Un\*x/LInux servers, and I have no funding to add features for Windows servers.
