### ISSUE TITLE
Disallow change of display resolution

### ISSUE THREAD

**Issue by bwinkel** [TurboVNC/turbovnc#118]
First of all, thanks a lot for your work. TurboVNC saved our day, when we migrated from Qt4 to Qt5.

Is it somehow possible to make the VNC display resolution fixed? We provide some screens to external users and depending on the VNC clients they use, it sometimes happens that the display resolution is changed from the initial resolution. I figure that this is a feature and not a bug, but it'd be great if one could disallow this behavior with some configuration option when starting the VNC server.

**Comment by dcommander** [comment]
Questions:
1. Are you trying to disable desktop resizing only for specific TurboVNC Server instances or for all instances running on the machine?
2. Do the external users need to be able to control the TurboVNC Server desktop, or do they just need to be able to view it?
3. Which VNC viewers specifically are causing the problem?  As far as I'm aware, only the TigerVNC Viewer and the TurboVNC Viewer support remote desktop resizing.

If the answer to (2) is "no", then you can simply assign view-only credentials to the users, in the form of a view-only VNC password or OTP or ACL.  Otherwise, I'll need to modify the server, and your answer to (1) will determine how I need to modify it.  Remote desktop resizing can be disabled in the viewer as well, but that isn't the default.

**Comment by bwinkel** [comment]
1. For our use case, it would be perfectly OK to disable the feature for all server instances.
2. Yes, the clients need to be able to control the desktop.
3. Good question. We don't have control over which VNC clients are used, not even over which operating systems are used. I know, that one can disable the feature in the clients, but it would be impossible for us to enforce this (we have no control over the user machines that run the VNC clients). 

Thanks!

**Comment by dcommander** [comment]
OK, it sounds like an additional directive in the security configuration file would do the trick.

**Comment by dcommander** [comment]
Implemented in dev branch.
