### ISSUE TITLE
Include binaries in github Releases

### ISSUE THREAD

**Issue by krrk** [TurboVNC/turbovnc#119]
Could you include binaries for each platform in the Release tab of github like you do for VirtualGL? It seem that SourceForge is unreliable and that you have abandoned that platform. When trying to grab any of the release from SourceForge I receive the following error:

> Unable to find any mirror information for the "/2.1.2/TurboVNC-2.1.2-AppleJava.dmg" file. Please select another file.

I am even receiving a similar error for every project on SourceForge.

**Comment by dcommander** [comment]
You are mistaken.  I still use SF for file releases on all of my open source projects.  What you saw under the VirtualGL releases was an experiment that I forgot to delete.  I was testing whether it would be possible to make the files available both on GitHub and SF, but it proved to be too much of a pain.  There are no plans at the moment to release binaries any place other than on SF.

**Comment by krrk** [comment]
Thanks. It appears that SourceForge is migrating their datacenter and has some issues still.

**Comment by dcommander** [comment]
Good to know.  I don't claim to be a fan of SourceForge necessarily.  They made a move in recent months (taking away the ability to manage the subscribers of my various project mailing lists) that forced me to move our mailing lists to Google Groups, so really the only thing left on SourceForge is file releases and legacy tracker/mailing list/forum data.  However, there is a desire to keep the projects "active" on SF so SF doesn't assume control of them, and since I prefer their file release system, it makes sense to continue using it in order to achieve that goal.  If I abandon the SF projects, I would need to make sure that it is a permanent move, and I'm not ready to do that just yet.

**Comment by dcommander** [comment]
One thing I may look at in the coming months is releasing to GitHub first, using their REST API, then pushing to SourceForge from there.  That is what I was trying to do with VirtualGL (the experiment you stumbled upon.)  It's going to take some time to get it right, however.
