### ISSUE TITLE
Can I add some application autostart after vncserver start?

### ISSUE THREAD

**Issue by fcying** [TurboVNC/turbovnc#123]
I add some application in the end of xstartup.turbovnc, but can't autostart.

**Comment by dcommander** [comment]
That’s because xstartup.turbovnc calls the window manager startup script, which doesn’t return control to xstartup.turbovnc until the window manager exits. In order to autostart applications in that environment, you’ll need to use the autostart feature in whichever window manager you are using (for instance, by placing a .desktop file under ~/config/autostart for GNOME.)

If you only want to run one application and not a full window manager, and if the application is a full-screen (non-windowed) application, then you can simply launch the application at the top of xstartup.turbovnc without running a WM. You can also configure xstartup.turbovnc to run a single windowed application in isolation with a stripped-down WM (see https://turbovnc.org/Documentation/ApplicationIsolation.)

**Comment by fcying** [comment]
Because I need run the application inside vnc, When using tigervnc before, it was started window application on the last line of xstartup.I will see how to configure stripped-down WM, Thanks for Reply~

**Comment by dcommander** [comment]
If the TigerVNC script works, then simply copy ~/.vnc/xstartup to ~/.vnc/xstartup.turbovnc and edit the script to your liking.  The TigerVNC script is more simple than ours, but both scripts try to launch the system's window manager before falling back to TWM.  If TWM is acceptable as a window manager, then you can simply edit ~/.vnc/xstartup.turbovnc as follows:

```
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
if [ -f $HOME/.Xresources ]; then xrdb $HOME/.Xresources; fi
xsetroot -solid grey
xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
twm &
{your application goes here}
```

**Comment by fcying** [comment]
With a simple script, it can autostart application. Thanks~
