### ISSUE TITLE
Can not run a PyQt5 application in VNC

### ISSUE THREAD

**Issue by fcying** [TurboVNC/turbovnc#125]
When I run a PyQt5 application in vnc(TurboViewer+TurboVncserver), it have a error.

If run this application in (TurboViewer+TigerVncserver), it run normal

```
$ python3  main.py
[50036:50065:0313/101434.703937:ERROR:gl_implementation.cc(225)] Failed to load libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[50036:50065:0313/101434.943415:ERROR:gl_surface_qt.cpp(667)] Requested OpenGL implementation is not supported. Implementation: 0
[1]    50036 segmentation fault (core dumped)  python3 main.py
```

**Comment by al3x609** [comment]
try turbovnc + virtualGL, for gl *like support apps

**Comment by dcommander** [comment]
Yes, now that I look at the error message, that likely is the problem. TurboVNC 2.1.x and prior don’t have built-in OpenGL support, because TurboVNC is designed to work with VirtualGL. VirtualGL adds OpenGL support to X proxies— such as TurboVNC— that lack it. VGL also allows OpenGL applications to use GPU acceleration, even when running in an X proxy such as TurboVNC (whereas the built-in OpenGL implementation in X proxies is almost always unaccelerated.)

If the OpenGL applications you plan to run are not particularly complex, then you may want to simply try the 2.2 pre-release of TurboVNC: https://turbovnc.org/DeveloperInfo/PreReleases, which now has a built-in (unaccelerated) OpenGL implementation. That will be easier than setting up VirtualGL, but if you plan to run heavy-hitting OpenGL applications, then VGL is worth the effort.

**Comment by dcommander** [comment]
Closing due to lack of response.  Presumed to be related to the cause I outlined above.  Use VGL or the 2.2 pre-release of TurboVNC to work around.
