### ISSUE TITLE
WebSockets support in the TurboVNC Server

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#127]
I need use no vnc with de last version turbovnc without proxy .

**Comment by dcommander** [comment]
It doesn't at the moment.  Leaving this open as a suggested enhancement.  I'll investigate the potential difficulty of WebSockets support as I prepare the 2.2 beta release.  The code already exists in LibVNCServer, so I'm hoping it's an easy port.

**Comment by dcommander** [comment]
I was able to get most of the way there, but unfortunately my implementation locks up when connecting from the noVNC viewer.  Will investigate further whenever I have time.

**Comment by dcommander** [comment]
This is fully implemented, using the WebSockets code from LibVNCServer, but unfortunately it seems to suffer from https://github.com/novnc/noVNC/issues/874.  I will go ahead and push the code tomorrow.  If anyone knows of another WebSockets-enabled VNC viewer that I could test, please comment below.

**Comment by al3x609** [comment]
mayble an old proyect. [libvirt-console-proxy for QEMU websockets](https://www.berrange.com/tags/websockets/)

**Comment by dcommander** [comment]
AFAICT, that project doesn't implement a WebSockets client.  It only implements a server.

**Comment by dcommander** [comment]
Unfortunately, I discovered that the WebSockets implementation interferes with SSH tunneling, and I can't get encrypted operation (wss://) to work.  :(  I will push it to an experimental branch, but unfortunately it isn't ready to put into the main TurboVNC code base yet, until those issues and the noVNC issue are fixed.  I'm not sure how to fix it, since it is borrowed code from LibVNCServer.

**Comment by dcommander** [comment]
dev.websockets branch has been pushed, for those who want to experiment with the experimental code.  The issues with noVNC pointer events and encryption are also reproducible with LibVNCServer.  The main impetus for this in the long term is supporting a WASM-based viewer, so the feature doesn't necessarily have to make it into 3.0.  3.0 already has a good solution for managing noVNC proxy instances using the vncserver script.

**Comment by al3x609** [comment]
> Unfortunately, I discovered that the WebSockets implementation interferes with SSH tunneling, and I can't get encrypted operation (wss://) to work. :( I will push it to an experimental branch, but unfortunately it isn't ready to put into the main TurboVNC code base yet, until those issues and the noVNC issue are fixed. I'm not sure how to fix it, since it is borrowed code from LibVNCServer.

I have a question.

* Does it only fail with wss or ws too?

**Comment by dcommander** [comment]
ws works fine, except for the aforementioned pointer event issue with noVNC, which causes the connection to terminate if you move the mouse around a lot.  It's unclear whether that issue is the fault of the WebSockets server code or the fault of noVNC.

**Comment by dcommander** [comment]
Ultimately, the solution could be workable if I can get the noVNC pointer issue and the wss issue resolved.  I could work around the SSH incompatibility by just making the WebSockets code optional (activated by passing `-websocket` to `Xvnc`, for instance.)

**Comment by dcommander** [comment]
Correction:  I was able to get wss working properly with LibVNCServer.  I had just forgotten to specify the X.509 certificate and private key file (derp.)

**Comment by al3x609** [comment]
thanks, 

I understand that noVNC, only accepts standard vnc security type, Has this a possible issue for noVNC/turbovnc configuration?

**Comment by dcommander** [comment]
I suggest using it with the OTP feature in the TurboVNC Server.  The idea is that noVNC isn't really necessary on desktop machines for which there is a TurboVNC Viewer available.  It is mainly useful for mobile devices or other devices for which a TurboVNC viewer isn't available, so the basic workflow would be:

1. Use the TurboVNC Session Manager to connect to a TurboVNC session and start a noVNC instance for it. (Ideally, I want to add a more friendly way to enable noVNC from the Session Manager, as well as a way to retrieve the noVNC URL.  Maybe even a way to start/stop noVNC instances on the fly would be nice.)
2. Open noVNC in a web browser on your phone/tablet (using the URL retrieved above.)
3. Use the TurboVNC Session Manager to generate a new OTP for the session. Enter that OTP into your phone/tablet in order to connect to the session.

Using noVNC is a stopgap for TurboVNC 3.0.  In the long term, I have funding from a large TurboVNC shop to implement a WebAssembly-based TurboVNC viewer.  We're just waiting on that technology to mature a bit more.

**Comment by dcommander** [comment]
wss is now working.  That was a derp on my part-- I forgot that the TurboVNC implementation of the rfbssl API splits the initialization into two functions instead of one, so I had to modify __websockets.c__ to call both `rfbssl_init()` and `rfbssl_accept()`.  Interestingly, the noVNC disconnect issue doesn't appear to occur with wss-- only with ws.

**Comment by dcommander** [comment]
Figured out the SSH disconnect issue.  I still need to port the feature to GnuTLS (currently it only works when building TurboVNC with OpenSSL) before pushing to dev.  Then I'll figure out how best to integrate with noVNC.

**Comment by dcommander** [comment]
I've pushed my latest code to dev.websockets, but unfortunately it still suffers from the following problems:

1. novnc/noVNC#874, which effectively makes the TurboVNC Server's built-in WebSockets implementation (and LibVNCServer's as well) unusable with noVNC unless encryption (WSS) is used.  However ...
2. WSS doesn't work with GnuTLS, and after hours spent trying to diagnose the problem, I have no idea why it is happening.
3. WSS doesn't work with RHEL 7 (both OpenSSL 1.0.2 and 0.9.8e), and after hours spent trying to diagnose the problem, I have no idea why it is happening.

Unfortunately development on this feature is now stalled pending resolution of those issues.  For the purposes of noVNC, we already have an acceptable solution.  The funding for built-in WS support came from an ongoing effort to develop a WebAssembly version of the TurboVNC Viewer, and since I currently can't make the WebSockets-to-Sockets emulation layer in WASM work properly with the TurboVNC Server, I can't validate that the built-in WS implementation in the TurboVNC Server works properly for that purpose.  And since it clearly doesn't work properly for noVNC yet, I need to put it on the back burner for now and move on to other projects.

**Comment by dcommander** [comment]
Item 2 above is no longer an issue.  Now that the OpenSSL wrapper in the TurboVNC Server supports the same features that the GnuTLS wrapper supported, the GnuTLS wrapper is being removed in TurboVNC 3.0.

**Comment by dcommander** [comment]
This will probably slip TurboVNC 3.0, since a resolution doesn't appear likely anytime soon.

**Comment by dcommander** [comment]
Implemented in dev/3.0 evolving, thanks to a fix from LibVNCServer.  In my testing, both WS and WSS now work with the latest noVNC code.
