### ISSUE TITLE
[question] root  rights and vnc session from another users

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#155]
The root user should have some way to end all the sessions of other users. Is there any way to configure this for this user to do this?
i.e. vncserver -kill *

**Comment by dcommander** [comment]
`vncserver -kill` does little more than kill the Xvnc process for a particular TurboVNC session. The only reason you need __vncserver__ in order to do that is because the script finds the process ID for the specified session by searching for the .pid file under __~/.vnc.__. Killing all TurboVNC sessions is much easier, since there’s no need to discriminate. You could simply run `pkill Xvnc` as root to kill all Xvnc processes, then loop through all of the users’ home directories and remove __.vnc/*.pid__.
