### ISSUE TITLE
Java 8 Update 201 breaks TurboVNC client on MacOS

### ISSUE THREAD

**Issue by silas101** [TurboVNC/turbovnc#159]
After updating to the latest version of Java JRE on the Mac (Java 8 update 201), I can no longer connect to a TurboVNC server v2.2.1. I am using TurboVNC viewer v2.2.1.

I downgraded to Java 8 Update 192 and I am able to successfully connect to the VNC session.

Screenshot of error message:
![image001](https://user-images.githubusercontent.com/4960048/51418271-69947900-1b37-11e9-89bb-af424269e144.png)

**Comment by rems0** [comment]
Just wanted to add a "me too" it that somehow helps to find a solution without having to downgrade Java.
Is excluding some of the SecurityTypes perhaps a solution?
With "-securitytypes none" it works again, but we really don't want to disable authentication.

Thanks,
Richard

**Comment by dcommander** [comment]
Apparently we're running into this:

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8211883

Gee thanks, Oracle, for continuing to make my life a living hell with your unilateral backward-incompatible decisions.  You're really making me regret using Java in my product.  Seemed like such a great idea in 2012.  Is it possible that, just for one day, someone in the security community could treat programmers like adults who are capable of rationally evaluating risk, rather than assuming that we can't make our own informed decisions?  Yes, I know that anon ciphers are vulnerable to man-in-the-middle attacks, but they're still better than no encryption, which is effectively what this decision leaves us with out of the box.  GRRRRRR!!!!!

Since they are now disabling anonymous cipher suites in the __java.security__ file, there is no way to override that programmatically.  You have to edit the __java.security__ file (under __/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/security__ if you're using the JRE or __/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/jre/lib/security__ if you're using the JDK) and remove `anon, ` from `jdk.tls.disabledAlgorithms`.  I can confirm that that works around the problem for me.  Using an X.509 certificate also works around the problem, but that's admittedly a pain.

Looking forward, it seems that I'll need to customize the __java.security__ file in the JRE that is being shipped with TurboVNC 3.0 in order to work around this.

**Comment by dcommander** [comment]
Another thing you can do, since `security.overridePropertiesFile` is `true`, is:

```
echo "jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, NULL" >~/java.security
export JAVA_TOOL_OPTIONS=-Djava.security.properties=$HOME/java.security
```

**Comment by dcommander** [comment]
Should be fixed in the latest pre-release builds
