### ISSUE TITLE
if cairo send request to X proxy using xcb_send_request64, will the request be xcb request or X request?

### ISSUE THREAD

**Issue by liuty10** [TurboVNC/turbovnc#164]
I am interacting with 360 image in firefox, and I have learned that firefox is based on GTK(gtk calls gdk, and gdk calls cairo to do 2D rendering). When I drag the 360 images to change web content, I use ltrace to record the functions that firefox call, and I find there are a lot of xcb_send_request64.
So, my question is: 
if cairo send request to X proxy using xcb_send_request64, will the request be xcb request or X request?

**Comment by dcommander** [comment]
Both xcb and Xlib are APIs that use the X11 protocol behind the scenes, so from the X server's (X proxy's) point of view, there is no difference.  Xlib is just a higher-level API that abstracts a lot of the lower-level protocol stuff, whereas xcb exposes it.

**Comment by liuty10** [comment]
When dealing with 3D rendering, OpenGL functions are intercepted by VirtualGL and are executed on local servers. If a frame is ready, it was copied from pixel buffer and composed onto a window using XShmPutImage. The X proxy receives the XShmPutImage request and sends a compressed image to the VNC client. 
For xcb, will the request be xcb_shm_putImage_request? or still XShmPutImage request?

How about 2D rendering?
1. 2D rendering commands are sent to X proxy directly. 
2. The requests from apps are not limited to XPutImage, it can be all the other requests defined by X protocol, such as draw_line, draw_rectangle, ...

So, one difference between 2D and 3D rendering when using TurboVNC is that:
3D rendering always calls XShmPutImage or XPutImage to send the rendered image to X proxy. While 2D rendering only sends commands(not rendered images) to X proxy. After receiving a command, the X proxy does rendering work and call XPutImage to form a window. Then, compresses the window image and sends to VNC client. Is my understanding correct?

**Comment by dcommander** [comment]
> For xcb, will the request be xcb_shm_putImage_request? or still XShmPutImage request?

I'll repeat-- from the X server's point of view, there is no difference between Xlib and XCB.  They both send the same requests and receive the same replies at the protocol level.  In the X server, the shared memory PutImage request (`xShmPutImageReq`) is handled here:
https://github.com/TurboVNC/turbovnc/blob/master/unix/Xvnc/programs/Xserver/Xext/shm.c#L513-L610
regardless or whether an Xlib or XCB client is sending it.

> How about 2D rendering?
> 
>    1. 2D rendering commands are sent to X proxy directly.
> 
>    2. The requests from apps are not limited to XPutImage, it can be all the other requests defined by X protocol, such as draw_line, draw_rectangle, ...
> 
> 
> So, one difference between 2D and 3D rendering when using TurboVNC is that:
> 3D rendering always calls XShmPutImage or XPutImage to send the rendered image to X proxy. While 2D rendering only sends commands(not rendered images) to X proxy.

Correct so far.

> After receiving a command, the X proxy does rendering work and call XPutImage to form a window. Then, compresses the window image and sends to VNC client. Is my understanding correct?

Not exactly.  `XPutImage()` is an Xlib function that abstracts sending the lower-level X11 PutImage protocol request and receiving the reply, so it only exists in the Xlib client library, not in the X server.  In the case of TurboVNC, we hook into the X.org driver interface.  That allows us to create and maintain our own framebuffer that can be read and written by both the X server and VNC server portions of TurboVNC.  The VNC server hooks into the X11 drawing commands (https://github.com/TurboVNC/turbovnc/blob/master/unix/Xvnc/programs/Xserver/hw/vnc/draw.c) in order to detect which portions of the framebuffer have changed, and it compresses and sends the changed regions directly from the framebuffer.  As you can see from the code in draw.c, there is a wrapper for all of the X11 drawing operations.  When an X11 drawing request is received by the X server, it activates the corresponding function in draw.c.  That function detects which pixels will be affected by the operation, calls the actual X11 drawing function (see https://github.com/TurboVNC/turbovnc/tree/master/unix/Xvnc/programs/Xserver/fb), then adds the modified region to a list of regions that will be sent with the next framebuffer update.
