### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Immortalin** [TurboVNC/turbovnc#167]
I ran an application directly through the websockets branch with no window manager by using `-vgl -xstartup application`. It works pretty well, my question is, is this still using VirtualGL?

**Comment by dcommander** [comment]
No.  `-vgl` sets an environment variable (`TVNC_VGL`) that is only picked up by xstartup.turbovnc.  If you're using your own xstartup script, then you will need to use `vglrun` within that script in order to activate VirtualGL.

Also, it is usually ill-advised to directly invoke an application startup script using `-xstartup`, unless the application is a full-screen application that doesn't require window management.  There are other things that the window manager sets up, such as key maps, that are probably necessary unless the application is doing its own low-level keyboard handling.

**Comment by Immortalin** [comment]
So technically the specifically flag sequence I give do activate VirtualGL?

**Comment by dcommander** [comment]
I already answered that question.

**Comment by Immortalin** [comment]
Sorry just to clarify, the `-xstartup` flag does NOT activate `xstartup.turbovnc` i.e. those two are unrelated other than sharing a same name.

**Comment by Immortalin** [comment]
Okay I am not sure if this is inteneded behaviour but on Ubuntu Budgie (default wm is budgie-wm powered by GNOME's libmutter) 18.04.2 LTS running vncserver on commit https://github.com/TurboVNC/turbovnc/commit/12d0f047f7e50568403e890cd9af174fb1922c04 with no flags causes it to exit silently  giving the following log:

```
TurboVNC Server (Xvnc) 64-bit v2.2.80 (build 20190314)
Copyright (C) 1999-2019 The VirtualGL Project and many others (see README.txt)
Visit http://www.TurboVNC.org for more information on TurboVNC

14/03/2019 21:56:25 Using security configuration file /opt/TurboVNC/etc/turbovncserver-security.conf
14/03/2019 21:56:25 Enabled security type 'tlsvnc'
14/03/2019 21:56:25 Enabled security type 'tlsotp'
14/03/2019 21:56:25 Enabled security type 'tlsplain'
14/03/2019 21:56:25 Enabled security type 'x509vnc'
14/03/2019 21:56:25 Enabled security type 'x509otp'
14/03/2019 21:56:25 Enabled security type 'x509plain'
14/03/2019 21:56:25 Enabled security type 'vnc'
14/03/2019 21:56:25 Enabled security type 'otp'
14/03/2019 21:56:25 Enabled security type 'unixlogin'
14/03/2019 21:56:25 Enabled security type 'plain'
14/03/2019 21:56:25 Desktop name 'TurboVNC: Aspire (computer)' (computer-Aspire)
14/03/2019 21:56:25 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
14/03/2019 21:56:25 Listening for VNC connections on TCP port 5902
14/03/2019 21:56:25   Interface 0.0.0.0
14/03/2019 21:56:25 Framebuffer: BGRX 8/8/8/8
14/03/2019 21:56:25 New desktop size: 1240 x 900
14/03/2019 21:56:25 New screen layout:
14/03/2019 21:56:25   0x00000040 (output 0x00000040): 1240x900+0+0
14/03/2019 21:56:25 Maximum clipboard transfer size: 1048576 bytes
14/03/2019 21:56:25 VNC extension running!
Killing Xvnc process ID 24385
```

If this is not intended behaviour, then assume it a bug report, Otherwise TurboVNC works perfectly fine when invoked with `-xstartup appname` albeit without a window manager.

Here's the xstartup (default, unmodified):
```
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
XDG_SESSION_TYPE=x11;  export XDG_SESSION_TYPE

OS=`uname -s`

# Emulate GDM
USESTARTUP=0
if [ -x /usr/bin/gnome-session ]; then
  # Use Unity 2D on Ubuntu 12 if no WM is specified.  Unity 3D 5.20.x doesn't
  # even pretend to work properly with our X server.
  if [ -f /usr/share/gnome-session/sessions/ubuntu-2d.session -a -z "$TVNC_WM" ]; then
    TVNC_WM=2d
  fi
  case "$TVNC_WM" in
    2d)
      # Ubuntu 12: ubuntu-2d
      # Ubuntu 14: gnome-fallback
      for SESSION in "gnome-fallback" "ubuntu-2d" "2d-gnome"; do
        if [ -f /usr/share/gnome-session/sessions/$SESSION.session ]; then
          DESKTOP_SESSION=$SESSION;  export DESKTOP_SESSION
          XDG_CURRENT_DESKTOP=$SESSION;  export XDG_CURRENT_DESKTOP
        fi
      done
      # RHEL 7, Fedora
      if [ -f /usr/share/gnome-session/sessions/gnome-classic.session ]; then
        DESKTOP_SESSION=gnome-classic;  export DESKTOP_SESSION
        GNOME_SHELL_SESSION_MODE=classic;  export GNOME_SHELL_SESSION_MODE
        XDG_CURRENT_DESKTOP="GNOME-Classic:GNOME";  export XDG_CURRENT_DESKTOP
        USESTARTUP=1
      fi
      # Ubuntu 16+
      if [ -f /usr/share/gnome-session/sessions/gnome-flashback-metacity.session ]; then
        DESKTOP_SESSION=gnome-flashback-metacity;  export DESKTOP_SESSION
        grep -q "unity" /usr/share/gnome-session/sessions/gnome-flashback-metacity.session && {
          XDG_CURRENT_DESKTOP="GNOME-Flashback:Unity";
          export XDG_CURRENT_DESKTOP;
        } || {
          XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME";
          export XDG_CURRENT_DESKTOP;
          GNOME_SHELL_SESSION_MODE=ubuntu;  export GNOME_SHELL_SESSION_MODE;
          USESTARTUP=1;
        }
      fi
      unset TVNC_WM
      ;;
    *)
      # This is necessary to make Unity work on Ubuntu 16, and on Ubuntu 14, it
      # ensures that the proper compiz profile is set up.  Otherwise, if you
      # accidentally launch Unity in a TurboVNC Server session that lacks
      # OpenGL support, compiz will automatically disable its OpenGL plugin,
      # requiring you to reset the compiz plugin state before Unity will work
      # again.
      if [ -f /usr/share/gnome-session/sessions/ubuntu.session -a "$TVNC_WM" = "" ]; then
        DESKTOP_SESSION=ubuntu;  export DESKTOP_SESSION
        grep -qE "DesktopName\s*=\s*Unity" /usr/share/gnome-session/sessions/ubuntu.session && {
          XDG_CURRENT_DESKTOP=Unity;  export XDG_CURRENT_DESKTOP;
        } || {
          XDG_CURRENT_DESKTOP=ubuntu:GNOME;  export XDG_CURRENT_DESKTOP;
          GNOME_SHELL_SESSION_MODE=ubuntu;  export GNOME_SHELL_SESSION_MODE;
          USESTARTUP=1;
        }
      fi
      ;;
  esac
  if [ "$DESKTOP_SESSION" != "" ]; then
    GDMSESSION=$DESKTOP_SESSION;  export GDMSESSION
    SESSIONTYPE=gnome-session;  export SESSIONTYPE
    STARTUP="/usr/bin/gnome-session --session=$DESKTOP_SESSION"
    export STARTUP
  fi
fi

if [ "$TVNC_VGL" = "1" ]; then
  if [ -z "$SSH_AGENT_PID" -a -x /usr/bin/ssh-agent ]; then
    TVNC_SSHAGENT=/usr/bin/ssh-agent
  fi
  if [ -z "$TVNC_VGLRUN" ]; then
    TVNC_VGLRUN="vglrun +wm"
  fi
fi

if [ "$STARTUP" != "" -a "$USESTARTUP" = "1" ]; then
  exec $TVNC_VGLRUN $STARTUP
fi
if [ "$TVNC_WM" = "" ]; then
  # Typical system-wide WM startup script on Linux and Solaris 11
  if [ -f /etc/X11/xinit/xinitrc ]; then
    TVNC_WM=/etc/X11/xinit/xinitrc
  fi
  # Typical system-wide WM startup script on Solaris 10
  if [ $OS = 'SunOS' -a -f /usr/dt/config/Xinitrc.jds ]; then
    TVNC_WM=/usr/dt/config/Xinitrc.jds
  fi
  # Typical per-user WM startup script on Solaris 10
  if [ $OS = 'SunOS' -a -f $HOME/.dt/sessions/lastsession ]; then
    TVNC_WM=`cat $HOME/.dt/sessions/lastsession`
  fi
else
  TVNC_WM=`which "$TVNC_WM" 2>/dev/null`
fi
if [ "$TVNC_WM" != "" ]; then
  if [ -x "$TVNC_WM" ]; then
    exec $TVNC_SSHAGENT $TVNC_VGLRUN "$TVNC_WM"
  else
    exec $TVNC_SSHAGENT $TVNC_VGLRUN sh "$TVNC_WM"
  fi
else
  echo "No window manager startup script found.  Use the TVNC_WM environment"
  echo "variable to specify the path to a window manager startup script or"
  echo "executable.  Falling back to TWM."
  which twm >/dev/null && {
    if [ -f $HOME/.Xresources ]; then xrdb $HOME/.Xresources; fi
    xsetroot -solid grey
    xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
    twm
  } || {
    echo "TWM not found.  I give up."
    exit 1
  }
fi
```

**Comment by dcommander** [comment]
> Sorry just to clarify, the `-xstartup` flag does NOT activate `xstartup.turbovnc` i.e. those two are unrelated other than sharing a same name. Is this correct?

Please read the man page.  `man -M /opt/TurboVNC/man vncserver`.

> Okay I am not sure if this is intended behaviour but on Ubuntu Budgie (default wm is budgie-wm powered by GNOME's libmutter) 18.04.2 LTS running vncserver on commit [12d0f04](https://github.com/TurboVNC/turbovnc/commit/12d0f047f7e50568403e890cd9af174fb1922c04) with no flags causes it to exit silently giving the following log:

If you have additional questions or issues, then file them separately.

**Comment by Immortalin** [comment]
@dcommander thanks! :D Any suggestions for running window manager inside an existing GUI other than Xephr?

**Comment by dcommander** [comment]
Your terminology is confusing.  I don't think "GUI" means what you think it means.

**Comment by Immortalin** [comment]
Apologies, I mean using a turbovnc on a host with an active window manager. I tried starting budgie-wm from with virtual GL script  for the specific app being streamed through VNC while the main budgie-wm (desktop) is active resulted in system freezing among under errors with graphics. I have not tested any other window managers.

**Comment by dcommander** [comment]
I have never used budgie-wm, but the issue you’re describing is common in recent Linux distributions— particularly those that support Wayland. The problem is in the display manager, not the window manager. Recent display managers typically either reset the 3D X server when you log out, or they lock it down when you log in. This will cause applications running with VGL to abort or hang if they are using that X server for rendering. GDM has started using Wayland by default, so unless you log in with an Xorg session, there is no 3D X server at all. VGL can configure Wayland-enabled GDM releases to use Xorg at the login prompt, but that disables the ability to log in with a Wayland session.

The design of VirtualGL in this regard is a relic of the days before headless X servers were a thing. When VGL first came on the scene 15 years ago, and throughout much of my tenure at Sun Microsystems (2005-2009), GPU-equipped servers were uncommon, so the idea of VGL was that you could install it on a 3D workstation with a default workstation O/S configuration (that is, the workstation ran a display manager at boot time and booted to a login prompt.) Back then, logging in locally to the 3D X server didn’t interfere with VGL. Flash forward to 2019, and logging in locally to the 3D X server almost always does interfere with VGL, which is one of many reasons why I’m working on an EGL back end that doesn’t require a 3D X server. Barring that, your only option at the moment if you want to use VGL and log in locally to the machine at the same time is to set up a dedicated GPU with a headless X server solely for use by VGL, and keep the physical display separate.

**Comment by Immortalin** [comment]
@dcommander thanks for the explanation! I really appreciate it, not many library authors take the time to explain their reasoning, really awesome of you to set an example :)
