### ISSUE TITLE
 Viewport opengl interface 

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#175]
Is posible manage a different opengl viewport for every client connect to Xvnc session? how to a future implementation?

The protocol  rfb share a single viewport for all clients. maybe this new approach, Can be possible this  over vnc?

**Comment by dcommander** [comment]
If you mean a separate TurboVNC Viewer window for every X window, then no, that is not possible.  RFB stands for "remote framebuffer", so it has always been a remote desktop protocol, not a remote window management protocol.  TurboVNC provides a handful of features that allow for an immersive remote desktop experience:
* Using a keystroke to easily switch into and out of full-screen mode
* Optionally (and by default) spanning the full-screen viewer window across all client monitors
* Automatically resizing the remote desktop whenever the TurboVNC Viewer window changes size (including when entering or exiting full-screen mode)
* Automatically configuring the server's Xinerama layout so that the screen boundaries of the remote desktop match those of the client
* Optionally grabbing the keyboard so window management keystrokes (Alt-Tab, etc.) are passed to the server
