### ISSUE TITLE
Ctrl-Alt-Shift-F is not working after windows 10 1903 update.

### ISSUE THREAD

**Issue by Jae-Hyuck** [TurboVNC/turbovnc#193]
Ctrl-Alt-Shift-F (to exit from full-screen mode) is not working after Windows 10 1903 update.
https://superuser.com/questions/1445551/what-does-ctrlaltshiftf-key-combination-in-windows-10-pro-version-1903-do

The alternative method (Ctrl-Esc Esc and then right-click on the vncviewer taskbar icon) is also not working to me. (Maybe I don't know exactly how to use it.)

Please check the issue. Thank you.

**Comment by dcommander** [comment]
Known issue:
https://www.mail-archive.com/turbovnc-users@googlegroups.com/msg00162.html
and unfortunately not one that can be fixed or even worked around by us, at least not without understanding why the issue is occurring.  There is no documentation from Microsoft to indicate why Ctrl-Alt-Shift-F is now reserved.  It just stopped working for no apparent reason, so it may very well be a bug.  The workaround is to enable Alt-Enter as an alternate keystroke to enter/leave full-screen mode.  I will expose that in the GUI in TurboVNC 3.0 (#182).

**Comment by Jae-Hyuck** [comment]
Thank for your support!

Here is a temporal solution on TurboVNC 2.2.2, for other people.
1. Edit any ".vnc" file as fsaltenter=1
2. Connect by running the ".vnc" file. Then Alt-Enter is now working.
3. After the moment, even if you just run the vnc viewer without ".vnc" file, Alt-Enter is working. Maybe the viewer memorizes the previous config.

**Comment by dcommander** [comment]
Yes, if `-fsaltenter` or `-nofsaltenter` is specified for any connection, that setting will be remembered for the connection.  The same will be true for the Java viewer once #135 is implemented.

**Comment by dcommander** [comment]
You don't necessarily need to create a .vnc file.  You can just edit the Start Menu icon for the TurboVNC Viewer and add `-fsaltenter` as a command-line argument for vncviewer.exe.

**Comment by dcommander** [comment]
The use of Alt-Enter as an alternate full-screen toggle hotkey can now be configured in the TurboVNC Viewer Options dialog, which at least makes this issue more straightforward to work around.

**Comment by jsh-de** [comment]
For the archives: I tripped on this bug with a software of mine today, I was still running Windows 10 1909 (not sure why Windows auto-update hadn't happened yet). I updated my Windows to 20H2 using the Update Assistant, and joyfully note: the bug seems to have been fixed by Microsoft: KeyDown-events for CTRL-ALT-SHIFT-F do occur again.

**Comment by dcommander** [comment]
Confirmed fixed in 20H2
