### ISSUE TITLE
Issues Compiling the Windows VNC viewer

### ISSUE THREAD

**Issue by naatje80** [TurboVNC/turbovnc#205]
I tried to compile vncviewer for Windows manually to check if issue  #203 is solved.
No matter which version of Visual Studio I use, If I compile 32-bit or 64-bit, if I use a manually compiled turbojpeg library or the pre-compiled version, I always get the linking error:
```
zlib.lib(crc32.c.obj) : error LNK2019: unresolved external symbol crc_fold_init referenced in function crc_reset
zlib.lib(crc32.c.obj) : error LNK2019: unresolved external symbol crc_fold_copy referenced in function copy_with_crc
zlib.lib(crc32.c.obj) : error LNK2019: unresolved external symbol crc_fold_512to32 referenced in function crc_finalize
```

To compile, I've used the commands: 
```
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -Wno-dev -DTVNC_BUILDJAVA=0 ../
nmake
```
When I downloaded a pre-compiled version of turbovnc, it was also required to add: `-DTJPEG_LIBRARY="c:/libjpeg-turbo64/lib/turbojpeg.lib" -DTJPEG_INCLUDE="c:/libjpeg-turbo64"`
But at the end, still the same linking error.
(```-DTJPEG_LIBRARY="-libpath:c:/libjpeg-turbo64/lib turbojpeg.lib"``` was mentioned in the building instructions, but cmake could not correctly find the library in this way)

It seems to be related to zlib. Googling on the internet revealed that there are issues with zlib on Windows, and sometimes it is required to build it differently. But I assume this should already work, because the zlib build is part of the turbovnc build. I also noticed there is a patch file located in the common/zlib directory. Do I first need to execute this patch?

The version of Visual Studio I've tried were: 2015 and 2017.
I'm using cmake version 3.16.2

Thank you again for your help!

**Comment by dcommander** [comment]
You don't have to compile it to test the fix to #203.  Just install the pre-release build:
https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by dcommander** [comment]
There were two issues at work here:

1. A file was missing under **common/zlib**.  That file is only used with newer versions of Visual Studio, which is why the CI builds (which use Visual Studio 2010) worked but custom builds with Visual Studio 2015 didn't.  That issue has been fixed and pushed.
2. When using Visual Studio 2015, you can't currently link with **turbojpeg-static.lib**, because libjpeg-turbo is still built with Visual Studio 2010, and Visual Studio 2015 is backward-incompatible with Visual Studio 2010 if you're using static linking.  I intend to change that in the next major release of libjpeg-turbo.  In the meantime, it is necessary to use the TurboJPEG DLL instead.  Pass `-DTJPEG_LIBRARY="c:/libjpeg-turbo64/lib/turbojpeg.lib"` to CMake.

**Comment by dcommander** [comment]
The evolving 2.1 pre-release build of libjpeg-turbo (https://libjpeg-turbo.org/DeveloperInfo/PreReleases) now supports Visual Studio 2015 and later, if you don't mind using code that may or may not be production-ready.  I expect libjpeg-turbo 2.1 beta to be released later this month or early next.

**Comment by naatje80** [comment]
@dcommander The issue is resolved. I was now able to successfully compile turbovnc with Visual Studio 2015. I indeed now also use the latest sources for libjpeg-turbo.
