### ISSUE TITLE
vncviewer fails to connect to vncserver

### ISSUE THREAD

**Issue by zenny** [TurboVNC/turbovnc#21]
Hi,

This is in pursuant to @dcommander suggestion at https://github.com/VirtualGL/virtualgl/issues/11#issuecomment-161181948

Platform: TurboVNC  v2.0.1-20151105 in Ubuntu 14.04 Trusty.

I started a vncserver (official .deb from sf.net installed to /opt/TurboVNC/ folder by default) in reference to https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-14-04

```
$ sudo service vncserver start
 * Starting vncserver for user 'zenny' on localhost:2...                                                            
Desktop 'TurboVNC: MACHINE-GA-970A-D3:2 (zenny)' started on display MACHINE-GA-970A-D3:2

Starting applications specified in /home/zenny/.vnc/xstartup.turbovnc
Log file is /home/zenny/.vnc/MACHINE-GA-970A-D3:2.log
```

But when I try to connect with ssh it says,

```
channel_setup_fwd_listener: cannot listen to port: 5902
Could not request local forwarding.
```

I checked /etc/ssh/sshd_config`to check whether X11 forwarding was disabled, but was not the case.
```
$ grep Forwarding /etc/ssh/sshd_config
X11Forwarding yes
```
Obviously, vncviewer died with:

```
$ /opt/TurboVNC/bin/vncviewer 
libjawt.so path: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64
Could not connect: Connection refused
```
'netstat -plant | grep Xvnc' gives Xvnc instant running in port 5902

```
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN      9911/Xvnc       
tcp        0      0 0.0.0.0:6002            0.0.0.0:*               LISTEN      9911/Xvnc              
tcp        0      0 0.0.0.0:5802            0.0.0.0:*               LISTEN      9911/Xvnc       
tcp6       0      0 :::6002                 :::*                    LISTEN      9911/Xvnc  
```

Appreciate any hints on the right way to use TurboVNC! Thanks!

**Comment by dcommander** [comment]
* Those instructions are not ours.  They mention TightVNC, not TurboVNC.  For whatever reason, Ubuntu is still shipping TightVNC 1.3.x, even though that project is no longer maintained.  Please use the TurboVNC User's Guide for the version you are trying to install: http://www.turbovnc.org/Documentation/Documentation.
* The "X11Forwarding" setting in sshd_config has nothing to do with this.  That setting specifies whether you can forward X11 traffic over SSH (VNC is a virtual X server, but it doesn't use the X11 protocol for the remote connection.)  Instead, you need to verify that "AllowTCPForwarding" is set to yes.
* Unless you have opened up the appropriate ports in your firewall, you will have to tunnel the RFB connection over SSH, as you seem to be trying to do.  However, you are leaving out one important step, which is specifying tunneling on the client end: `/opt/TurboVNC/vncviewer -tunnel MACHINE-GA-970A-D3:2` (you can also start vncviewer without arguments and enable tunneling in the Options dialog, under "Security".)

**Comment by zenny** [comment]
@dcommander Thanks a zillion for very useful inputs here to prove that how simple TurboVNC is as well as at https://github.com/VirtualGL/virtualgl/issues/11#issuecomment-161392904. The documentation you pointed to, and --help pages were extremely enlightening.

In the meantime, I am trying NOT to scale down the server's geometry while downsizing only the client's (vncviewer's) to half (1/2), but that does not seem possible with what I understood and executed as of below:

```
$ /opt/TurboVNC/bin/vncserver -geometry 3840x2160 -depth 32 -xstartup 'vglrun -c proxy libreoffice'
```
```
$ /opt/TurboVNC/bin/vncviewer MACHINE-GA-970A-D3:2 -DesktopSize=Server
```
Once I get connected, virtual x server's resolution is reportedly 1916x1022 instead of the geometry I assigned (3840x2160) above.

Did I miss some parameters? Thanks again.

**Comment by dcommander** [comment]
Several comments:
* `-depth 32` is unnecessary with TurboVNC (that's already the default.)
* `-c proxy` is unnecessary with `vglrun` in a TurboVNC environment (VirtualGL will automatically detect that it's running in an X proxy environment.)
* Generally it isn't recommended to run a windowed application like OpenOffice in TurboVNC without a window manager.  The approach you took above, passing a single application using the `-xstartup` parameter, would work with a single-window, full-screen application, but the results with windowed applications will be unpredictable at best.  VNC is a fundamentally different type of solution than xpra.  xpra is essentially just like using remote X, except that it compresses the X protocol-- thus it can run multi-window applications, because the window management is taking place on the client.  With VNC, however, the window management and all X rendering is taking place on the server, so it really needs a WM.  The VNC session is essentially behaving as a remote virtual desktop.
* Regarding the unwanted resizing of the remote desktop, I have observed with some WM's that the WM will remember the last desktop size that was used with it (for instance, from a local session) and will attempt to resize the desktop to that size the next time the WM starts.  But since you aren't using a WM, I have no explanation.
* It isn't necessary to use `vglrun` (VirtualGL) unless the application uses OpenGL.
