### ISSUE TITLE
Cant supply username AND password to turbovncviewer.exe

### ISSUE THREAD

**Issue by kokoko3k** [TurboVNC/turbovnc#210]
Well, i don't think i need to say more, if i start
turbovncviewer.exe /user myuser /password mypass myserver
...the dialog still pops up and the password field is just empy.

even tried: echo mypass | turbovncviewer.exe /user myuser /autopass myserver
...but i've got a "error during authentication" and "empty password" message (!?)

**Comment by dcommander** [comment]
The `echo` command on Windows is somewhat non-intuitive.  Unfortunately, it counts trailing spaces and quotes as part of the string, so if you do

```
echo mypass{space}| vncviewer.exe myserver /autopass [/user myuser]
```

the TurboVNC Viewer will read that space as part of the password.  The solution is to avoid adding a space between the `echo` command and the pipe.  With that in mind, `/autopass` does work with `/user`.

However, you are correct that `/password` does not work with `/user` in the Windows TurboVNC Viewer.  That is a limitation of the `/password` feature in that viewer.  Bearing in mind that that feature was developed in 2006, it was originally intended only to work with VNC passwords, not Unix passwords.  Thus, the Windows TurboVNC Viewer immediately converts the plain-text password into an 8-character DES-encrypted password (suitable for use with the Standard VNC authentication scheme) as soon as it reads the plain-text password from the command line.  That behavior was intended to avoid storing the plain-text password in memory between the time that the viewer reads the password from the command line and transmits the password to the server.  I realize that, in this day and age, DES3 isn't much more secure than plain text, but it would not be straightforward to change that behavior.  I have no interest in doing so, since
- the native Windows TurboVNC Viewer is being replaced with the Java TurboVNC Viewer + an embedded JRE in the next major release of TurboVNC, and the Java viewer already supports using `-password` with `-user`, and
- a workaround is available (`/autopass`, per above.)

Unix Login Authentication is never a good idea unless you are using some form of encryption. (The Windows TurboVNC Viewer only supports SSH tunneling.  Built-in TLS encryption requires the Windows/Java TurboVNC Viewer.)  Without SSH or TLS encryption, Unix Login Authentication sends the Unix password over the network in plain-text form.  Again, DES3 isn't much more secure than plain text in this day and age, but if a VNC password is compromised, it's much easier for the user to change it, and the potential attack surface is more limited (a running VNC session, not an entire user account.)  Still, I don't recommend using VNC authentication over an unencrypted connection, either.  That's one reason why the native Windows TurboVNC Viewer is being retired.  It was easier to figure out how to make the Java viewer behave like the native viewer than to figure out how to add encryption to the native viewer, and the performance of those two viewers is similar.

Also, the `-password` and `-autopass` features are never a good idea unless you are using some form of disposable token rather than your actual password.  That's really what those features were intended for-- automated portals or session managers that generate one-time passwords for each TurboVNC Server instance and then pass those OTPs automatically to an instance of the TurboVNC Viewer.  Otherwise, I can't think of a justifiable reason to use `/password` with Unix Login Authentication.  If you're willing to type the password each time, then just type it into the authentication dialog.  If you're not willing to type the password each time, then using `/password` would require storing your Unix password in a script in plain-text form, which is not secure.  That's one reason why `/password` in the Windows TurboVNC Viewer was never extended to include Unix Login Authentication.  Now, if you are using a PAM-based OTP mechanism on the server (which, bear in mind, didn't exist in 2006), that would be a justifiable reason to use `/password` with `/user`, but again, that already works in the Java TurboVNC Viewer and will thus work with TurboVNC 3.0.

**Comment by kokoko3k** [comment]
Hi dcommander,
thank you for the detailed explaination, and thank you for turbovnc.
I can confirm that removing the space after the pipe workaround the "issue".

As per the security concerns, i manage a lab with a lot of Windows clients connecting to a linux server.
In the past i used FreeNX to open a remote desktop, but it has been harder and harder to integrate as itis unmantained.
So i switched to x2go, but i'm having problems with it stallig for no apparent reasons.
Given how desktop environment and Linux toolkits in general are progressing, i don't think there is a real gain in using Xorg protocol over the net, so it was time to use something image based, and turbovnc seems to fit perfectly, and indeed it does.

Keep in mind that my intention was to replicate session resume functionality given by Nx/X2go.

* Our users type their username/password a first time to log into the windows machine.
* Next they type the same username/passwords in putty to start a remote script that (if not already running) spawns via ssh their vnc servers (since we dont have so many users -2500 by now- I managed to find a way to associate an unique port number per user).
* Then they need to supply the password a third time to finally connect to the vnc server (Unix login).

So, typing 3 times the same data seems a bit too much; i've managed to auto-fill usernames, but still...
Why don't you use key based ssh auth? You may ask.
I tried, but unfortunately, since their remote desktop needs to mount remote cifs shares with right acls (i do that via pam_mount), it needs to have a password floating through the pam stack 'till pam_mout block (i tried to steal and convert the kerneros ticket from the windows login, and give it to krb5 on the linux side, for mount-cifs -sec krb5 to work, but failed miserably).

So, in the end, you're right about the password in plain-text, but i'm not really storing them anywhere.
What i managed to do was to create a simple app asking for username/password; that app runs into a script and forward the plaintext credentials to putty first (to spawn the vnc server) and then to the vncviewer to connect to it.
So yes, it is not secure, but all the insecureness is happening for less than a second on a local machine used by just one person.

Thank you again for the time you spent for answering me and keep up the good work!

**Comment by dcommander** [comment]
If you have time to play with it, I would welcome your feedback regarding the TurboVNC Session Manager, which is currently available for testing in the [3.0 evolving pre-release builds](https://turbovnc.org/DeveloperInfo/PreReleases.) (It involves both the viewer and the server, so you will have to install the pre-release on both ends in order to test it.)  It might allow you to eliminate one or two of those steps.  The Session Manager connects to the TurboVNC host via SSH, using the embedded SSH client in the Java TurboVNC Viewer (which, in 3.0, is deployed along with an embedded JRE, so it isn't necessary to install Java in order to use it.)  The Session Manager then uses that SSH connection to start or resume TurboVNC Server sessions automatically.  The listening port and one-time password are transmitted back to the viewer through SSH, so the viewer can then seamlessly connect and authenticate with the TurboVNC Server session without requiring re-authentication.  The TurboVNC Session Manager won't currently solve your problem of transmitting usernames/passwords for use with PAM (the feature currently uses OTP authentication), but it seems like that would be a relatively straightforward addition.  If SSH user/password authentication is being used, then the Session Manager could automatically feed those credentials into the VNC authentication layer, since everything is being tunneled through SSH anyhow.

**Comment by kokoko3k** [comment]
Thanks, it sound interesting, i might have some time to test it when i'll be back to work.
However, i'm a bit worried about the cpu load on the server.
Is the image data encripted via ssh as well?
At full load our server needs to serve 60 clients and they use a quality of 70 and a quality of 90 via alr every 0.2 seconds.
With this quality, the measured network traffic made by a single client can reach 20/30mbps and I'd say that i can expect a total network load of about 300mbps (10/60 clients needing full bandwidth) which can be quite intensive.
However it is definitely a VERY nice feature.

**Comment by dcommander** [comment]
The CPU overhead of SSH shouldn't be much, but test it and let me know.  You can always disable the "automatic" mode of the TurboVNC Session Manager by passing `-nosessmgrauto` to the viewer.  That would allow you to use the session manager without encryption and with your chosen authentication scheme (which may be necessary because of your server-side PAM requirements), but I would also welcome feedback regarding how to make that more seamless.
