### ISSUE TITLE
"Empty Password" with no bypass setting or other workaround

### ISSUE THREAD

**Issue by DeeeeLAN** [TurboVNC/turbovnc#212]
I attempted to connect to my VNC session using the TurboVNC GUI but was unable to because my VNC session does not have a password, which is apparently not a currently supported configuration of TurboVNC.

**Comment by dcommander** [comment]
Referring to https://cdn.rawgit.com/TurboVNC/turbovnc/2.2.4/doc/index.html#hd008005 and the man page for Xvnc (`man -M /opt/TurboVNC/man Xvnc`), no authentication is supported, but this authentication method is not enabled by default.  Pass `-securitytypes X509None,TLSNone,None` to `/opt/TurboVNC/bin/vncserver` to enable it, or add those security types to `permitted-security-types` in **/etc/turbovncserver-security.conf**.

**Comment by DeeeeLAN** [comment]
The server is not the issue, that is already set up and working fine. What is failing is the client GUI. I can log in with other clients without entering a password but TurboVNC fails with the empty password error.

**Comment by dcommander** [comment]
Please refer to the documentation I recommended above.  TurboVNC supports various security types, where a "security type" encapsulates a specific server-side "authentication method", a specific client-side "authentication scheme", and a specific "encryption method."  The security types that allow no password are not enabled by default.  You have to enable them as described above.  You aren't providing very much in the way of diagnostic information.  Some of what you said implied that you are not using the TurboVNC Server, but you haven't specified which server you are using.  You also haven't specified how that server is configured or which VNC viewers you used that worked properly.  I am just explaining how *our* solution works and how to enable password-less connections using our server.

**Comment by DeeeeLAN** [comment]
The server in use is TigerVNC Server version 1.8.0. I am able to connect without a password using both TigerVNC viewer and RealVNC viewer. Here is the command that runs to start the server instance:
```
/usr/bin/Xvnc :20 -bs -auth ~/.Xauthority -depth 24 -desktop foo -fp catalogue:/etc/X11/fontpath.d -geometry 1920x1200 -pn -rfbauth ~/.vnc/passwd -rfbport 5920 -rfbwait 30000 -once -DisconnectClients=0 -AlwaysShared passwordFile=~/.vnc/passwd -extension MIT-SHM -BlacklistThreshold=0 -BlacklistTimeout=0
```

**Comment by dcommander** [comment]
I can't reproduce that.  Which version of the TigerVNC viewer?  How are you configuring the viewer?  I assume that **~/.vnc/passwd** does not exist on the server?  Otherwise, I have no idea how you are specifying an empty password, since `vncpasswd` (both our implementation and TigerVNC's) does not accept a password less than six characters.  I started a TigerVNC Server session using TigerVNC 1.8.0 and exactly the same command line that you posted above.  When attempting to connect to the session using both the TigerVNC and TurboVNC viewers, they both complain that there is no password configured.  That is the correct behavior, because you're starting the server with `-rfbauth` and `passwordFile`, which means that you intend for the server to use the VNC Password authentication method.  You can't use VNC Password authentication with an empty password.  The correct and standard way to authenticate with a VNC session with no password is to enable the `None` authentication method, which is not enabled in either the TurboVNC or TigerVNC server by default.  If I add `-securitytypes TLSNone,None` to your server command line, then both TigerVNC and TurboVNC viewers connect successfully.
