### ISSUE TITLE
Too many authentification failures

### ISSUE THREAD

**Issue by arthursw** [TurboVNC/turbovnc#218]
I use TurboVNC with [noVNC](https://github.com/novnc/noVNC) and [nginx](nginx.com) to give access to a computer (a Scaleway instance) to some users from anywhere.

I use the default TurboVNC password authentification.

I would like to know a way to prevent the "Too many authentification failures" error which prevents users from connecting to my machine. This happens because of bots trying to bruteforce the machine.

I though of using [recaptcha](https://www.google.com/recaptcha/intro/v3.html) but I don't know the best way to integrate it.

Maybe with [nginx_http_recaptcha_module](https://github.com/yaoweibin/nginx_http_recaptcha_module)? 
I could also implement something by hand, but I'm not sure how to do it.

I also thought about using [nginx rate-limiting](https://serverfault.com/questions/1015772/prevent-vnc-too-many-authentication-failures-error-with-nginx-rate-limiting) but I don't think this would help.

Is there a better way?

**Comment by dcommander** [comment]
That is a function of the VNC server.  The TurboVNC Server is hard-coded such that, after 5 unsuccessful login attempts, it will block logins for 10 seconds * the number of unsuccessful attempts beyond 5.  It would be straightforward to improve that feature such that:

1. The blacklist threshold (the number of unsuccessful login attempts) and the blacklist timeout (the time period during which logins are blocked) are configurable.
2. The server only blocks logins from the IP address from which the unsuccessful login attempts originated.

I'm happy to make those improvements.  In general, however, it's a pretty bad idea to run a VNC server on the open Internet.  TurboVNC recently underwent a thorough security review by Kaspersky, and they found one flaw (CVE-2019-15683) that we fixed in 2.2.3, but in general, security testing of VNC solutions is not widespread or frequent enough to provide the necessary level of confidence for exposing those servers on the Internet.  Personally, I would not put a VNC server on the Internet unless it was behind an SSH gateway.

**Comment by arthursw** [comment]
Thank you very much for your detailed answer.

I will only use this VNC server for a few weeks so I hope I won't have any trouble in this short period of time.

**Comment by arthursw** [comment]
I could not find the behavior you described in the documentation; maybe that's the only thing to change: update the documentation to explain how TurboVNC behaves when too many authentications fail.

**Comment by dcommander** [comment]
That code was inherited largely unchanged from TightVNC 1.3.x, and this is the first time in 16 years of TurboVNC's history that anyone has taken issue with it.  I think the best course of action would be to implement the enhancements I described above, which will give me an opportunity to document the feature in the Xvnc man page in the context of describing what the new settings do.  Leaving this open until I can implement that.

**Comment by dcommander** [comment]
The master branch (which will become 2.2.6) now documents the VNC/OTP auth fail temporary connection blocking feature in the Xvnc man page and usage info and allows that feature to be configured or disabled using two new Xvnc options (`-maxauthfails` and `-authfailtimeout`.)  The dev branch (which will become 3.0 beta1) now tracks VNC/OTP auth fails on a per-IP-address basis and temporarily blocks connections only from the IP addresses that have exceeded the failure limit.
