### ISSUE TITLE
Using dev branch + websockets

### ISSUE THREAD

**Issue by webpolis** [TurboVNC/turbovnc#219]
Hi

I strongly rely on the websocket capabilities so I switched to using the dev branch instead of release one. But, using noVNC, without proxying, the websocket initiates negotiation but it always stops with:

`￹STDVVNCAUTH_￹TGHTULGNAUTH￹VENCVENCRYPT`

I tried with both ws and wss and I haven't defined any specific security types, just went with default:

`vncserver :99 -depth 16 -rfbport 12002 -rfbauth /home/user/.vnc/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3 -fp /usr/share/fonts/X11/misc -geometry 1366x912 -xstartup /home/user/.vnc/xstartup.turbovnc`

Am I missing anything? Any clue is appreciated. I'm generating the password using `x11vnc's -storepasswd` which worked with other servers (tried x11vnc's server, Tightvnc, tigervnc).

Any help is appreciated.

**Comment by dcommander** [comment]
Not sure.  How are you serving up the noVNC files?  You need some sort of simple HTTP server in order to do that, which is why the tip of the TurboVNC dev branch now includes one (**/opt/TurboVNC/bin/webserver**).  The vncserver script will automatically invoke that simple HTTP server if you supply an argument of `-novnc {path_to_noVNC}`. 

I can't reproduce the problem.  Using the latest tip of our dev branch and the latest tip of the noVNC master branch, I ran:

```
vncserver :99 -rfbport 12002 -novnc {path_to_noVNC}
```

That seems to contain the relevant elements from your command line.  The noVNC URL it returned was:

```
http://bullwinkle:5899/vnc.html?host=bullwinkle&port=5999
```

That is incorrect, because it isn't taking into account the `-rfbport` argument.  Replacing the URL with 

```
http://bullwinkle:5899/vnc.html?host=bullwinkle&port=12002
```

I can connect successfully.  Note that you won't be able to connect with wss unless you specify an X.509 certificate and private key using the `-x509key` and `-x509cert` arguments.  The vncserver script will automatically populate those arguments with, respectively, **~/.vnc/x509_cert.pem** and **~/.vnc/x509_private.pem**, if those files exist.

**Comment by dcommander** [comment]
In short, you haven't yet given me enough data in order to successfully reproduce and diagnose the problem.  So apparently I'm missing something at the moment.

**Comment by webpolis** [comment]
Weird.. 

I'm using the [RFB](https://github.com/novnc/noVNC/blob/master/core/rfb.js) class directly basically replicating their (example)[https://github.com/novnc/noVNC/blob/master/vnc_lite.html#L169].

I've just the *wsProtocols* setting for the RFB's constructor options, from **base64** to **binary** and works. Using base64 doesn't work with TurboVNC

**Comment by webpolis** [comment]
Also, I have a question:

The RFB class has an option:

```
compressionLevel

Is an int in range [0-9] controlling the desired compression level. Value 0 means no compression. Level 1 uses a minimum of CPU resources and achieves weak compression ratios, while level 9 offers best compression but is slow in terms of CPU consumption on the server side. Use high levels with very slow network connections. Default value is 2.
```

Does it have any effect?
Also, I wonder why the WebSocket doesn't respond to the header:

```Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits```

What are the considerations to have in mind in order to increase performance?

Thanks

**Comment by dcommander** [comment]
The compression levels are described here:
https://cdn.rawgit.com/TurboVNC/turbovnc/master/doc/index.html#hd007

noVNC uses the 0-9 quality scale, and how that maps to actual JPEG quality and subsampling levels is described here:
https://cdn.rawgit.com/TurboVNC/turbovnc/master/doc/index.html#hd0010
(Our server uses the same mapping as the TigerVNC Server.)

TurboVNC is just borrowing the WebSockets code for LibVNCServer.  I don't know much about the difference between base64 and binary, but the commit status of https://github.com/LibVNC/libvncserver/commit/c7c77de60914c9f52224f98d75ae412b66e9c864 and some of the comments on noVNC issue threads suggest that base64 was never really a standard, so its implementation in the LibVNCServer code is only meant to support certain legacy clients.

**Comment by webpolis** [comment]
Awesome, thanks for the references. I apologize for being so lazy and going deeply into the dependencies, but I was confident your'll point to the right source.
