### ISSUE TITLE
Support for TightVNC server File transfer and Scale:Auto

### ISSUE THREAD

**Issue by necros2k7** [TurboVNC/turbovnc#226]
subj

**Comment by dcommander** [comment]
The TurboVNC Viewer already supports client-side scaling.

File transfer will not be supported, for reasons described in https://github.com/TurboVNC/turbovnc/issues/97.

Summary:
- VNC file transfer has only ever been implemented with Windows VNC servers.  It doesn't make much sense for Un\*x VNC servers, since there are many better ways to transfer files to/from Un\*x machines.  Whereas the TurboVNC Viewer works with a variety of VNC servers, we do not provide a VNC server for Windows.  Thus, it doesn't make sense to implement or support a feature that would only be useful with other people's VNC servers.
- VNC file transfer is considered a security risk.

As I stated in #97, I would be willing to upgrade the existing file transfer implementation in the native Windows TurboVNC Viewer so that it supports modern versions of the TightVNC Server.  That would have to be a funded development project, the fix would only apply to Windows clients, and the fix would likely only be available in a sustaining unofficial build (since 2.2.5 is likely to be the last release in the 2.2.x series.)
