### ISSUE TITLE
About html

### ISSUE THREAD

**Issue by xspython** [TurboVNC/turbovnc#232]
Hello, do you have any HTML development plans recently? Now Java and python are too difficult to use ！

**Comment by dcommander** [comment]
I don’t understand what you’re asking. Our project doesn’t use Python at all. Our viewer uses Java, but it isn’t difficult for an end user to install Java, and with TurboVNC 3.0, the JRE is embedded in the viewer, so it is no longer necessary to install Java. TurboVNC 3.0 also integrates with noVNC, an HTML 5/JavaScript VNC viewer that runs in a web browser (but with reduced performance compared to the Java viewer.) If none of that answers your question, then please clarify.

**Comment by xspython** [comment]
Have you ever thought about replacing java with other languages, such as Google dart? Novnc does not support desktop adaptation

**Comment by dcommander** [comment]
What do you mean by "desktop adaptation?"  If you mean automatic desktop resizing, then noVNC does support that, but the feature isn't enabled by default.

As far as languages, it isn't just a matter of "replacing" Java.  I have been an independent open source developer since 2009.  I don't get paid a salary for maintaining libjpeg-turbo, VirtualGL, or TurboVNC, so the only way I can implement major features is through funded development.  The TurboVNC Viewer uses Java because, back in 2012, I received funding to rewrite the viewer in Java.  At the time, the funding came from a company that was interested in laying the groundwork for an Android TurboVNC Viewer (which never came to fruition) and another company that was interested in using the TurboVNC Viewer as a browser-based applet (which you can't do anymore with Java.)  I had also proposed, at the time, developing a cross-platform native TurboVNC Viewer using GTK, but that project never received funding, so it never happened.  Thus, as the Java TurboVNC Viewer gained traction as a cross-platform TurboVNC Viewer, it received funding for new features, and it has reached the level of maturity at which it will become the only TurboVNC Viewer in TurboVNC 3.0.  TurboVNC 3.0 includes an embedded JRE on Mac, Windows, and Linux, so from the end user's point of view, they will never notice that the viewer is written in Java.  It will behave just like a native application.

The Java TurboVNC Viewer is no longer a zero-install viewer as it used to be.  It is now used as a standalone application.  For a zero-install viewer, we support noVNC in the evolving TurboVNC 3.0 code base.  In the long term, I have funding for research into a WebAssembly TurboVNC Viewer, but currently that technology has fundamental issues that prevent it from working with a VNC viewer.  I'm continuing to monitor its progress.  I don't have the resources to learn a new language right now, nor to completely rewrite the TurboVNC Viewer using another language and GUI framework.  I have no experience with Dart nor any sense of whether it can provide the performance and deployment options that we need.
