### ISSUE TITLE
two issues related to auto scaling during in the turboVNC client

### ISSUE THREAD

**Issue by naatje80** [TurboVNC/turbovnc#233]
We are encounter two bugs that both seems to be related to scaling in the TurboVNC client:

1. The first issues seems to cause that the gnome desktop environment to moves all active Windows to the current virtual desktop. This only happens once in a while during auto resizing, when moving the TurboVNC cliet Window between multiple monitors. I was able to reproduce the issue by:
a. Start the VNC server
b. Connect to the server using the turbovnc client
c. Open various application on multiple virtual desktops within the Gnome shell desktop environment
d. Move and maxime the TurboVNC client Window between the multiple physical monitors. After a couple of times it will cause some kind of "crash" and Windows will be moved from the the virtual desktops to the currently selected virtual desktops. At first I thought it would be related to differnt resolution setup of each monitor. In my case I'm using my notebook and secondary monitor with same resolution (1920x1080), but even then I'm encoutering the issues.

2. The second issue is causing the maximization to break when multiple sessions are started. Although it is not always reproducable, it seems to occure quite often when executing the following steps:
a. Start two VNC servers sewssion
b. Connect to the 1st session using the TurboVNC client. Maximize and de-maximeze the window again. 
c. Connect to the 2st session using a new session of the TurboVNC client. Not always, but quete often the auto resizing during maximization is broken within this new Window.

Although we are using TigerVNC as VNC server, both issues are reproducable when using the TurboVNC server instead. So I assume both issues are related to the TurboVNC client, and not the TigerVNC/TurboVNC server. 

We are using: 
	- TurboVNC 2.2.5 client on Windows 10
	- TigerVNC 1.10.1 (but also tested with TurboVNC 2.2.5) server on Scientic Linux 7.7. The server is starting a gnome shell desktop session.
	
I hope you will be able to reproduce and solve both issues. In case you need more information, please let me know.

**Comment by dcommander** [comment]
I'll take a look and try to understand what's happening.

**Comment by naatje80** [comment]
@dcommander Thank you for your quick response. It is indeed difficult to explain if you are not able to see it for yourself. If required, I could make video again if you are not able to reproduce it yourself.

**Comment by naatje80** [comment]
@dcommander Were you able to reproduce one (or both) of the issues? Please let me know if you require some additional information from our side.

**Comment by dcommander** [comment]
I have been really busy with VirtualGL for the past couple of weeks.  I'll try to look into the issue today.

**Comment by naatje80** [comment]
I understand. Please take your time.

Op do 10 sep. 2020 om 17:09 schreef DRC <notifications@github.com>:

**Comment by dcommander** [comment]
The first issue seems to be related to the feature in our viewer that automatically reconfigures the server's Xinerama screens such that the screen boundaries align with the client's screen boundaries.  This will happen if the viewer window is resized and the window straddles multiple screens after the resize.  Unfortunately, GNOME 3 doesn't seem to like the Xinerama screens being reconfigured on the fly.  (Chalk that up to yet another issue with GNOME 3 in a remote display environment.)  If you don't care about Xinerama or multi-screen spanning with the TurboVNC Viewer, then the easiest way to get around the issue is to set `TVNC_SINGLESCREEN=1` in the environment on the client.  That will restore the automatic desktop resizing behavior of TurboVNC 2.1.x, which did not support Xinerama.  Another workaround is to use MATE on the server, which seems to handle the dynamic changing of Xinerama screens properly.

**Comment by dcommander** [comment]
As far as the second issue, I can reproduce it, but it appears to also be a GNOME 3 issue, probably related to the fact that multiple GNOME 3 sessions share the same XDG runtime directory (and thus some of the same configuration) when launched from TurboVNC.  I unfortunately don't know of a way around that.  If you're feeling adventurous, the new release of the TigerVNC Server jettisons vncserver altogether in favor of a systemd-based VNC server launch mechanism, which may be more GNOME 3-friendly.  That new mechanism unfortunately requires a static mapping between users and VNC display numbers that is configurable only by root, so it's a non-starter for TurboVNC at the moment, but it would be a useful data point to know whether that mechanism addresses the second issue.  If it doesn't, then I don't know what would.  Unfortunately, most of the innovations in Linux in recent years-- Wayland, systemd, GNOME 3, Vulkan, etc.-- have been designed without much thought toward remote display.  Those innovations have made my job much more difficult, and yet I'm still just one person trying to maintain products that used to have the weight of a Fortune 500 company behind them.  Most commercial TurboVNC deployments use MATE or another WM that is a better fit for X proxies.  I have tried my best to work around as many GNOME 3 issues as I can, but ultimately GNOME 3 just wasn't designed to be run in a user-space X proxy, so the expectation should be that it will be usable in a TurboVNC session, but it will have some issues.

**Comment by dcommander** [comment]
Feel free to add follow-up comments/questions, but I'm closing this issue for now, since it seems to be mainly an interaction issue with a specific WM rather than an actual bug in TurboVNC.

**Comment by naatje80** [comment]
Thank you for your update on both issues and for your time to take a look at it. It is really appreciated! But in my experience, even with a Fortune 500 company, is that the are not always able to fix (or willing to fix) a certain issue. The direct contact often even lacks the right experience and it is often difficult to direct contact a develop with the right knowledge. I have the best experience with open source and people like you to really doing their best to keep the a product stable and working like it should (as far as possible of course).  I will suggest the user(s) affected by the first issue to use the environment variable TVNC_SINGLESCREEN=1 in his environment. Concerning the second issue: we already considered MATE, but unfortunately RedHat decided to only support the Gnome Desktop from now on. The epel repo includes builds for MATE, XFCE, KDE and other desktop environments, but my experience with epel is not that great for usage in a stable commercial environment. But possible we have to reconsider in the future if more changes could affect the environment. Maybe if I get some time for it in the near future I could check if I'm able to find a fix for it. I was able to fix some other issues in opensource projects that were specific to our environment. If I'm able to find a possible solution I will certainly create a pull request for it. For now, we will just have to live with it. It is not critical, but at most only annoying sometimes. Thank you again!

**Comment by dcommander** [comment]
Yes, working for a Fortune 500 company was a tradeoff.  I spent probably 3/4 of my time on things that had no bearing on the long-term health of the open source projects-- corporate administrivia and supporting the company's obsolete platforms, platforms that were quickly killed or refocused away from 3D graphics once the company was acquired.  After being laid off, I decided to become an independent developer because it allowed me to focus more on the users and the technology, even though I am making 1/4 to 1/3 of the money that I could make as a corporate employee.  However, the Fortune 500 company did have the ability to steer technology in ways that I can't.  I meant mainly to highlight the fact that, in 2005, the solution to these problems was a lot simpler than it is now, and there were more people actively working on it.  In the grand analysis, I would still rather be independent than corporate, but I also really miss the days when I could just run `/etc/X11/xinit/xinitrc` in a TurboVNC session and expect it to work.  The difficulty these days has a lot to do with open source developers choosing form over function.  That isn't just a trend in open source, unfortunately.

Red Hat doesn't officially support MATE in RHEL 7, but they also don't support TurboVNC.  The configuration they supposedly do support is the GNOME 3 Classic session in TigerVNC (on RHEL 7, GNOME 3 Classic is what you get if you run `/etc/X11/xinit/xinitrc`.)  I've verified that the first issue is reproducible with GNOME 3 Classic, and I expect that the second one probably is too, so it might be worthwhile to pursue the matter with Red Hat.  It's probably possible to emulate what the TurboVNC Viewer is doing, vis-a-vis reconfiguring the Xinerama screens, with a sequence of `xrandr` commands.

Since MATE isn't available in RHEL 8, we're going to have to figure something else out before RHEL 7 becomes EOL.  I hope that the systemd-based launcher in TigerVNC may improve to the point that it no longer requires a static user/display mapping.  Honestly, if Red Hat or another company that is as invested in open source decided that they really wanted to support remote display, then they could make it happen in ways that I couldn't.  I feel like I have a lot more flexibility to help users these days but also a lot less power, and that's a source of my frustration.  I feel like a lot of companies that benefit from these technologies don't invest in them in sustainable ways (even Red Hat, which co-founded TigerVNC, doesn't actively participate in its development anymore.)
