### ISSUE TITLE
Font issues in latest build

### ISSUE THREAD

**Issue by loganmc10** [TurboVNC/turbovnc#24]
I'm running into font issues in the latest (Dec 17 http://turbovnc.sourceforge.net/vnc.nightly/) build.

I ran into these issues when I built TurboVNC myself, but I thought it was just my system.

These are the messages I get in my VNC log file:
_FontTransOpen: Unable to Parse address catalogue:/etc/X11/fontpath.d
[dix] Could not init font path element catalogue:/etc/X11/fontpath.d, removing from list!

And when I open an xterm:
Warning: Cannot convert string "nil2" to type FontStruct
xterm: cannot load font 8x16

The result: the Xvnc server runs, but the fonts are all wrong and tiny. When I built TurboVNC myself, Xvnc wouldn't start at all, and I had to add:
-xkbdir /usr/share/X11/xkb
To the "vncserver" command, this made Xvnc start, but the fonts were still incorrect and I had those same error messages.

I don't have these issues in TurboVNC 2.0.1. My system is RHEL 6.

**Comment by dcommander** [comment]
The font issue has been fixed in master.

RE: the XKB issue, I can't reproduce.  The default path hard-coded into Xvnc when it is built is /usr/share/X11/xkb, which is correct for RHEL 6.  Note that this can be changed at build time by modifying the XKB_BASE_DIRECTORY CMake variable, so you might want to run `ccmake {source directory}` from your build directory and double-check that the XKB_BASE_DIRECTORY variable is sane.
