### ISSUE TITLE
Add an option to grab the keyboard only when the viewer has focus

### ISSUE THREAD

**Issue by Ennea** [TurboVNC/turbovnc#247]
I use TurboVNC as a viewer strictly in windowed mode, and switch into and out of it quite frequently. An option to only grab the keyboard while the viewer has focus would be very beneficial.

**Comment by dcommander** [comment]
It should already do that, assuming you're on a Windows or Linux client (the Mac TurboVNC Viewer doesn't implement keyboard grabbing, because keystrokes such as Alt-Tab aren't intercepted to macOS.)  If you set the keyboard grab mode to `Always`, then clicking outside the TurboVNC Viewer window will cause grabbing to temporarily be turned off until you click back in the TurboVNC Viewer window.

**Comment by Ennea** [comment]
You're right, that does work! I only tested this earlier, and it still captured Alt-Tab when the viewer was out of focus (I'm on Windows btw). I cannot reproduce this again, however. I thought maybe starting the viewer with the "Fullscreen only" grab option and switching it to "Always" after it was running would cause it again, but now it just keeps working properly. I'll see if I can stumble upon it acting wonky again and re-open this with instructions to reproduce. Until then, closing this. Thank you!

**Comment by dcommander** [comment]
Cool.  If you are able to repro the issue, let me know.  Also bear in mind that you can use Ctrl-Alt-Shift-G to disable and enable keyboard grabbing on the fly.  When the grab mode is "Manual", the viewer will only re-enable grabbing when the window re-gains focus if grabbing was already enabled when focus was lost.
