### ISSUE TITLE
Allow unversioned libssl and libcrypto

### ISSUE THREAD

**Issue by Parakleta** [TurboVNC/turbovnc#252]
The following code doesn't work on my machine because the version of OpenSSL is newer than allowed for in the suffix list.

https://github.com/TurboVNC/turbovnc/blob/f88a93f3c7f3d6ec021cc72ca555a38abc7ece27/unix/Xvnc/programs/Xserver/hw/vnc/rfbssl_openssl.c#L225-L234

I would propose changing this to something like:

```c
    for (i = 0; i < SUFFIXES; i++) {
      snprintf(libName, 80, "libssl.so.%s", suffix[i]);
      dlerror();  /* Clear error state */
      if ((sslHandle = dlopen(libName, RTLD_NOW)) != NULL)
        break;
    }
    if (sslHandle == NULL) {
      snprintf(libName, 80, "libssl.so");
      dlerror();  /* Clear error state */
      sslHandle = dlopen(libName, RTLD_NOW);
    }
    if (sslHandle == NULL) {
      rfbErr("Could not load libssl\n");
      return -1;
    }
```

This would allow opening the platform's default version of `libssl.so` which in many instances is a symlink to the latest version.

The same change would need to be applied to the loading of `libcrypto.so` later in the same function.

**Comment by dcommander** [comment]
That’s a good idea, but I would also like to specifically handle the version on your machine. What is the suffix?

**Comment by Parakleta** [comment]
111 is the suffix, for OpenSSL 1.1.1d/h in FreeBSD 12.1/12.2

**Comment by dcommander** [comment]
OK, I’ll take a look at it using my FreeBSD 12 VM.

**Comment by dcommander** [comment]
I modified **rfbssl_openssl.c** so that it specifically looks for **libssl.so.111** and **libcrypto.so.111**, which fixes the issue for now.  When I developed the OpenSSL back end for the TurboVNC Server, I consciously decided not to search for **libssl.so** and **libcrypto.so**, because those aren't generally available unless you install a separate OpenSSL developer package.  Furthermore, for security reasons, the TurboVNC Server tries to search for the OpenSSL library suffixes in descending order, so it can load the most recent version of OpenSSL on systems that have multiple versions (that allows it to use the most recent cipher suites.)  On FreeBSD specifically, it's possible to have **libssl.so** and **libcrypto.so** installed both in **/usr/lib** and **/usr/local/lib** (i.e. there is a system version as well as a version installed from the **openssl-devel** port.)  That makes it a bad idea to load **libssl.so** or **libcrypto.so**, because the version in **/usr/local/lib** is currently the 3.0.0 alpha version.

This OpenSSL run-time selection stuff is primarily intended for cross-distribution compatibility-- that is, for the purpose of building a single binary and running it on multiple O/S distributions.  If you are building the TurboVNC Server for a single O/S distribution, then you can safely disable the `TVNC_DLOPENSSL` CMake variable.  That will link Xvnc against a single version of OpenSSL and use only that version at run time.

**Comment by Parakleta** [comment]
I thought about static linking but then I wouldn’t have access to security updates in the libraries without rebuilding.  Having hard coded version numbers risks a similar problem (although less severe since many security updates wont change the version).

**Comment by dcommander** [comment]
I wouldn’t expect FreeBSD to change OpenSSL in an incompatible manner until FreeBSD 13 is released.
