### ISSUE TITLE
Lossless Refresh not kicking in when application is generating identical frames

### ISSUE THREAD

**Issue by ChipmunkV** [TurboVNC/turbovnc#260]
OpenGL application producing identical frames and rendering them (`glXSwapBuffers`). Two issues with that:
* the interframe detects that the images are identical so it sends a 1-pixel fillRect update for every frame application generates
* the ALR timer seems to be reset every frame so there is no ALR ever happening

The test example is a modified `glxgears` where we aren't rotating the gears:

[glxgears-stationary.c.zip](https://github.com/TurboVNC/turbovnc/files/5785832/glxgears-stationary.c.zip)

    gcc glxgears-stationary.c -lGL -lX11 -lm -o glxgears-stationary

Running:

    vncserver :101 -alr 1 -interframe
    DISPLAY=:101 vglrun glxgears-stationary

Does it make sense to get rid of the 1-pixel fillRect updates in this case?
Should we avoid resetting ALR timer?

**Comment by dcommander** [comment]
Interframe comparison once behaved as you propose in PR #261, i.e. it avoided sending a framebuffer update (FBU) if all of the pixels in the FBU were duplicates.  However, that proved to be incompatible with "traditional" VNC viewers.  Traditionally, VNC used a client-pull protocol (and, in fact, all VNC implementations other than TigerVNC and TurboVNC still do.)  The server did not send a FBU unless a viewer first sent a framebuffer update request (FBUR), and the viewer did not send a new FBUR until after it received a FBU.  Unfortunately, the original approach to interframe comparison caused an infinite loop whereby, as soon as a FBU was completely eliminated by interframe comparison, no further FBUs would be sent to traditional VNC viewers.  From the point of view of those viewers, it appeared as if the VNC server had frozen.  The solution, introduced in 24027618adb1a58eac55713764eb5fee96373ad0, was to send an empty FBU (an FBU with zero rectangles) if interframe comparison eliminated all of the pixels within it.

The behavior of ALR should not be dependent upon interframe comparison, so the underlying problem here is with ALR: how can it handle duplicate framebuffer updates, irrespective of whether interframe comparison is enabled?

Closing #261.  We can continue the conversation here.  I'll look into the issue further and see if I can come up with a solution that makes both of us happy.

**Comment by dcommander** [comment]
After pondering this for a bit, I think the best course of action is for ALR to ignore redundant framebuffer updates if interframe comparison is enabled.  That should be an easy fix.  Even though ALR is driven by the server, it is ultimately centered around user interaction.  The User's Guide even says as much:

"The ALR feature is designed mainly for use with interactive visualization applications. The idea is that, on a low-bandwidth connection, low-quality JPEG can be used while the 3D scene is rotated/panned/zoomed, but when the motion stops, a fully lossless copy of the 3D image is sent and can be studied in detail."

"When the motion stops" should certainly include cases in which the motion stops due to an ill-behaved 3D application that is repeatedly rendering duplicate frames.  The User's Guide even mentions the specific case of "ill-behaved window managers" that can defeat ALR by repeatedly rendering duplicate pixels (that was a problem with a long-obsolete version of GNOME, if memory serves.)  Since ALR predates interframe comparison by several years, I didn't revisit the possibility of eliminating that issue in ALR when interframe comparison was implemented.

**Comment by dcommander** [comment]
The documentation also says,

"ALR will monitor all of the VNC viewer connections, and if more than _`timeout`_ seconds have elapsed since the last framebuffer update was sent to a given viewer, then the TurboVNC Server will send to that viewer a mathematically lossless copy of any 'ALR-eligible' screen regions that have been affected by lossy compression."

The spirit of this could certainly be interpreted to mean "the last framebuffer update that actually contained pixels."

Sorry if this comes across as over-explaining.  I'm repeating my thoughts aloud to make sure I'm not missing anything.

**Comment by ChipmunkV** [comment]
From reading the comments in the code I thought that the old viewers are specifically allergic to the empty FBUs but they will work fine with 1x1 rectangle updates or no updates at all.

> After pondering this for a bit, I think the best course of action is for ALR to ignore redundant framebuffer updates if interframe comparison is enabled. That should be an easy fix.

Yes, can do that. As I mentioned at the start: there are two issues: ALR not activating and repetitive 1x1 FBUs. That solves the ALR issue.

As for the second issue - empty FBUs that TigerVNC / TurboVNC / noVNC don't need: I've probably haven't seen an obvious way to distinguish between the case when a client needs FBU and the case when the server spams 1x1 FBUs needlessly.

**Comment by dcommander** [comment]
> From reading the comments in the code I thought that the old viewers are specifically allergic to the empty FBUs but they would work fine with 1x1 rectangle updates or no updates at all.

Yes, you're right.  My memory was faulty in that regard.  The issue was one of backward compatibility with older releases of the Windows TurboVNC Viewer, the Windows TightVNC 1.3.x Viewer, and perhaps the newer TightVNC v2.0 and UltraVNC Viewers (which both share the TightVNC 1.3.x legacy with TurboVNC.)

> As for the second issue - empty FBUs that TigerVNC / TurboVNC / noVNC don't need: I didn't immediately see an obvious way to distinguish between the case when a client needs FBU and the case when the server spams 1x1 FBUs needlessly.

It might be possible to turn off the empty FBUs for a particular viewer connection if the RFB ContinuousUpdates and Fence extensions are active on that connection.  If both of those extensions are active, then the TurboVNC Server will not rely on framebuffer update requests.  Those extensions will not be active if using a legacy VNC viewer that needs the empty FBUs.  However, unless the empty FBUs are causing a measurable performance problem, I'm not interested in eliminating them.  Doing so would require a lot of testing, and I don't have time to do that right now.
