### ISSUE TITLE
[vncviewer] `ssh.exe` does not fork on Windows.

### ISSUE THREAD

**Issue by Parakleta** [TurboVNC/turbovnc#264]
When creating the tunnel externally using `ssh.exe` on Windows, the viewer waits for the tunnel to be established successfully.  Unfortunately on windows `ssh.exe` cannot background due to a lack of proper process support so this just hangs forever.  This same limitation also applies to `plink.exe` (the putty command line utility).

https://github.com/TurboVNC/turbovnc/blob/8b3f5b2395e7603a6fb551d90c4585334434a5b1/java/com/turbovnc/vncviewer/Tunnel.java#L234

Maybe it would be possible to use the timeout variant of `waitFor` and then check the `exitValue()` explicitly?

**Comment by dcommander** [comment]
I've spent a lot of time in years past playing with this, and there unfortunately isn't a way to make it work without a forking SSH client.  Unless the external SSH client forks off, the only other option is to use the internal SSH client in the Java TurboVNC Viewer (which has the ability to go fork itself.)  All VNC viewers that support SSH tunneling have this same forking limitation, to the best of my knowledge (including the Windows TurboVNC Viewer.)  Cygwin and MSYS2 are the only forking Windows SSH implementations of which I'm aware.

**Comment by Parakleta** [comment]
I don’t understand what the problem is with just not using the indefinite version of `waitFor()`?  Effectively I am kludging around it horribly by using a VBScript wrapper which runs `ssh.exe` as a process and immediately returns which should be the same as if VNCViewer didn’t wait for the process to finish.

Is there something I’m missing?

**Comment by dcommander** [comment]
SSH clients sometimes have to authenticate interactively-- for instance, if the client falls back to password authentication because public key authentication fails or if the client has to ask for a public key passphrase.  The TurboVNC Viewer must block until that authentication is complete and the SSH tunnel has been successfully established, and the only way to do that is to use a forking SSH client.  If the external SSH process times out, then the TurboVNC Viewer has no way of knowing whether the tunnel has been established or not.  `Process.exitValue()` won't help, because from the point of view of Java, the external SSH process for a non-forking SSH client will not have exited.  Perhaps, due to a very slow network or the behavior of certain firewalls, `Process.waitfor()` could time out before we even knew whether the remote SSH server was viable.  Also, from the TurboVNC Viewer's point of view, it has no way of knowing whether a particular SSH client is forking or non-forking, so it would have no way of determining when it should use one approach or the other.  You may have been able to hack together a solution for a specific non-forking SSH client, but there are numerous ways in which that could fail in the general case.  It's just not supportable.

We support several methods of SSH tunneling on Windows-- the internal SSH client in the Java viewer and the Cygwin or MSYS2 external SSH clients.  Use one of those, please.

**Comment by Parakleta** [comment]
I can see that it is more complex than I had anticipated.  The difficulty I have currently is that I doubt I will be able to get anything Cygwin or MSYS2 approved by security, and the internal SSH client doesn't support forwarding of named pipes (which is fair, since the `ssh_config` file cannot describe them).

My workaround, just in case anyone else needs something similar, is to set `-Dturbovnc.tunnel=wscript ssh_tunnel.jse /host:%H /local:%L /remote:%R` and then have the following script:

```javascript
var WshShell = WSH.CreateObject("WScript.Shell");
var args = WSH.Arguments.Named;

var ssh_exec = '"ssh.exe"';
ssh_exec += ' -N -L "' + args.Item("local") + ':localhost:' + args.Item("remote") + '"';
ssh_exec += ' "' + args.Item("host") + '"';

WshShell.Run(ssh_exec, 0);
```
I ensure that key based authentication is configured and it seems to be working fine so far, although I may need to add a delay before returning if TurboVNC ever tries to connect before it is ready.  It does also have the problem that there is no simple way to end the `ssh` process when TurboVNC is finished.

**Comment by dcommander** [comment]
Yeah, those are exactly the reasons why using a non-forking SSH client and a `Process.waitFor()` timeout isn't supportable in the general case:
- It requires public key authentication with an SSH agent (to ensure that the passphrase doesn't have to be entered.)
- It sets up a race condition whereby the viewer will fail if the SSH client doesn't establish the connection before the viewer tries to use it.
- The SSH process will become orphaned.

JSch (the internal SSH client) does appear to have pipe forwarding support, so it may just be a matter of enabling it in the TurboVNC Viewer, but can you help me understand the use case for that?

**Comment by Parakleta** [comment]
My use case is the security of reverse tunnels.  If I am opening random reverse ports on a shared server if other users can guess the port number they can inject content into those tunnels back to the client machines.  If I set up a pipe in the user's local `.vnc` directory then only they can access it.  My current use is just for pulseaudio, but I may have use for usb/serial forwarding later.

Currently I open `-R /home/$user/.vnc/audio.socket:localhost:4713` on the VNC server, set the `PULSE_SERVER=~/.vnc/audio.socket` environment variable on the server, and just run pulseaudio accepting localhost only connections on the client.

**Comment by dcommander** [comment]
So your IT department is OK with you installing PulseAudio on your Windows machine but not MSYS2?

**Comment by Parakleta** [comment]
pulseaudio is a standalone (as in portable, non-installed) executable and doesn't provide or require any kind of shell access or tools.  It's in a school environment so everything shell related is locked down extensively, and anything with an installer needs to be vetted by a central off-site IT security department.  I'm actually using the VNC system so that I can give students access to an authentic (non-locked) environment I'm setting up on FreeBSD that I can the modify at will.  Even that has been a stretch and has required locking down the various components as much as possible.

Is there a security vulnerability with pulseaudio I should be aware of?  It doesn't run with any escalated privileges and is only running in client mode receiving audio on a localhost port and playing it to headphones.

**Comment by dcommander** [comment]
OK, well, you could also download the individual MSYS2 packages and install them manually, or you could forego using `-via` and set up the SSH tunnel manually in a different shell window prior to launching the TurboVNC Viewer.  If you set up the SSH tunnel manually, then you don't need a forking SSH client.  A forking SSH client is only needed because the TurboVNC Viewer has to ensure that the SSH tunnel is created before it tries to connect to the VNC server and because it has to close down that tunnel when the viewer exits.  You can do both things yourself.  Example:

```
ssh -L5901:localhost:5901 {vnc-server}
```
then leave that window open, launch the TurboVNC Viewer, and connect to `localhost:1`.

**Comment by dcommander** [comment]
And no, PulseAudio doesn't have any security vulnerabilities of which I'm aware, but of course, neither does MSYS2 OpenSSH.  That was my point.  My ability and willingness to accommodate particular IT policies in TurboVNC has a lot to do with how arbitrary they are, and this one is quite arbitrary IMHO.  Fortunately, you have a couple of ways to work around it yourself.
