### ISSUE TITLE
ALR seems unreliable.

### ISSUE THREAD

**Issue by Parakleta** [TurboVNC/turbovnc#265]
I don't know where to start with diagnosing this but I am happy to do any testing you require.

I am currently using IceWM as the window manager, and I have the `$autoLosslessRefresh` setting at 0.100 and have set the `TVNC_ALRALL=1` environment variable.  There are many instances where the screen doesn't do a lossless refresh, especially when an object is first rendered.  Interestingly, if I drag the object around then sometimes when I stop it does do the lossless refresh, but no amount of waiting will make it happen without other interaction.

The most noticeable and trivially reproducible of these is simply opening the application menu.

**Comment by dcommander** [comment]
Can you try the latest 2.2.x pre-release build and enable interframe comparison?  https://github.com/TurboVNC/turbovnc/commit/d4ad14ef3b3d1f889864cdea18e711ebb1d56829 uses the interframe comparison engine to prevent duplicate framebuffer updates from defeating ALR.

If that doesn't work, then there may not be much I can do about it at the moment.  ALR is really intended for use with VirtualGL, which is why it only monitors X11 PutImage requests by default.  With `TVNC_ALRALL=1`, ALR will respond to any kind of X11 request, so the blinking cursor in your shell will defeat it, and window managers are notorious for using `XCopyArea()` to draw the same image over and over again, which will also defeat ALR (unless you use the latest build and enable interframe comparison, per above.)

ALR was a funded development project for a medical visualization company (medical visualization users are ultra-paranoid about lossless image quality.)  I've maintained and fixed issues with it for 11 years, but in terms of its behavior, it largely "is what it is" unless some organization is willing to fund the development of a better solution.  TigerVNC, for instance, has a different take on the same problem, although their solution currently has other issues that I would have to work through before accepting it in TurboVNC.

**Comment by Parakleta** [comment]
I'm using the development version because I need the session management support (which is excellent by the way), and I updated yesterday specifically because I saw that patch and was hoping that it would fix the issue.

Interframe comparison is enabled in the Java VncViewer options, I assume there's no where else to do it.

It feels like the code is missing its last opportunity to trigger, because it renders blurry but then never comes back with the clean version after the delay.  Does the ALR run on a timer or does it trigger on the X11 updates if the interval was large?  If I have two updates at less than the ALR delay apart and then nothing would that prevent me getting the clean version (since there's no long delay update to trigger ALR)?

**Comment by dcommander** [comment]
> I'm using the development version because I need the session management support (which is excellent by the way), and I updated yesterday specifically because I saw that patch and was hoping that it would fix the issue.

Glad the Session Manager is working well.  I hope to be able to release 3.0 beta soon, but I still have probably 100 hours of work to do on it and no funding.  :(  But for the purposes of this bug, either the 2.2.x or 3.0 pre-release will work.

> Interframe comparison is enabled in the Java VncViewer options, I assume there's no where else to do it.

You can also force-enable it by passing `-interframe` to the server, but that isn't necessary.  Setting it in the viewer is sufficient.

> It feels like the code is missing its last opportunity to trigger, because it renders blurry but then never comes back with the clean version after the delay. Does the ALR run on a timer or does it trigger on the X11 updates if the interval was large? If I have two updates at less than the ALR delay apart and then nothing would that prevent me getting the clean version (since there's no long delay update to trigger ALR)?

No, basically:
- The TurboVNC Server tracks which rectangles of the remote desktop have been updated using a qualifying X request (PutImage only if `TVNC_ALRALL=0` or all X requests if `TVNC_ALRALL=1`.)  These rectangles comprise the "ALR-eligible region."
- For each connected viewer, the TurboVNC Server tracks which rectangles of the remote desktop have been sent using JPEG.  These rectangles comprise the "lossy region."
- For each connected viewer, if X seconds (where X is the value you passed to the server via the `-alr` option) have elapsed since the last [non-empty, non-duplicate] framebuffer update to that viewer, an ALR is sent for the intersection of the ALR-eligible and lossy regions.
- When an ALR is sent to a particular viewer, that viewer's ALR timer will reset, and that viewer's ALR-eligible and lossy regions will be cleared.

I'll see if I can reproduce the issue and figure out what's going on.  I don't discount the possibility of a bug.

**Comment by dcommander** [comment]
Unfortunately, I can't reproduce the issue.  I tried IceWM 1.3.8 on CentOS 7 and IceWM 2.0.1 on Fedora 33.  Please provide more specifics regarding your computing environment-- server and client operating systems, the speed of the network between the server and the client, and any non-default TurboVNC Server or Viewer settings you are using (other than the obvious ALR setting.)

**Comment by Parakleta** [comment]
You know what.  I cannot reproduce it now.

The only thing that I can think that I specifically changed is that I discovered that the pathing was causing the client machines to use some stripped windows version of JDK8 instead of JDK11 when running the VNC viewer.  I discovered that this was causing the `turbovnchelper.dll` to not load.  This appears to be the problem.

If I remove that `.dll` file the refresh issue occurs, and if I put it back everything is fine.  It wouldn't have occurred to me that the viewer could cause the problem.

**Comment by dcommander** [comment]
That is weird. I’ll investigate again. The helper on Windows shouldn’t affect blitting at all.

**Comment by Parakleta** [comment]
The other difference is that I am running on FreeBSD and so as per #251 threading is disabled in the server. (Although this hasn’t changed)

Something else that has changed now from previously is that the system has gone live and I am no longer the only user and am no longer on Display :1.

Not sure if any of that helps.

**Comment by ChipmunkV** [comment]
Yes, I see it sometimes. Using this script to vary latency and ping on local network interface `set-rate-delay.sh`:

```
#!/bin/bash

set -eu

if [ "$#" -ne 2 -a "$#" -ne 0 ]; then
	echo 'ERROR: zero or two parameters expected: rate and delay' >&2
	exit 1
fi

sudo tc qdisc del dev lo root handle 1:0 2>/dev/null || true

if [ "$#" == 2 ]; then
	sudo tc qdisc add dev lo root handle 1:0 netem delay "$2"
	sudo tc qdisc add dev lo parent 1:1 handle 10: tbf rate "$1" latency 10ms burst 1000000
fi
```

Usage:

    set-rate-delay.sh 8192kbit 180ms

**Comment by Parakleta** [comment]
I've been playing with it some more and the only reliably bad behaviour I still get is the initial render, but that might be a different thing.  When first logging in the screen is blurry and doesn't automatically refresh.

Regarding the other information you requested:  The server is FreeBSD, the client is Windows 10 using the java VNC viewer, I'm using the lowest preset quality settings, and we have a 200Mbit connection to the server.  The server and client are not on the same site, but close enough that the general latency should be negligible (in the order of 15ms), but I can check tomorrow.

I'll keep monitoring it to see if it occurs again and I can discover any patterns in behaviour.

**Comment by dcommander** [comment]
I can reproduce the issue with the initial screen refresh, but why that's happening is a mystery to me.  I can see the server send a full-screen ALR, and the only subsequent updates involve the clock area at the lower right.  So nothing should be overwriting the ALR.  I see that issue on a Mac client as well, so it's apparently a server issue.

**Comment by dcommander** [comment]
I think I figured it out.  What's happening is that the flow control extensions detect that the network is congested, and they prevent the automatic lossless refresh from being sent.  It's straightforward to modify the server so that it bypasses the flow control extensions when sending the ALR, but it's going to be important to set the ALR timer to a greater value than the network latency, or else you'll run into performance problems.

**Comment by dcommander** [comment]
I'm investigating this on a deeper level, because I may need to merge in some changes to the RFB flow control extensions from TIgerVNC.

**Comment by Parakleta** [comment]
That sounds very promising. Thanks.

**Comment by dcommander** [comment]
This should be fixed now.  The master (2.2.x) branch now:
- bypasses flow control when sending an ALR, to ensure that the ALR isn't deferred due to network congestion (because deferring it would cause it to be sent as a lossy refresh later on)
- automatically and temporarily increases the ALR timeout if it is less than 1.5x the network round-trip time (as measured by the RFB flow control extensions.)  This prevents ALRs from being continuously sent while the user is trying to interact with an application, which leads to flickering and poor performance.

The dev (3.0) branch also includes the latest congestion control algorithm enhancements from TigerVNC 1.9.0 and later, which (at least in my testing) seems to produce better throughput with the traffic shaper settings you're using.

Please test thoroughly and let me know if you find any issues.

**Comment by Parakleta** [comment]
Sounds good, I’ll rebuild against the dev branch on Monday and test on Tuesday and let you know.

Thanks again.

**Comment by dcommander** [comment]
Have you had a chance to test?  I am delaying the 2.2.6 release pending your results.

**Comment by Parakleta** [comment]
Sorry yes, it's all good now.  I cannot make it glitch at all.

Thanks very much.
