### ISSUE TITLE
Include support of -maxclients to vncserver/turbovncserver.conf

### ISSUE THREAD

**Issue by sigwx** [TurboVNC/turbovnc#268]
I ran across an instance where I needed more than the default 256 clients, and it seemed allowing for -maxclients to be configured via turbovncserver.conf was the logical place to add support to change the default.

**Comment by dcommander** [comment]
Can't you achieve the same thing by setting `$serverArgs = '-maxclients {foo}'`?

`$serverArgs` was introduced in order to avoid the need for configuration file variables that serve no purpose other than to pass arguments to Xvnc.  Going forward, I would like to use configuration file variables only for configuring the behavior of the `vncserver` or `xstartup.turbovnc` scripts.  Xvnc arguments need to be passed using `$serverArgs`.

**Comment by sigwx** [comment]
Yes, just thought it would be more convenient/obvious to give it its own
config file entry.   I see your point, feel free to drop the request :-)

Thanks for the info/feedback!
