### ISSUE TITLE
Add support for mousing in and out of viewer window grabing/releasing focus

### ISSUE THREAD

**Issue by hackonteur** [TurboVNC/turbovnc#27]
I use a Windows viewer to connect to a Linux server, where I use focus follows mouse. This would be particularly useful.

**Comment by dcommander** [comment]
Please clarify.  I'm not sure I understand what you're trying to achieve.

**Comment by hackonteur** [comment]
I have two monitors connected to a Windows machine. I run a VNC viewer fullscreen on 1 monitor. Since Windows is click-to-focus, it is possible for my mouse cursor to be inside of the VNC viewer, but still have a different Windows app getting focus, including typing and scrolling. I want the VNC viewer to claim focus whenever the mouse cursor enters that screen.

**Comment by dcommander** [comment]
There is no way that I know of for an application to do that on Windows, since the application is only notified of mouse events when its window has the mouse focus.  You're going to have to configure the client O/S (Windows) to enable "focus follows mouse" or use some sort of external utility to accomplish that (http://arstechnica.com/civis/viewtopic.php?t=1150437).
