### ISSUE TITLE
vnc-ltsp-config with TurboVNC

### ISSUE THREAD

**Issue by MoiseKans** [TurboVNC/turbovnc#271]
Hello,
This is the continuation of the issue 27 (https://github.com/TurboVNC/turbovnc/issues/270)

Indeed, I may have to explain a little bit more our infra :
-	We use NIS as user authentication
-	We have more than 10 different Linux workstations
-	Each colleague can connect on every workstations
-	We use generic account for some purpose i.e. many users use the same ID and password

What we used to do is :
-	Install tigervnc
-	Install vnc-ltsp
-	As it is described in chapter 5 : https://wiki.centos.org/HowTos/VNC-Server 
This configuration allows us to not launch a priori vncserver for each user and sessions close when you log off.
We do not have to configure user environment or password and so on.
More details about advantages are mentioned in the Chapter 5.

What we understand for tigervncserver is that this feature of simplicity with multi-gui session is no more available but is it not more related to vnc-ltsp ?
Do you thing that we can configure turbovncserver with vnc-ltsp ?
When we try to install vnc-ltsp RPM it indicates a missing dependencies with vnc-server.

We succeeded to user up-to-date tigervncserver with vnc-ltsp but we can not open a second gui session after the first session opened.
But if we launch at the same time 2 gui session, it works, as if some lock filed were created ?

Thanks

**Comment by dcommander** [comment]
I just tested that procedure on CentOS 7 with the TurboVNC Server.  It works as long as you change `XVNC=/usr/bin/Xvnc` in **/etc/sysconfig/vncts** to `XVNC=/opt/TurboVNC/bin/Xvnc`.  Also, I recommend that you remove any `-depth 16` arguments from the entries in **/etc/xinetd.d/vncts**, as TurboVNC performs best with depth 24.  Also, the use of different RFB ports for different geometries is unnecessary with TurboVNC, since the remote desktop can be dynamically resized.

Example configuration for two simultaneous instances:

`$ cat /etc/sysconfig/vncts`

```
## VNC Terminal Services Configuration

# Where is the Xvnc executable?
XVNC=/opt/TurboVNC/bin/Xvnc

# Default options to use
VNCTSOPTIONS="-inetd -once -query localhost -SecurityTypes None"
```

`$ grep vnc- /etc/services`

```
vnc-turbo0 5900/tcp
vnc-turbo1 5901/tcp
```

`$ cat /usr/share/vnc/vncts.services`

```
vnc-turbo0 5900/tcp
vnc-turbo1 5901/tcp
```

`$ sudo cat /etc/xinetd.d/vncts`

```
# default: off
# To use this remote vnc method: 
# * Allow local accesss to Xserver/XDMCP, add to /etc/X11/xdm/Xaccess:
#   localhost	
# Then, this server is accessible at vncviewer <server>:0-5

service vnc-turbo0
{
	disable	= no
	socket_type	= stream        
	wait		= no
	user		= nobody 
	group		= tty
	server		= /usr/bin/vncts
}

service vnc-turbo1
{
	disable	= no
	socket_type	= stream        
	wait		= no
	user		= nobody 
	group		= tty
	server		= /usr/bin/vncts
}
```

In the long term, you should consider migrating to the TurboVNC Session Manager. (It is not released yet, but you can evaluate it in the 3.0 evolving pre-release builds: https://turbovnc.org/DeveloperInfo/PreReleases.)  The TurboVNC Session Manager allows users to start and manage TurboVNC sessions remotely over SSH (the TurboVNC 3.0 Viewer has a built-in SSH client.) Thus, it solves much the same problem that you are solving with xinetd + XDMCP, only more securely.  The xinetd + XDMCP approach opens a lot of attack surfaces, unfortunately, which is why Linux distributions have stopped supporting that approach.  I'm not sure if the latest X.org releases even allow TCP connections anymore.
