### ISSUE TITLE
'double free or corruption' in ARM64

### ISSUE THREAD

**Issue by woowahan-jaehoon** [TurboVNC/turbovnc#276]
Hi.

I use turbovnc 2.2.6 in ARM64-based ubuntu 20.04.

For using TurboVNC in that, I built turbojpeg and turbovnc.

It seems to be perfect but it sometimes crashed with this log
```
double free or corruption (out)
(EE) 
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE) 
```

How can I find location of issue and fix it?

**Comment by dcommander** [comment]
Build the TurboVNC Server with debug symbols (`CMAKE_BUILD_TYPE=RelWithDebInfo` or `CMAKE_BUILD_TYPE=Debug`), start a TurboVNC Server instance, use `gdb attach {TurboVNC-Server-PID}` to attach GDB to the instance, and type `continue` in GDB.  When the error occurs, GDB will stop at that point in the code.

You can also use valgrind to detect double free()s.  In this case, however, you have to invoke `/opt/TurboVNC/bin/Xvnc` directly rather than using the `vncserver` script.
