### ISSUE TITLE
Multiple screens documentation

### ISSUE THREAD

**Issue by makspiechota** [TurboVNC/turbovnc#279]
Hi,
I'm unable to find any documentations/tutorials/tips on how to configure vnc server and/or client to render multiple virtual screens.
Could you provide me with any tips about that?

**Comment by dcommander** [comment]
Here are the various touch points:
1. You can configure the initial virtual screen layout of a TurboVNC session by using the `-geometry` argument to `vncserver`.  Our implementation accepts multi-screen descriptors, e.g. `-geometry 1920x1200+0+0,1920x1200+1920+0`.
2. You can configure the TurboVNC Viewer to always use the server's layout by setting the desktop size option to `server` in the TurboVNC Viewer (either via the `-desktopsize` command-line option or the TurboVNC Viewer Options dialog.)
3. You can change the screen layout within the TurboVNC session by using the `xrandr` command-line utility or any GUI application that understands the X11 RANDR extension.
4. If the TurboVNC Viewer is configured to use automatic desktop resizing, which it is by default, then the viewer window will span multiple screens depending on the span mode.  The default ("Automatic") is to span multiple screens only in full-screen mode, but you can change the span mode to "All monitors" (either via the `-span` command-line option or the TurboVNC Viewer Options dialog) in order to make the viewer window span multiple screens in windowed mode as well.  When the viewer window spans multiple screens, it will automatically configure the virtual screen layout in the TurboVNC session to match the client's screen boundaries.

Further reading on Un*x:
```
man -M /opt/TurboVNC/man vncserver
```
```
/opt/TurboVNC/bin/vncviewer -? | more
```
Further reading on Windows:
```
c:\program files\turbovnc\vncviewer.exe /?
```
```
c:\program files\turbovnc\vncviewer.bat -? | more
```
