### ISSUE TITLE
Error creating new session with TurboVNC Viewer

### ISSUE THREAD

**Issue by wanlinwang** [TurboVNC/turbovnc#313]
![图片](https://user-images.githubusercontent.com/32032219/154297788-2ae8f7ca-f506-407f-81cf-44fa61fdccef.png)

As the snapshot shows, I came across error creating new session. Please, how to create a new session with TurboVNC Viewer on Windows, how could I specify a securitytype which use Linux user to authenticate? Many thanks.

**Comment by dcommander** [comment]
The host machine must have v3.0 beta1 (or later) of the TurboVNC Server installed in order to use the TurboVNC Session Manager.  There is no need to authenticate using a Unix user account, because the TurboVNC Session Manager already authenticates using SSH (which is tied to your Unix user account) and a one-time password that is tunneled through the SSH connection.  However, if you need to use another form of authentication with the session manager, you can pass `-nosessmgrauto` on the TurboVNC Viewer command line, as described [here](https://rawcdn.githack.com/TurboVNC/turbovnc/3.0beta1/doc/index.html#hd006001).  That will allow you to use any security type with the TurboVNC Session Manager.

**Comment by wanlinwang** [comment]
> The host machine must have v3.0 beta1 (or later) of the TurboVNC Server installed in order to use the TurboVNC Session Manager.  There is no need to authenticate using a Unix user account, because the TurboVNC Session Manager already authenticates using SSH (which is tied to your Unix user account) and a one-time password that is tunneled through the SSH connection.  However, if you need to use another form of authentication with the session manager, you can pass `-nosessmgrauto` on the TurboVNC Viewer command line, as described [here](https://rawcdn.githack.com/TurboVNC/turbovnc/3.0beta1/doc/index.html#hd006001).  That will allow you to use any security type with the TurboVNC Session Manager.
> 
> 

Thank you for your prompt response. Is OTP necessary for creating new session?

**Comment by dcommander** [comment]
Yes, unless `-nosessmgrauto` is used.

**Comment by wanlinwang** [comment]
> Yes, unless `-nosessmgrauto` is used.
> 
> 

Awesome, thank you.
