### ISSUE TITLE
Allow settings passwords that are longer than 8 characters.

### ISSUE THREAD

**Issue by butterfly1924** [TurboVNC/turbovnc#329]
As security is essential for customers. Longer password might be needed.

**Comment by dcommander** [comment]
The VNC password protocol doesn’t allow for more than eight characters. However, TurboVNC also supports authentication using Unix user/password credentials or one-time passwords or time-based one-time passwords. The TurboVNC Session Manager uses SSH for both encryption and primary authentication (and a one-time password for secondary authentication within the SSH tunnel), so that mode of operation is as secure as any SSH session.
