### ISSUE TITLE
TurboVNC viewer: invalid privatekey error - cannot connect to server

### ISSUE THREAD

**Issue by mbutler808** [TurboVNC/turbovnc#331]
Aloha, 
I am trying to use TurboVNC to connect to the SlicerMorphCloud server, but I cannot get past an invalid private key error (screenshot attached). 

I am able to ssh to my server in the terminal, so my account/password is valid, but I cannot launch the app I need to use. 
I use Mac OS 10.15.17 (Catalina), I also tried it on Mojave.
I have a private key for GitHub. It is saved in ~/.ssh/id_ed25519 

I would be grateful for any suggestions. Thanks! M
[TurboVNCviewer_error.pdf](https://github.com/TurboVNC/turbovnc/files/8820690/TurboVNCviewer_error.pdf)

**Comment by dcommander** [comment]
Try the 3.0.x pre-release build. This should be fixed now. Refer also to https://github.com/TurboVNC/turbovnc/issues/323#issuecomment-1113640309 for a workaround for TurboVNC 3.0.

**Comment by dcommander** [comment]
Oh, also the TurboVNC Viewer doesn’t support ED25519 keys. That is slated for a future release. It will handle ECDSA and RSA-256/512.

**Comment by mbutler808** [comment]
Thank you @dcommander for the quick reply, but I still need help. 
(1) where can I find the prerelease build? I could only find the current and 2.2.90 and older on sourceforge.  Is there a binary mac OS? 
(2) I tried creating an rsa key, and converting id_rsa to id_rsa.pem as noted in the comment, but TurboVNC viewer 3.0 still doesnʻt work. 

Thank you!
Marguerite

**Comment by mbutler808** [comment]
@dcommander  Did I miss where I was supposed to specify the location of a private key somewhere?  I reinstalled it a couple of times, on two different Macs.

**Comment by dcommander** [comment]
On the pre-release page, there is a link for Mac packages. Follow that link and download the .dmg file. Open the .dmg and open the installer inside of it. Sorry for the confusion about specifying a key. The TurboVNC Viewer will automatically use ~/.ssh/id_rsa if it exists. So the easiest thing to do is make sure that your chosen private key is at that location. Otherwise you have to specify the key in ~/.ssh/config using the IdentityFile keyword (Google for documentation on the OpenSSH config file) or on the TurboVNC Viewer command line using the SSHKeyFile parameter.
