### ISSUE TITLE
 /usr/bin/xstartup.turbovnc: line: 207 on Arch linux x64 and arm64

### ISSUE THREAD

**Issue by gyurmogyuri** [TurboVNC/turbovnc#347]
xstartup.turbovnc: Creating new session bu
 s instance:
 xstartup.turbovnc: unix:path=/tmp/dbus-rf2Q5W7NF7,guid=a2de447a93e4c9396715cf27636
 cd9e3
 xstartup.turbovnc: Executing /etc/X11/xini
 t/xinitrc
 /usr/bin/xstartup.turbovnc: line: 207: /etc/X11/xinit/xinitrc: Permission denied
 /usr/bin/xstartup.turbovnc: line 207: exec: /etc/X11/xinit/xinitrc: not executable end
 re: Permission denied

**Comment by dcommander** [comment]
Arch falls into the [community support](https://turbovnc.org/Documentation/OSSupport) category, precisely because issues like this tend to pop up in that distribution (and other "bleeding-edge" rolling distros) and not in any other distro.  I have never seen a distro on which **/etc/X11/xinit/xinitrc** isn't executable, and in fact, making that script executable is a requirement for some distribution packaging specs, such as Debian's.

That being said, **xstartup.turbovnc** will only try to invoke `/etc/X11/xinit/xinitrc` if it fails to find another window manager.  It searches for GNOME by default, but for other window managers, you need to either pass `-wm` to `/opt/TurboVNC/bin/vncserver` or set `$wm` in **/etc/turbovncserver.conf** or **~/.vnc/turbovncserver.conf**.  The value you pass to `-wm` or set in `$wm` should correspond to a session desktop file under **/usr/share/xsessions**, without the **.desktop** extension.  Refer to https://turbovnc.org/Documentation/Compatibility30 for some common examples.
