### ISSUE TITLE
Alt key shifts focus away from VNC on Windows by popping up a menu.

### ISSUE THREAD

**Issue by Patrick-Poitras** [TurboVNC/turbovnc#349]
This is a copy-paste of the comments on https://github.com/TurboVNC/turbovnc/issues/348 when I believed this was part of another bug. I've attempted to provide enough information to prevent having to reference the other issue.

--------------------

Original report:

I'm now having a slightly different problem, where if I press the Alt key, and don't press anything else and release, it shifts the focus away from the window, and then if I press keys, there's a window that pops up.

![image](https://user-images.githubusercontent.com/42386710/204649871-25fc96aa-c8c3-4ae4-b23c-a04e62fc20c5.png)

It does this even if there's keyboard grabbing, which makes it a mess. The key sequence that reproduces this 100% of the time is roughly "Alt_Down Alt_Up Up_Arrow_Down"

--------------------------

A summary of what has been tried by @dcommander https://github.com/TurboVNC/turbovnc/issues/348#issuecomment-1330096238, which are summarized. :
- https://stackoverflow.com/a/56341205: Java doesn't allow the protected KeyboardFocusManager.getKeyEventPostProcessors() method to be accessed through Reflection.
- https://stackoverflow.com/a/3994002: Prevents the Alt key from working at all.
- Intercepting the left Alt key in the LowLevelHook C++ class (used by the keyboard grabber) : also prevents the Alt key from working at all.

**Comment by dcommander** [comment]
Should be fixed now, and I'll comment again when pre-release builds are available with the fix.  https://stackoverflow.com/a/3994002 actually was the right approach.  I just needed to modify the key event dispatcher so that it actually sends the LAlt key press or release to the server rather than ignoring it.  In my haste to look into the issue prior to the TurboVNC 3.0.2 release deadline last week, I missed that.

**Comment by dcommander** [comment]
Builds are up

**Comment by Patrick-Poitras** [comment]
It works! Thank you so much!
