### ISSUE TITLE
Turbo VNC 64 bit non-java client will not connect to VMWare Workstation 10 VNC Server

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [TurboVNC/turbovnc#36]
If a custom port is four digits and starts with 59, then when attempting to connect, the 59 is dropped from the port number.

This does not occur with the java based viewer.

Occurs in v2.0.1 64 bit running on Windows 7.

**Comment by dcommander** [comment]
It's because Port 59nn is equivalent to VNC display nn, so connecting to {server}::5901 (note double colon) is the same as connecting to {server}:1.  Both the Windows and Java viewers automatically replace ::59nn with :nn in the GUI, but the Java viewer still prints out the actual port number on the command line.

If I am misunderstanding something, then please provide more details as to how to reproduce the problem.

**Comment by jonl-percsolutions-com** [comment]
The problem is, the Java based viewer connects, but the non-java based viewer does not.  IE, I have a vm with VNC turned on port 5980, but TurboVNC non-java viewer is the only viewer that does not connect.  TightVNC, RealVNC, TurboVNC Java Viewer all connect

**Comment by dcommander** [comment]
That's odd.  How are you trying to connect?  Are you specifying the port on the command line or in the GUI?

**Comment by jonl-percsolutions-com** [comment]
I am specifying the port in the GUI.  Specifying like so : `hostname:5980`

**Comment by dcommander** [comment]
Yeah, and the viewer definitely does rewrite it to hostname:80, but I don't understand why it subsequently fails to connect.  I swear it works for me.

On the server:
```
/opt/TurboVNC/bin/vncserver :80
```

On the client:
* Start TurboVNC Viewer
* Enter "server:5980" in the "VNC server" text box
* Click "Connect"

It connects with no issues.  There is still some piece of information I'm missing here.

**Comment by jonl-percsolutions-com** [comment]
The only other piece of missing information that might be pertinent is that the OS is running in VMWare Workstation 10 and i am connecting to VMWare Workstations internal VNC Server. Just ran a little test and looks like changing the port, changed it to 1234, on the VMWare VNC server does not fix the issue, so it might be some compatibility issue with VMWare Workstations VNC Server and the non-java VNC Client.  The java VNC client works fine.

**Comment by dcommander** [comment]
I don't see why that would be the issue.  So you're running the VMWare VNC server on port 5980?

**Comment by dcommander** [comment]
I mean, our native Windows viewer was originally based on TightVNC, so I fail to comprehend how their viewer would work properly and ours wouldn't.

**Comment by dcommander** [comment]
When you say it doesn't connect, what error messages are displayed by the viewer?  Is there a VNC server log that might indicate what's wrong?

**Comment by jonl-percsolutions-com** [comment]
There appears to only be a log statement in vmware if the connection is established.

The error that appears in the ui is just the error "Failed to connect to server(servername::port)".

Additional information and testing:  I was actually evaluating TurboVNC vs TightVNC vs Mac Remote Screen Sharing,  so I am actually attempting to connect to the vmware vnc server from the local machine.  If I try from a remote machine it works fine.  If I try with hostname/localhost from the local machine it does not work.  If I try with loopback address, it works fine.  

So it appears ultimately that the problem is when the viewer is attempting to connect to a server on the same machine.

**Comment by dcommander** [comment]
So you're running all of this (including VMWare) on a Windows box?

**Comment by jonl-percsolutions-com** [comment]
Correct.  Windows 7 box.

**Comment by dcommander** [comment]
OK, so this is a much more general problem than you described.  It has nothing to do with VMWare.  The underlying cause is actually a feature, not a bug.  If your Windows box is configured with both IPv6 and IPv4 addresses, then localhost will point to the IPv6 loopback address (::1) instead of the IPv4 loopback address (127.0.0.1).  That behavior on the part of Windows is different from other platforms.  On OS X, localhost always points to 127.0.0.1.  On Linux, localhost points to 127.0.0.1 and localhost6 points to ::1.  The Windows TurboVNC Viewer is IPv6-capable, so when you specify "localhost" in that viewer, it will try to connect to ::1, and I strongly suspect that the VMWare server isn't listening on the IPv6 loopback address (I actually don't think an IPv6-capable Windows VNC server exists yet-- at least, I couldn't find one.)  So you should try to connect to 127.0.0.1 instead of localhost.

**Comment by jonl-percsolutions-com** [comment]
The only problem I see with call it "a feature", is that you get different behavior between your own two clients and the one which you say that you are derived from, which instead looks like broken behavior. Perhaps it might not be worth fixing as the behavior is platform dependent in some ways, but it would definitely be good to document if it is not documented somewhere.

Also, fwi, it appears that RealVNC server supports ipv6 on windows.

https://www.realvnc.com/products/vnc/documentation/4.1/release-notes/ipv6

**Comment by dcommander** [comment]
I understand.  It's just that this is a somewhat esoteric use case, and the differences in behavior are due to platform differences.  I don't know about the newer TightVNC 2.x viewer, but the 1.3.x viewer that we were originally based upon (12 years ago-- we've come a long way since then) doesn't support IPv6, which is why it works.  It's unclear to me why Java behaves differently by default (and I've spent an hour looking at the JVM source code.)  I do know that, if you pass `-Djava.net.preferIPv6Addresses=true` to the JVM, it behaves exactly as the native viewer behaves.  The native viewer is using `AF_UNSPEC` to obtain an IP address from a hostname, and on Windows, that always translates localhost into ::1.  Java is also using `AF_UNSPEC`, so I have no idea why it behaves differently, and I don't have time to dig into it further.

**Comment by dcommander** [comment]
I figured out what the JVM was doing.  It specifically handles the case of localhost and tries to resolve localhost using an IPv4 address unless `-Djava.net.preferIPv6Addresses=true` is specified, so I just pushed a commit that makes the Windows viewer behave similarly (except that it uses the existing `/ipv6` switch as a way of informing it that the IPv6 loopback address is preferred.)

**Comment by jonl-percsolutions-com** [comment]
Awesome that sounds perfect.
