### ISSUE TITLE
Minimize option in F8 Menu

### ISSUE THREAD

**Issue by ercanal** [TurboVNC/turbovnc#366]
Is it possible to add minimize functionality to TurboVnc Viewer  Hotkey (F8) Menu? 
It is not possible to switch from VNC session to my real machine without disabling fullscreen mode.

**Comment by dcommander** [comment]
I assume you are using a Windows client?  You didn't specify.

The behavior you describe is probably due to keyboard grabbing being enabled by default in full-screen mode.  When keyboard grabbing is enabled, Alt-Tab and other special keystrokes are passed to the VNC session.  You can temporarily disable keyboard grabbing with Ctrl-Alt-Shift-G, then Alt-Tab will switch away from the TurboVNC Viewer window.  Keyboard grabbing will be re-enabled when you switch back to the TurboVNC Viewer window.  (NOTE: This is similar to how VMWare works.)  If you don't ever want Alt-Tab to be passed to the VNC session, then you can set the grabbing mode to "Manual".

On Windows, the minimize hotkey (Windows-<down arrow>) is also captured by the keyboard grabbing feature, so you can press Ctrl-Alt-Shift-G, then Windows-<down arrow> to minimize the TurboVNC Viewer window when it is in full-screen mode with keyboard grabbing enabled.  It would be poor UI design to duplicate a feature of the window manager, and it doesn't make sense to replace two keystrokes with one F8 menu, since that wouldn't really reduce the number of actions required to accomplish the task.

Probably the ideal solution would be a toolbar with close and minimize gadgets that fades in when you move the mouse to the top of the full-screen window.  (RealVNC and TightVNC both have that.)  However, that would be a significant effort, so it's not something I could implement unless an organization specifically paid for the labor.
