### ISSUE TITLE
vglrun and tuborvnc?

### ISSUE THREAD

**Issue by qibin2020** [TurboVNC/turbovnc#371]
Hi experts,
  I have a very naive question -- After I have setup the turbovnc server and xfce4 desktop environment I can directly run e.g.  `glxgear` in the xfce terminal (with very good FPS), does that mean turbovnc itself now handles all the virtual-GL function? I have checked some documentations and they all described the usage like `vglrun glxgear` is necessary. Do I understand them correctly or tuborvnc could handle all of this with single software now.
    Many thanks!

**Comment by dcommander** [comment]
TurboVNC and VirtualGL are independent.  VirtualGL basically just intercepts the OpenGL function calls from an OpenGL application and directs them away from TurboVNC so that the function calls can be GPU-accelerated.  (This is a vastly oversimplified statement.  Refer to the VirtualGL User's Guide for diagrams and more details.)  `vglrun` just sets `LD_PRELOAD` to preload the VirtualGL interposer libraries ahead of libGL so that those libraries can intercept the necessary function calls.  If you use `vglrun` with a single application, then VirtualGL is only active for the life of that application.  If you want to activate VGL for the entire TurboVNC session, then you have to run the window manager using `vglrun` by passing `-vgl` to `/opt/TurboVNC/bin/vncserver` or setting the `$useVGL` variable in the TurboVNC Server config file.
