### ISSUE TITLE
Java Viewer: Keyboard shortcuts mapped differently from native version

### ISSUE THREAD

**Issue by capi** [TurboVNC/turbovnc#384]
OS: Windows 10
Keyboard Layout: German (Austria)
Device: Dell Latitude 7400

I'm primarily still using the native viewer of 2.2.7 and everything works fine. I tried updating to the Java Viewer of 3.0.3 and I noticed that a lot of keyboard shortcuts no longer are correctly sent in the Java version:
* Ctrl-Alt-T is sent as Ctrl-Alt-Shift-T for instance.
* Ctrl+Plus works, but Cntrl-Minus sends something different

My current assumption is that these are related to the Ctrl-Alt == AltGr quirkyness of Windows for non-US keyboards, but it works for the old native viewer, but not for the new Java-based viewer.

How can I help to debug this issue?

**Comment by dcommander** [comment]
This is probably the same issue as #194. It was resolved in TurboVNC 3.1 by implementing the QEMU Extended Key Event extension to the RFB protocol, which allows raw keyboard scan codes to be sent to the VNC server rather than X11 key symbols. Effectively this moves key mapping from the client side to the server side, so the keyboard layout specified in the TurboVNC session will affect key mapping but the keyboard layout specified on the client will not.

Upgrade both the server and client to 3.1 beta1 to take advantage of the new feature.
