### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jmakov** [TurboVNC/turbovnc#401]
Not really sure where to start. Any help very welcome.
```shell
-- Performing Test TURBOJPEG_WORKS
-- Performing Test TURBOJPEG_WORKS - Failed
CMake Error at cmakescripts/FindTurboJPEG.cmake:87 (message):
  Could not link with TurboJPEG library /usr/lib/libturbojpeg.so.  If it is
  installed in a different place, then set TJPEG_LIBRARY accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:162 (include)
```

**Comment by dcommander** [comment]
Hmmm...  OK.  I have zero experience with Manjaro.  The dependencies that the build is tripping on are:

1. The PAM headers and link library, which are presumably provided by a system package that isn't installed (I have no idea which package)
2. The TurboJPEG headers and link library, which may or may not be provided by a system package. If Manjaro provides the TurboJPEG headers and link library, then they would be provided by a package with either "turbojpeg" or "libjpeg-turbo" in the name, but I don't know enough about Manjaro to say for sure.  You may have to build and install libjpeg-turbo from source in order to get the TurboJPEG headers and link library.

Note that, with respect to TurboVNC, Manjaro is a "Community Support" operating system: https://turbovnc.org/Documentation/OSSupport.  That means that I am willing to fix any incompatibilities that may exist between TurboVNC and that operating system, but the community is expected to diagnose those issues.  (There are too many Linux distributions for me to reasonably test all of them.  I would have no time left to develop TurboVNC if I did that. 
I have to focus on the most popular ones.)

Unfortunately that is all the help I can provide for the moment, but if you are able to solve the problem, please comment regarding your solution so that others may learn from it.
