### ISSUE TITLE
JRELoadError with arm64 Mac - version 3.1.1

### ISSUE THREAD

**Issue by silas101** [TurboVNC/turbovnc#404]
I'm getting a 'JRELoadError' when trying to launch TurboVNC viewer (arm64), version 3.1.1 on my M1 Max Mac. 
This Mac has Java 8 update 401 installed. Using the version 3.1 (arm64) works without any problem. Using the version 3.1.1 x86_64 works fine too.

As another data point, I get the same JRELoadError when using the v3.1.1 arm64 version on a M3 Macbook. Using v3.1 (arm64) works no problem. This Macbook does not have Java installed. 
![Screenshot 2024-02-16 at 3 02 28 PM](https://github.com/TurboVNC/turbovnc/assets/4960048/e96753ff-0720-4098-a455-f7b938a606f5)

**Comment by dcommander** [comment]
The TurboVNC Viewer includes its own JRE, so it doesn't matter whether the system has Java installed.  I think the issue was that, because of 53b5417795345f564c5bf23c10f7886627f646bd, some of the objects for the arm64 TurboVNC Helper library and JavaAppLauncher were accidentally being built as x86-64 objects.  (I am cross-compiling the arm64 binaries on an Intel Mac and neglected to explicitly set the Objective C compiler flags.)  Fortunately, the issue is confined to our official build scripts rather than the TurboVNC code base itself.

Please try the build [here](https://s3.amazonaws.com/turbovnc-pr/main/macos/index.html) and let me know if the issue is resolved.  If so, I will rebuild the official 3.1.1 package and re-upload it.

**Comment by silas101** [comment]
The 3.1.1 rebuild works, thank you! 

I appreciate all the work you've put into the TurboVNC project. The users I support at my institution are very dependent on this for their workflow.

**Comment by dcommander** [comment]
A new official 3.1.1 package has been uploaded to https://github.com/TurboVNC/turbovnc/releases/tag/3.1.1.
