### ISSUE TITLE
Session Manager Error

### ISSUE THREAD

**Issue by ubless607** [TurboVNC/turbovnc#409]
Could not execute
 /opt/TurboVNC/bin/vncpasswd -o -display :3 
on host xxx:
The X display ":3" does not support VNC one-time passwords

I have reset the vncpasswd but it didn't work.

**Comment by dcommander** [comment]
Are you trying to connect to a TurboVNC session? The session manager can only be used with the TurboVNC server, not TigerVNC or other VNC servers. But you can still connect to those other VNC servers "the old-fashioned way", by specifying the display number. In other words, enter "{host}:3" rather than just "{host}".

**Comment by ubless607** [comment]
Yes, it is the TurboVNC session.
I have solved the problem, I was trying to connect to the VNC server generated by other user.

**Comment by dcommander** [comment]
Was that session showing up in your session list? That shouldn't have happened.
