### ISSUE TITLE
Guidance needed: Trying to get TurboVNC to only serve a single monitor

### ISSUE THREAD

**Issue by ArcAIN6** [TurboVNC/turbovnc#411]
Just as the title says, i have 3 monitors, and i want to be able to remote in to see what's happening on only the 3rd monitor. 
I see a drop down  for automatic , all, and primary only, so i'm assuming it should be possible to select the monitor i would like to use, without having to use my primary monitor. 

Thank you in advanced for any assistance with this, hopefully it's possible. 

EDIT:  I should have denoted this is in a windows invironment

**Comment by dcommander** [comment]
The screen spanning option only applies to the client. If you are using a Windows server, then you are not using TurboVNC as a VNC server. The ability to share a specific server-side screen would be a feature in the VNC server, which is out of our control.

**Comment by dcommander** [comment]
Listen mode simply allows a VNC server to make a "reverse connection" to the TurboVNC Viewer rather than the viewer making a connection to the VNC server. It doesn't change the fundamental capabilities of either the server or viewer. If you are using a Windows server, then you are using someone else's VNC server, because the TurboVNC Server is Un*x-only. The ability to share one specific screen of your Windows machine would be a function of the VNC server, and since you aren't using our VNC server, that is out of the scope of our support. There is nothing that the TurboVNC Viewer can do to enable the functionality you want.
