### ISSUE TITLE
set VNC_TUNNEL_CMD/turbovnc.tunnel through ~/.vnc/default.turbovnc

### ISSUE THREAD

**Issue by yghorbal** [TurboVNC/turbovnc#420]
Hi,

 I was wondering if there is any way to set custom `VNC_TUNNEL_CMD/turbovnc.tunnel` through `~/.vnc/default.turbovnc` file.
 I've gone over the code and the answer is most likely **no**, but my Java is rusty and I've may missed some obvious way other than Env Vars or Java Properties.
 For non tech-savvy users, it would be more easy if we keep the rollout process easy (at least for macOS) : install the dmg and put this file there and you're good to go. For now, we have to do some sheningans to keep the "click button" behaviour while setting a custom`VNC_TUNNEL_CMD` that fits our need.

 By the way, and regarding the `~/.vnc/default.turbovnc`, it would be really nice if there is a reference to its existence and its behaviour (regarding precedence with cli arguments for exemple). In fact, there is not a single reference to this file in the whole documentation.

 Thank you!

**Comment by dcommander** [comment]
> I was wondering if there is any way to set custom `VNC_TUNNEL_CMD/turbovnc.tunnel` through `~/.vnc/default.turbovnc` file. I've gone over the code and the answer is most likely **no**, but my Java is rusty and I've may missed some obvious way other than Env Vars or Java Properties. For non tech-savvy users, it would be more easy if we keep the rollout process easy (at least for macOS) : install the dmg and put this file there and you're good to go. For now, we have to do some sheningans to keep the "click button" behaviour while setting a custom`VNC_TUNNEL_CMD` that fits our need.

Not currently, but I have already identified the probable need to turn those settings into legitimate viewer parameters.  Do you need to change them in order to invoke a different SSH client (other than `/usr/bin/env ssh` on Un*x or `ssh.exe` on Windows), or do you need to change the SSH arguments as well?  The reason I ask is that, if you simply need to pass additional arguments to SSH, there may already be a way to accomplish that using an OpenSSH config file.

> By the way, and regarding the `~/.vnc/default.turbovnc`, it would be really nice if there is a reference to its existence and its behaviour (regarding precedence with cli arguments for exemple). In fact, there is not a single reference to this file in the whole documentation.

**default.turbovnc** is referenced in the TurboVNC Viewer documentation (`/opt/TurboVNC/bin/vncviewer -?`).  In fact, if you change one of the defaults in **default.turbovnc**, the parameter documentation in `/opt/TurboVNC/bin/vncviewer -?` will change to reflect the new default.

The User's Guide isn't a comprehensive reference.  It refers you to `/opt/TurboVNC/bin/vncviewer -?` and the TurboVNC Server man pages for the low-level details.  https://turbovnc.org/Documentation/Documentation does as well.

**Comment by yghorbal** [comment]
> > I was wondering if there is any way to set custom `VNC_TUNNEL_CMD/turbovnc.tunnel` through `~/.vnc/default.turbovnc` file. I've gone over the code and the answer is most likely **no**, but my Java is rusty and I've may missed some obvious way other than Env Vars or Java Properties. For non tech-savvy users, it would be more easy if we keep the rollout process easy (at least for macOS) : install the dmg and put this file there and you're good to go. For now, we have to do some sheningans to keep the "click button" behaviour while setting a custom`VNC_TUNNEL_CMD` that fits our need.
> 
> Not currently, but I have already identified the probable need to turn those settings into legitimate viewer parameters. Do you need to change them in order to invoke a different SSH client (other than `/usr/bin/env ssh` on Un*x or `ssh.exe` on Windows), or do you need to change the SSH arguments as well? The reason I ask is that, if you simply need to pass additional arguments to SSH, there may already be a way to accomplish that using an OpenSSH config file.

For instance, I want to _cancel_ an argument. The default ssh command enforces `-a` and in my specific use case it happens that I need ssh agent forwarding (for many good reasons). Since ssh cli arguments takes precedence over `.ssh/config`, I'm in the situation where I need to override `VNC_TUNNEL_CMD/turbovnc.tunnel`

> > By the way, and regarding the `~/.vnc/default.turbovnc`, it would be really nice if there is a reference to its existence and its behaviour (regarding precedence with cli arguments for exemple). In fact, there is not a single reference to this file in the whole documentation.
> 
> **default.turbovnc** is referenced in the TurboVNC Viewer documentation (`/opt/TurboVNC/bin/vncviewer -?`). In fact, if you change one of the defaults in **default.turbovnc**, the parameter documentation in `/opt/TurboVNC/bin/vncviewer -?` will change to reflect the new default.
> 
> The User's Guide isn't a comprehensive reference. It refers you to `/opt/TurboVNC/bin/vncviewer -?` and the TurboVNC Server man pages for the low-level details. https://turbovnc.org/Documentation/Documentation does as well.

I did'nt have any Linux Viewer installation at hand, so no `/opt/TurboVNC/bin/vncviewer -?` and the one that comes with the macOS installation bundle really don't reference that file at all.
```
% grep -cri default.turbovnc /Library/Documentation/TurboVNC
/Library/Documentation/TurboVNC/newconn.png:0
/Library/Documentation/TurboVNC/sessmgr.png:0
/Library/Documentation/TurboVNC/index.html:0
/Library/Documentation/TurboVNC/x11transport.png:0
/Library/Documentation/TurboVNC/turbovnc.css:0
/Library/Documentation/TurboVNC/somerights20.png:0
/Library/Documentation/TurboVNC/unixauth.png:0
/Library/Documentation/TurboVNC/vncauth-insecure.png:0
/Library/Documentation/TurboVNC/vncauth.png:0
/Library/Documentation/TurboVNC/LICENSE.txt:0
/Library/Documentation/TurboVNC/newconn-sessmgr.png:0
/Library/Documentation/TurboVNC/vncauth-redundant.png:0
/Library/Documentation/TurboVNC/vgltransportservernetwork.png:0
```

**Comment by dcommander** [comment]
> For instance, I want to _cancel_ an argument. The default ssh command enforces `-a` and in my specific use case it happens that I need ssh agent forwarding (for many good reasons). Since ssh cli arguments takes precedence over `.ssh/config`, I'm in the situation where I need to override `VNC_TUNNEL_CMD/turbovnc.tunnel`

Fair enough, but can you tell me more about your use case?  Since the tunnel established by `VNC_TUNNEL_CMD`/`turbovnc.tunnel` is only used for tunneling the RFB connection, and since the `Tunnel` parameter (as opposed to the `Via` parameter) only interacts with a single host, why do you need SSH agent forwarding?  I'm not trying to be argumentative.  I'm just trying to understand the full scope of the issue so I can come up with a better long-term solution. (https://github.com/TurboVNC/turbovnc/commit/396e76cfa419d227f9364c0e481328f551dc8ab2, which added the `-a` argument, may have been ill-advised.)  The `VNC_VIA_CMD`/`VNC_TUNNEL_CMD` interface dates back to TightVNC 1.3.x, and I intend to completely revisit it in TurboVNC 3.2.  For instance, it may make sense to separate the SSH command itself from the `Via`/`Tunnel` templates and to attach the `-a` and `-x` arguments to the SSH command, thus making it easy to remove those arguments without fiddling with the templates.

> I did'nt have any Linux Viewer installation at hand, so no `/opt/TurboVNC/bin/vncviewer -?` and the one that comes with the macOS installation bundle really don't reference that file at all.

The macOS package also contains **/opt/TurboVNC/bin/vncviewer**.  I freely admit that that is not an ideal place for documentation, since not all Mac users are command line users.  I am just saying that the documentation is there, albeit not in the most obvious place.  This project works on a shoestring budget, is funded solely through patronage and funded development, and has to compete with corporate-backed solutions that have entire teams for documentation, testing, development, marketing, project/product management, etc.  Thus, there are some imperfections that are the result of my lack of resources.  I have thought through the possibility of including full command-line documentation in the TurboVNC User's Guide, but I'm not sure how to do that in a way that doesn't require me to maintain the same information in two places.  The cop-out I chose is to include a section in the User's Guide that refers users to the command-line documentation.  Before the introduction of **default.turbovnc**, the command line was the only place you could use the TurboVNC Viewer parameters anyhow, so the lack of parameter documentation in any other place was a non-issue.  Because of **default.turbovnc**, you can now use the TurboVNC Viewer parameters outside of the command line, but you still have to go to the command line to get the parameter documentation, and that's where you'll find the documentation for **default.turbovnc** as well.  I am open to suggestions that don't create a maintenance burden for me.

**Comment by yghorbal** [comment]
> > For instance, I want to _cancel_ an argument. The default ssh command enforces `-a` and in my specific use case it happens that I need ssh agent forwarding (for many good reasons). Since ssh cli arguments takes precedence over `.ssh/config`, I'm in the situation where I need to override `VNC_TUNNEL_CMD/turbovnc.tunnel`
> 
> Fair enough, but can you tell me more about your use case? Since the tunnel established by `VNC_TUNNEL_CMD`/`turbovnc.tunnel` is only used for tunneling the RFB connection, and since the `Tunnel` parameter (as opposed to the `Via` parameter) only interacts with a single host, why do you need SSH agent forwarding? I'm not trying to be argumentative. I'm just trying to understand the full scope of the issue so I can come up with a better long-term solution. ([396e76c](https://github.com/TurboVNC/turbovnc/commit/396e76cfa419d227f9364c0e481328f551dc8ab2), which added the `-a` argument, may have been ill-advised.) The `VNC_VIA_CMD`/`VNC_TUNNEL_CMD` interface dates back to TightVNC 1.3.x, and I intend to completely revisit it in TurboVNC 3.2. For instance, it may make sense to separate the SSH command itself from the `Via`/`Tunnel` templates and to attach the `-a` and `-x` arguments to the SSH command, thus making it easy to remove those arguments without fiddling with the templates.

The use case is that the workstation (running the server) is not directly accessible from the client. The client have to go through a proprietary ssh bastion host. The said bastion will operate in a proxy mode (read two ssh sessions : the first with the client and the second with the workstation) and in order to have ssh key auth on the second ssh connection, the user will have to forward the agent to the bastion. It's not the same classic JumpHost ssh.

IMHO, the current `-a` is a sane default to keep (as the `-x`by the wat). My use case is really very specific and workaroundable with `VNC_TUNNEL_CMD` env var. I confess that it would have been more convenient if it was tunable through the config file, but dealing  with `VNC_TUNNEL_CMD` env vas is not a show stopper.

> > I did'nt have any Linux Viewer installation at hand, so no `/opt/TurboVNC/bin/vncviewer -?` and the one that comes with the macOS installation bundle really don't reference that file at all.
> 
> The macOS package also contains **/opt/TurboVNC/bin/vncviewer**. I freely admit that that is not an ideal place for documentation, since not all Mac users are command line users. I am just saying that the documentation is there, albeit not in the most obvious place. This project works on a shoestring budget, is funded solely through patronage and funded development, and has to compete with corporate-backed solutions that have entire teams for documentation, testing, development, marketing, project/product management, etc. Thus, there are some imperfections that are the result of my lack of resources. I have thought through the possibility of including full command-line documentation in the TurboVNC User's Guide, but I'm not sure how to do that in a way that doesn't require me to maintain the same information in two places. The cop-out I chose is to include a section in the User's Guide that refers users to the command-line documentation. Before the introduction of **default.turbovnc**, the command line was the only place you could use the TurboVNC Viewer parameters anyhow, so the lack of parameter documentation in any other place was a non-issue. Because of **default.turbovnc**, you can now use the TurboVNC Viewer parameters outside of the command line, but you still have to go to the command line to get the parameter documentation, and that's where you'll find the documentation for **default.turbovnc** as well. I am open to suggestions that don't create a maintenance burden for me.

My intention was not to point an imperfection but rather to give feedback about something that I saw missing in the documentation. Yours is already high standrd, understandable, and easy to go over and have a very good balance between high level overview and gory details (same goes for VirtualGL documentation as well)
Maybe add a reminder in the "Advanced Settings" section, that the complete detailed configuration options can be found in the man pages and the "-help" section of the cli.

**Comment by dcommander** [comment]
> The use case is that the workstation (running the server) is not directly accessible from the client. The client have to go through a proprietary ssh bastion host. The said bastion will operate in a proxy mode (read two ssh sessions : the first with the client and the second with the workstation) and in order to have ssh key auth on the second ssh connection, the user will have to forward the agent to the bastion. It's not the same classic JumpHost ssh.

OK, I think for now the most expedient fix would be to introduce an SSH command parameter that defaults to `/usr/bin/env ssh -ax` on Un*x and `ssh.exe -ax` on Windows, then automatically populate the default `VNC_TUNNEL_CMD`/`VNC_VIA_CMD` templates from the value of that parameter.

Looking at the Advanced Configuration section of the User's Guide, I see a few ways in which it might be clarified, so I'll look into that.

**Comment by dcommander** [comment]
https://github.com/TurboVNC/turbovnc/commit/a7d085b6b099fd902adc5b5539a33f9702d6ecdc adds a new TurboVNC Viewer parameter for specifying the external SSH client command, and the `-a` and `-x` arguments are now part of the default value of the new parameter.  Thus, you should be able to re-enable SSH agent forwarding by setting `ExtSSHCommand` to, for instance, `/usr/bin/ssh -x` in **~/.vnc/default.turbovnc**.

**Comment by dcommander** [comment]
b73b97427b455244209fc70a54c63692d390809d addresses your concerns about the documentation.

**Comment by dcommander** [comment]
Also, efab8f80683b0f61705ab15a2e84084c94a204de tweaks the `ExtSSHCommand` feature slightly.  `%S` in the `Via`/`Tunnel` SSH command-line templates is now replaced with the value of the `ExtSSHCommand` parameter.  That allows you to either specify the external SSH client command without changing the templates or change the templates without specifying the external SSH client command.
