### ISSUE TITLE
vncserver -sessionlist?

### ISSUE THREAD

**Issue by yghorbal** [TurboVNC/turbovnc#421]
Hello,

 Just wondering if `vncserver -sessionlist` is something someone can rely on, or it's somehow a hidden and not publicly available option. I'm seeing the option in the code but it's not in the man page and not listed in `vncserver -h`.

  Also, when run (`vncserver -sessionlist`), the second column value seems to be always `3` (at least in the code it's enforced to print `3` https://github.com/TurboVNC/turbovnc/blame/27f95cf89daf64b003c4b545155fc1ac314f2b9a/unix/vncserver.in#L943)
  Is this a bug or this number is supposed to have a special meaning?

 I'm trying to use `-sessionlist` for a wrapper script and its output is nicer to parse than `-list`!

 Thank you for your help!

**Comment by dcommander** [comment]
`-sessionlist` is used invisibly by the TurboVNC Session Manager (along with `-sessionstart`), which is why it isn't documented.  However, it is a stable interface in the sense that, if it changed, it would introduce a backward incompatibility with prior installations of the TurboVNC Session Manager.  Thus, it is maintained in a backward-compatible way.  I will clarify that by describing the format and its backward compatibility policy in a code comment in the vncserver script.

**Comment by dcommander** [comment]
https://github.com/TurboVNC/turbovnc/commit/c378a84c70d32c5d86c169015f4888d40a002e66 documents `-sessionlist` and `-sessionstart` in the vncserver code comments.
