### ISSUE TITLE
3.1.2 - Deadlock in PeekExactTimeout

### ISSUE THREAD

**Issue by kageurufu** [TurboVNC/turbovnc#427]
Hello! We are deploying TurboVNC on ubuntu instances on OpenStack, with Guacamole providing an easy to use remote desktop (obviously without vgl extensions). Our deployment ansible role is at https://gitlab.com/exosphere/exosphere/-/blob/master/ansible/roles/vnc-server/tasks/Debian.yml?ref_type=heads

Sometimes after long running connections, Xvnc will hang. Existing connections just freeze until a timeout then disconnect. Reconnections just hang until a timeout, and we have to hard kill the process before restarting the systemd service to get things back online.

I have a core dump of the hung process I can provide, and have an instance sitting hung for further inspection.

```
$ /opt/TurboVNC/bin/vncserver -kill :1
Killing Xvnc process ID 38498
Xvnc seems to be deadlocked.  Kill the process manually and then re-run
    /opt/TurboVNC/bin/vncserver -kill :1
to clean up the socket files.
```

Attaching gdb shows Xvnc is stuck in PeekExactTimeout, backtrace as follows
```
#0  0x00007c5c86d27670 in __libc_recv (fd=31, buf=0x7ffec1217e80, len=4, flags=2) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  0x000000000048dabe in PeekExactTimeout ()
#2  0x000000000049985b in webSocketsCheck ()
#3  0x0000000000484274 in rfbNewClient ()
#4  0x000000000048e082 in rfbSockNotify ()
#5  0x000000000053ace1 in ospoll_wait ()
#6  0x0000000000530e50 in WaitForSomething ()
#7  0x0000000000444f83 in Dispatch ()
#8  0x00000000004204a5 in dix_main ()
#9  0x00007c5c86c29d90 in __libc_start_call_main (main=main@entry=0x420070 <main>, argc=argc@entry=26, argv=argv@entry=0x7ffec133aed8) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007c5c86c29e40 in __libc_start_main_impl (main=0x420070 <main>, argc=26, argv=0x7ffec133aed8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffec133aec8) at ../csu/libc-start.c:392
#11 0x000000000042009e in _start ()
```

If the debug symbols are available anywhere for the debian packages, I can get more info from gdb (I'm not too familiar with debugging without symbols). Or if the core dump would be useful, let me know where to send it.

Thanks

**Comment by dcommander** [comment]
The stack trace would suggest that it's hanging when a new client tries to connect, and it's hanging when the server tries to detect a WebSockets client. Is Guac using RFB/WebSockets or making a regular RFB connection? And can you confirm that the hang occurs when a new connection is attempted?

**Comment by dcommander** [comment]
Yes, I need to be able to reproduce it so I can investigate a workaround.  Our implementation of `PeekExactTimeout()` is borrowed from LibVNCServer, so if there is an issue, both implementations may need to be fixed.

**Comment by dcommander** [comment]
If would also be helpful if you could build the server from source with `-DCMAKE_BUILD_TYPE=RelWithDebInfo`, reproduce the issue, then post the stack trace (which should now include line numbers.)  That will help me figure out which call to `PeekExactTimeout()` is hanging.

**Comment by kageurufu** [comment]
I have not yet reproduced the issue with the latest version of guacamole, I am still trying however.

I've built 3.1.2 with `RelWithDebInfo`, and installed it on both instances (one with the old guacamole release, one on the latest). When I manage to capture another deadlock I'll report back

**Comment by kageurufu** [comment]
Ok, I finally deadlocked again (only using the older guacamole client, but that's still progress).

```
#0  0x000070855f527670 in __libc_recv (fd=fd@entry=11, buf=buf@entry=0x7fff8784f99c, len=len@entry=4, flags=flags@entry=2) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  0x0000599bd2427e7c in recv (__flags=2, __n=4, __buf=0x7fff8784f99c, __fd=11) at /usr/include/x86_64-linux-gnu/bits/socket2.h:38
#2  PeekExactTimeout (cl=cl@entry=0x599bd53f0e40, buf=buf@entry=0x7fff8784f99c "GGG", len=len@entry=4, timeout=timeout@entry=100) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/hw/vnc/sockets.c:484
#3  0x0000599bd243480b in webSocketsCheck (cl=cl@entry=0x599bd53f0e40) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/hw/vnc/websockets.c:109
#4  0x0000599bd241e35b in rfbNewClient (sock=sock@entry=11) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/hw/vnc/rfbserver.c:464
#5  0x0000599bd241ebf9 in rfbNewClientConnection (sock=sock@entry=11) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/hw/vnc/rfbserver.c:334
#6  0x0000599bd242855d in rfbSockNotify (fd=7, ready=<optimized out>, data=0x0) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/hw/vnc/sockets.c:239
#7  0x0000599bd24dca01 in ospoll_wait (ospoll=0x599bd47d1310, timeout=<optimized out>) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/os/ospoll.c:657
#8  0x0000599bd24d30f8 in WaitForSomething (are_ready=0) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/os/WaitFor.c:208
#9  0x0000599bd23e2cf9 in Dispatch () at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/dix/dispatch.c:421
#10 0x0000599bd23bdc79 in dix_main (argc=26, argv=0x7fff87972a78, envp=<optimized out>) at /home/exouser/turbovnc/unix/Xvnc/programs/Xserver/dix/main.c:276
#11 0x000070855f429d90 in __libc_start_call_main (main=main@entry=0x599bd23bd810 <main>, argc=argc@entry=26, argv=argv@entry=0x7fff87972a78) at ../sysdeps/nptl/libc_start_call_main.h:58
#12 0x000070855f429e40 in __libc_start_main_impl (main=0x599bd23bd810 <main>, argc=26, argv=0x7fff87972a78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff87972a68) at ../csu/libc-start.c:392
#13 0x0000599bd23bd845 in _start ()
```

**Comment by dcommander** [comment]
That's excellent information.  Thanks.  I may have gotten the logic slightly wrong when I ported the function from LibVNCServer.  I will investigate further.

**Comment by dcommander** [comment]
Our implementation of `PeekExactTimeout()` is logically equivalent to LibVNCServer's implementation of `rfbPeekExactTimeout()`, at least inasmuch as it applies to this specific behavior.  Since `recv()` returns 3, which is less than `len` (4), and sets `errno` to `EGAIN`, the function falls through to the `select()` call.  `select()` is called with a timeout of 100 ms in this case, and when it returns 1 (indicating that the socket has data ready) and also sets `errno` to `EAGAIN`, the outer loop continues.  The issue is that `recv()` is not supposed to return anything except -1 if it sets `errno` to `EAGAIN`.  The `*PeekExactTimeout()` code suggests that it expects `recv()` to sometimes return a positive value with `errno` set to `EAGAIN`, but in order to figure out whether the function is handling that situation properly, I need to be able to reproduce it.  The first thing that an RFB client is supposed to send is the RFB version header, which is more than 4 bytes, so `recv()` in `PeekExactTimeout()` should never return 3.  I've tried to simulate that in various ways, such as making the TurboVNC Viewer send the initial 3 bytes of the RFB header, flush the stream, then fail to flush the stream after the remaining header bytes are sent.  That doesn't trigger the issue, however.  It instead causes the server to block later on, during protocol negotiation.

I'm unfortunately clueless at this point.  I need more data or an example of a client that can reliably reproduce the issue.  Absent that, the only thing I can think to do would be to introduce an Xvnc option to disable WebSockets, but I would prefer to solve the problem.

**Comment by dcommander** [comment]
Assuming I understand the symptoms correctly and `PeekExactTimeout()` is going into an infinite loop (as opposed to an actual deadlock), then I was able to reproduce the issue by 
[modifying the TurboVNC Viewer](https://github.com/user-attachments/files/17602816/viewer-premature-send.patch) so that it preemptively sends the first few bytes of the RFB version header before it receives the version header from the server.  (That is incorrect behavior, but it accidentally works with most RFB servers because most RFB servers don't peek the socket to look for a WebSockets header.  A normal RFB client would wait until it receives the version header from the server, so `PeekExactTimeout()` in `webSocketsCheck()` would immediately return -1 since there is no data to receive from the client yet.)  However, you don't even need an RFB client to reproduce it.  You can do `echo XX | netcat {TurboVNC_host} {TurboVNC_port}`.  Thus, this is actually a DoS vulnerability.

This is a fundamental flaw in the design of `PeekExactTimeout()`, so the issue probably affects LibVNCServer as well.  If `recv(..., MSG_PEEK)` returns less than `len` bytes and `errno` is `EAGAIN`, then the function will fall through to the `select()` call.  The `select()` call will always immediately return 1 and leave `errno` unchanged, because `recv()` has not removed any bytes from the queue.  Thus, the function needs to enforce its own timeout in that case.

662481cd478578e112a53beed2cda86f2acc2994 should fix it.  Please test.

**Comment by kageurufu** [comment]
That seems to exactly match the behavior I was naively debugging.

I built and deployed your fixed commit on two instances, `echo|nc` no longer locks the process (now returning the expected `RFB 003.008`).

I'm going to leave guacamole connected again, and will report back with those results.

**Comment by kageurufu** [comment]
I haven't seen any locked instances so far, I think the issue is solved.

Is there any chance of a new release with the fix included?

**Comment by dcommander** [comment]
Yes, it should drop by the end of the week.
