### ISSUE TITLE
No cursor in viewer (TurboVNC viewer, TigerVNC x0vncserver)

### ISSUE THREAD

**Issue by pjlobo** [TurboVNC/turbovnc#68]
Executive summary: There is no cursor in viewer using TurboVNC viewer 2.1 running on a Debian 8 machine to connect to an Ubuntu 12.04 (yes, I know it's old, but can't upgrade now) server running TigerVNC x0vncserver 1.7.0.

I've come to this combination because TurboVNC does not have a x0vncserver (which I need) and TigerVNC viewer does not support scaling (which is nice to have). Using TigerVNC at both sides works fine, but there's no scaling. Both TurboVNC and TigerVNC viewers with x11vnc server work fine, but this is waaay slower.

I've tried all viewer and server options (i.e. local/server cursor, scaling on/off, etc.) to no avail. Can't say whether the problem is at the viewer or server side, so I'm opening an issue on both in the hope that this otherwise fantastic combination becomes useable.

Best regards.

**Comment by dcommander** [comment]
Investigating ...  Sorry for the very long delay.

**Comment by dcommander** [comment]
Reproduced.

**Comment by dcommander** [comment]
Hmmm...  I'm seeing exactly the same behavior with both the TigerVNC native and Java viewers on Windows, and on Mac, the TigerVNC native viewer doesn't work at all (just displays a black screen.)  The issue seems to be that x0vncserver isn't actually sending the cursor shape updates properly (or perhaps at all.)  Our Windows viewer works, because it has an option to always display a local cursor, but our Java viewer (which is the basis of our Linux and Mac viewers) doesn't have that option.  It would be straightforward to add that option, but I want to first understand why you're able to see a cursor with the TigerVNC Viewer and I'm not.

**Comment by dcommander** [comment]
Implemented a new `LocalCursor` parameter in the Java viewer (pass `-localcursor` to /opt/TurboVNC/bin/vncviewer to enable it.)  This causes the local cursor to always be displayed, and it ignores any cursor shape updates from the server.  The Windows TurboVNC Viewer already had this capability.  A new CI build with this feature should be available shortly.
