### ISSUE TITLE
Scroll wheel input fails when using multiple screens.

### ISSUE THREAD

**Issue by fggompute** [TurboVNC/turbovnc#69]
We have found that the scroll wheel doesn't work if the viewer window is moved to a screen that is either to the left or above the primary screen. Screens to the right or below works fine.

We tested with TurboVNC 2.1 on Windows 10.

**Comment by dcommander** [comment]
Windows 10 seems to unfortunately be somewhat broken in this regard.  I tried to swap the screens on my installation of it, but that caused the Control Panel to lock up and stop responding to input.  When I finally managed to coax it into swapping the screens, the mouse input seemed to be redirected to the wrong screen.  Windows 7 works fine.  Can you reproduce this on W7?  If not, then I think this is unfortunately Microsoft's bug, not ours.

**Comment by fggompute** [comment]
I'm able to reproduce it on Win7sp1 using the IE11 on Win7 VirtualBox image from Microsoft. It behaves exactly the same as on Win10.

**Comment by dcommander** [comment]
Was finally able to reproduce this.  The key is not just to swap the screens but to manipulate the main display setting as well.  The following combinations reproduce the error:

* Screen 1 to the right of Screen 2 and Screen 1 = "main display":  The problem occurs when the viewer is on Screen 1.
* Screen 1 to the left of Screen 2 and Screen 2 = "main display":  The problem occurs when the viewer is on Screen 1.

Investigating.

**Comment by dcommander** [comment]
Turned out to be an easy fix.  So here's basically what happens:

When you specify a screen as the "main display" under Windows (which is also called the "primary display" in the Win32 API-- TurboVNC uses the latter terminology), that screen is where the origin (0, 0) will be located.  That was the source of my confusion, as Windows also enumerates the screens (Screen 1 and Screen 2 in my case.)

So assuming two screens with size Sw x Sh, the following combinations of settings would produce the following screen coordinates:

**Screen 1 to the left of Screen 2, Screen 1 = primary/main display**
Screen 1 = 0, 0 to Sw - 1, Sh - 1
Screen 2 = Sw, 0 to Sw * 2 - 1, Sh - 1

**Screen 1 to the left of Screen 2, Screen 2 = primary/main display**
Screen 1 = -Sw, 0 to Sw - 1, Sh - 1
Screen 2 = 0, 0 to Sw - 1, Sh - 1

**Screen 2 to the left of Screen 1, Screen 2 = primary/main display**
Screen 1 = Sw, 0 to Sw * 2 - 1, Sh - 1
Screen 2 = 0, 0 to Sw - 1, Sh - 1

**Screen 2 to the left of Screen 1, Screen 1 = primary/main display**
Screen 1 = 0, 0 to Sw - 1, Sh - 1
Screen 2 = -Sw, 0 to Sw - 1, Sh - 1

In the second and fourth cases, the coordinates of mouse events can sometimes be negative, but our code was incorrectly parsing the coordinates passed to the windows `WM_MOUSEWHEEL` message as unsigned integers.

**Comment by dcommander** [comment]
CI build of the Windows viewer should be available here:
http://www.turbovnc.org/DeveloperInfo/PreReleases
(master/2.1.x stable)

by the time you read this.
