### ISSUE TITLE
Xvnc and Virtualgl

### ISSUE THREAD

**Issue by parabyte** [TurboVNC/turbovnc#73]
Okay i have virtualgl functioning and basics including permissions all working well on a debian box with various users via vglconnect script and also if i manually run turbo's vncserver and vglrun works perfectly.

what do i need to do to get this working with turbovnc's Xvnc application?

i got Xvnc running as a systemd service. its querying localhost xdmcp xdm server, i can log in and everything functions except no vglrun, also i often run audacious and noticed the visualiser stopped working, 

what is turbo Xvnc lacking? or what am i lacking!

many thanks

**Comment by dcommander** [comment]
My first advice would be not to use XDMCP.  There are some major drawbacks to that solution:

* XDMCP is very insecure, since it has no encryption and thus sends passwords in the clear over a TCP socket.
* XDMCP is not very well supported in recent Linux distributions (read: it probably doesn't get tested, assuming it works at all.)
* Enabling XDMCP in the display manager requires opening up the local X server to TCP connections, which is itself a security risk.
* XDMCP doesn't make much sense from the point of view of TurboVNC, because TurboVNC is designed to launch sessions under existing user credentials.  These credentials are established on-demand using SSH or at boot time using systemd/init.d, so presenting a login screen after connecting to a TurboVNC session is a duplication of effort.  TurboVNC is designed to authenticate as you connect, not after you connect, and it has built-in support for authenticating using PAM credentials.

If you want a TurboVNC session to launch at boot time, you can use the existing "tvncserver" init.d script with systemd, since systemd's backward compatibility mode supports init.d scripts.  Just edit /etc/sysconfig/tvncservers to specify the sessions that should be launched under which user accounts, then do `systemctl enable tvncserver; systemctl start tvncserver`.  If you feel you must use XDMCP, then I'd be interested to hear the details of your use case.

As far as why VirtualGL stopped working, my best guess is that, in the process of opening your display manager to XDMCP connections, you may have broken the display manager modifications that VirtualGL made in order to get access to the 3D X server.  You might try re-running vglserver_config and restarting the display manager to see if that resolves the issue.  If not, then please post the exact prodecure you are using and the exact error messages you are getting.
