### ISSUE TITLE
Multi-threaded encoding causes disconnect with TigerVNC client

### ISSUE THREAD

**Issue by paulmelis** [TurboVNC/turbovnc#76]
This is with TurboVNC server 2.1.1, TigerVNC client 1.7.1. Linux 64-bit on both server and client side.

```
server$ TVNC_MT=1 vncserver -geometry 3000x1900 -dpi 185 :1

client$ vncviewer <server>:1

TigerVNC Viewer 64-bit v1.7.1
Built on: 2017-01-23 15:56
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Fri Mar  3 09:46:23 2017
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       connected to host s37n1.elvis.surfsara.nl port 5901
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VeNCrypt(19)

Fri Mar  3 09:46:24 2017
 CVeNCrypt:   Choosing security type TLSVnc (258)

Fri Mar  3 09:46:25 2017
 X11PixelBuffer: Using default colormap and visual, TrueColor, depth 24.
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
 CConn:       Enabling continuous updates

Fri Mar  3 09:46:28 2017
 CConn:       TightDecoder: bad subencoding value received
```

Followed by a disconnect on the client.

When running the same combination but with the server not using TVNC_MT all works fine. I don't know if this is an issue with TurboVNC or TigerVNC.

**Comment by dcommander** [comment]
The easiest way to tell is to downgrade the TigerVNC Viewer to an earlier release. They recently implemented multithreaded decoding (I think that was introduced in 1.7), and that may be what's causing the problem. I looked at multithreaded decoding in the past and concluded that it was impossible to make it perform significantly better than single-threaded because of the way the viewer is architected. Basically, the problem is that the viewer has to maintain a single copy of the remote framebuffer and update it incrementally as it receives framebuffer updates from the server. Framebuffer updates are received from the server in a particular order, and they have to be decoded in that same order to ensure that the client's copy of the framebuffer is the same as the server's. That severely limits the amount of parallelism that you can achieve in the viewer, and in practice, the best I was ever able to do without introducing visual artifacts or other problems was to pipeline the receipt of the next framebuffer update while decoding and drawing the previous. The other issue is that you are limited to one thread per zlib stream, and the RFB Tight encoding spec only supports 4 zlib streams total. So I suspect there may be some shenanigans with regards to the TigerVNC Viewer's management of zlib streams when multithreaded decoding is enabled. The TurboVNC Server, when multithreaded encoding is enabled, assigns one of these zlib streams to each thread so that the viewer can conceivably also assign one stream per thread if it's multithreading, but this stream assignment should be 100% compatible with the Tight encoding spec, so theoretically at least, it shouldn't be making the TigerVNC Viewer choke. It doesn't make our viewer choke, nor other TightVNC-compatible viewers.

I have it on my to-do list to evaluate what TigerVNC did vis-a-vis multithreaded decoding, but I strongly suspect that something might be broken in their implementation. Test the TigerVNC 1.6 viewer. If that works, then this is a TigerVNC bug, but I will be digging into this issue in the coming weeks regardless, so I hope to develop a better understanding of what they did. If TigerVNC 1.6 still fails, then try limiting the thread count on the server to 4 (I'm not in front of my computer, so I don't remember the environment variable that does that, but I think it's TVNC_NTHREADS.)

**Comment by paulmelis** [comment]
It also happens with TigerVNC 1.6.0:

``
paulm@cmstorm:~/software/tigervnc-1.6.0/bin$ ./vncviewer 

TigerVNC Viewer 64-bit v1.6.0
Built on: 2015-12-24 16:02
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Fri Mar  3 12:46:44 2017
 CConn:       connected to host s37n1.elvis.surfsara.nl port 5901
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VeNCrypt(19)
 CVeNCrypt:   Choosing security type TLSVnc (258)

Fri Mar  3 12:46:46 2017
 X11PixelBuffer: Using default colormap and visual, TrueColor, depth 24.
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
 CConn:       Enabling continuous updates

Fri Mar  3 12:46:51 2017
 CConn:       TightDecoder: bad subencoding value received
```

**Comment by paulmelis** [comment]
Tested with TigerVNC 1.5.0, if fails as well with the subencoding error.

The clients also seems sensitive to what is left in the frame buffer after one of the errors and subsequent disconnects happens. The intial desktop image loads, but after the client error occurs after some interaction, reconnecting immediately triggers the subencoding error. Connecting with TurboVNC followed by doing a bit of interaction, disconnecting and reconnecting with TigerVNC makes the initial image load again.

**Comment by dcommander** [comment]
Did you try limiting the server thread count (`TVNC_NTHREADS=4`)?  Now that I'm refreshing my memory on this, because of the zlib stream limitation in the RFB Tight protocol, the TurboVNC Server will use the rfbTightNoZlib extension if more than 4 server threads are enabled (meaning that, for Threads 5-N, any non-JPEG subrectangles won't be compressed.)  The rfbTightNoZlib extension isn't supported in any viewers other than ours, so that could definitely explain the problem.

**Comment by paulmelis** [comment]
On 03-03-17 13:05, DRC wrote:
> Did you try limiting the server thread count (|TVNC_NTHREADS=4|)? Now
> that I'm refreshing my memory on this, because of the zlib stream
> limitation in the RFB Tight protocol, the TurboVNC Server will use the
> rfbTightNoZlib extension if more than 4 server threads are enabled
> (meaning that, for Threads 5-N, any non-JPEG subrectangles won't be
> compressed.) The rfbTightNoZlib extension isn't supported in any viewers
> other than ours, so that could definitely explain the problem.

Indeed, with TVNC_NTHREADS=4 TigerVNC 1.7.1 client works fine, but with 
TVNC_NTHREADS=5 it show the subencoding error.

**Comment by dcommander** [comment]
OK, that makes total sense then.  It's not a bug but rather a failure on my part to document the fact that a thread count > 4 requires the TurboVNC Viewer.  I should also probably set the maximum thread count on the server to 4 unless the user specifically overrides it.

**Comment by dcommander** [comment]
I just checked in a commit that will now limit the thread count to 4 by default, to avoid this problem (this can still be overridden with `TVNC_NTHREADS`, if the server has more than 4 cores.)  I also added the ability to configure multithreaded encoding on the command line or in the turbovncserver.conf file.
