### ISSUE TITLE
Notify Clients That Server Has Intentionally Exited

### ISSUE THREAD

**Issue by richgansa** [TurboVNC/turbovnc#77]
With our custom portal implementation the client will give an error, usually "Write Error: Broken pipe", when the VNC server is stopped (basically via vncserver -kill :#). Is it possible to configure the server to notify the client that the server was intentionally stopped so that the client relays a message along the lines of "The server has ended the session"? Then, also, an option to suppress that message would also be useful (similar to NoReconnect).

**Comment by dcommander** [comment]
What you're asking isn't possible using the current RFB spec.  `vncserver -kill` kills the Xvnc process from outside of the process (vncserver is just a Perl script.)  Xvnc has a signal handler that is invoked when the process is killed, so `ddxGiveUp()` in init.c could conceivably be modified to send a shutdown message to any connected clients, but unfortunately such a shutdown message doesn't exist.  :|  From the client's point of view, killing the server looks the same as a network failure.  All it knows is that it can no longer communicate with the server, and it has no way of knowing why.  That's why you generally see one of three different messages in the viewer when the server is killed:  "Connection Closed", "Read Error: Connection reset by peer", or "Write Error: Broken pipe".

How specifically is your portal trying to interact with the TurboVNC Server?  I'm asking because `vncserver -kill` isn't the normal way that portals would shut down the server.  Also, what organization do you represent?

**Comment by richgansa** [comment]
We have a server running CentOS 7 running MATE with a handful of graphics cards available to our users to access a shared Linux environment with full 3D capabilities. Simply put, our "portal" is Apache+PHP that dynamically starts/stops sessions as people need them and then provides one-time passwords to connect to the session. By default when a users logs out of the MATE session the  session just hangs at the background image. I added the -autokill argument to the vncserver script to end the session and it works as intended however the clients will receive the various errors. If there's a cleaner way of making this work I am open to suggestions.

We are a medium-sized (<50 employees on-premise) software distribution/support company from Michigan. I am open to further discussion via email if that is a more appropriate venue.

**Comment by dcommander** [comment]
Yes, please contact me offline with details of who you represent:  http://www.turbovnc.org/About/Contact.  The description of your company sounds like one with which I have an active support contract.

As far as the technical details, portals often invoke vncserver with `-fg`, which causes Xvnc to exit cleanly when the window manager exits, but that only works if you're launching it using a batch queuing system or something else that backgrounds the process.  Also, that doesn't really change anything from the client's point of view.

Why is the warning dialog a problem?  I'm just trying to understand your workflow.  About the best I can do here would be to add an undocumented option that disables the dialog for WarningExceptions (which should have the effect of disabling the dialog for disconnect messages but not for unexpected fatal errors.)

**Comment by richgansa** [comment]
I'll look into backgrounding `vncserver` while utiziling the `-fg` argument. That sounds like it should fill our need. I wasn't previously aware there was a method of cleanly ending the Xvnc process, so additional/undocumented commands shouldn't be necessary at this state. The dialog isn't a problem, per se, it's mainly confusing to the users as they're under the impression that something is wrong. This was mainly an effort to mitigate concern by the users.

I will be emailing you the other details shortly.
