### ISSUE TITLE
Possible authentication bug in auth.c

### ISSUE THREAD

**Issue by unixpeikko** [TurboVNC/turbovnc#80]
Hi,

  While trying to get TLSPlain authentication to work with PAM accounts and passwords I run into a situation, where vncserver (when using java client) correctly detects invalid username/password pairs and rejects the connections, but allows valid username/password pairs for sessions which is not even owned by the authenticated user. For example, I could authenticate using username ralf and ralf's correct password to users jack session running on different port.  With wrong password, the login is rejected i.e. pam part seems to work.

  I tried to understand the issue by reading auth.c on 

https://github.com/TurboVNC/turbovnc/blob/master/unix/Xvnc/programs/Xserver/hw/vnc/auth.c#L234 

and I couldn't find code that actually checks if user provided username actually owns the session. While thinking forward, it strikes odd that vncserver would even bother to ask the information from client when it clearly has to know it already. 

  Perhaps I'm not understanding the code well enough yet. I'll try to grab a complete copy and debug further.

**Comment by dcommander** [comment]
> While thinking forward, it strikes odd that vncserver would even bother to ask the information from client when it clearly has to know it already.

That's what authentication does.  It ensures that the person sitting in front of the client machine knows the same credentials that the server already knows.

Someone else reported this same problem to me in e-mail a couple of weeks ago, but I was unable to reproduce it.  However, I just realized why.  This issue occurs only when /opt/TurboVNC/bin/Xvnc is setuid root:

```
-rwsr-xr-x. 1 root root 3749272 Apr  5 13:50 Xvnc
```

Making Xvnc setuid root is the only way I know of to ensure that ACLs work properly, but I wasn't aware of this unintended consequence (it may not occur on every system.)  I'll have to dig into the issue and see if I can come up with a solution that fixes this while still allowing ACLs to work.  Stand by.

In the meantime, if you don't need to use ACLs, then you should be able to work around the problem by doing `chmod u-s /opt/TurboVNC/bin/Xvnc` and restarting the TurboVNC Server session.

**Comment by unixpeikko** [comment]
Unfortuantely something as simple as setuid root doesn't seem to be the reason in our case. /opt/TurboVNC/bin/Xvnc is not setuid root and we're starting the vncserver processes during bootup (script is run as root) with commands like

su <username> -c 'cd ~<username> && /opt/TurboVNC/bin/vncserver :<vnc port>'

**Comment by dcommander** [comment]
Hmmm...  Well, it still works for me if the two server instances are started from init.d using the /etc/sysconfig/tvncservers file, so it doesn't seem as if using root to start the servers is the core problem.

Please provide more details about:
* How the script you are using starts the TurboVNC Server processes under a specific user's credentials.  It is unclear from your comment above.
* Which Linux distribution you are using on the server.

**Comment by dcommander** [comment]
OK, so I've managed to refresh my memory as to how this stuff is supposed to work.  For starters, ACLs aren't enabled by default.  You have to enable them by uncommenting `enable-user-acl` in **/etc/turbovncserver-security.conf**.  When ACLs are enabled, the user account under which the server is running is automatically added to the ACL as a full-control user, and **auth.c** checks any authentication credentials against this list.  Since no other users are in the ACL unless you explicitly add them with **/opt/TurboVNC/bin/vncpasswd**, no other user credentials can successfully authenticate against the server.

The problem I reported above vis-a-vis making Xvnc setuid root should be a non-issue, because the only reason why you would make Xvnc setuid root is if you were enabling ACLs.  However, the problem you're reporting is different and seems to be a product of two things:

* If ACLs are disabled, then the TurboVNC Server doesn't sanity check the credentials to ensure that only the owner of the session is allowed to authenticate with it.
* For some reason that I don't yet fully understand, your system is behaving as if Xvnc is setuid root even though it's not (perhaps because of how you're starting the sessions using `su -c`.)

I would still like to get to the bottom of the specific issue you're encountering, because other users may encounter the same issue, but can you confirm that enabling ACLs works around the issue at least?

**Comment by dcommander** [comment]
Update:  I also discovered that `su -c` is the same mechanism that our init.d scripts use to start sessions, so let me summarize what I need from you now:

* Further information as to how you are starting the TurboVNC sessions as root
* The specs of your server O/S

I know how to fix this problem now, but I need to fully understand why it occurs so I can document the scope of the issue.  I know already that it occurs when Xvnc is setuid root, but you are still able to reproduce the problem under circumstances where I can't reproduce it.

**Comment by unixpeikko** [comment]
Adding "enable-user-acl" to turbovnc-security.conf seems to fix the issue. I'll perform some more testing to be sure.

Basically we're using the /etc/init.d/tvncserver script provided by TurboVNC package, but we've removed requirement for ~/.vnc/passwd file as we don't want to use VNC passwords.

The server(s) OS versions we've detected the issue are Redhat Enterprise Linux 6.5, 6.7 and 7.2. so far.

**Comment by dcommander** [comment]
Hmmm...  OK, well that's very weird that the init.d script on your machine allows multiple users to authenticate, but it doesn't on mine.  I'm also running RHEL 6 and 7.  Can you post the contents of your /etc/pam.d/turbovnc file?

**Comment by dcommander** [comment]
Also, the current version of the TurboVNC Server should not require **~/.vnc/passwd** unless one of the security types that uses the VNC password is enabled.  If, for instance, you configure **/etc/sysconfig/tvncservers** as follows:

```
VNCSERVERS="1:user1 2:user2"
VNCSERVERARGS[1]="-SecurityTypes {any security types other than TLSVnc, X509Vnc, or VNC}"
VNCSERVERARGS[2]="-SecurityTypes {any security types other than TLSVnc, X509Vnc, or VNC}"
```

or, better yet, set

```
permitted-security-types = {any security types other than TLSVnc, X509Vnc, or VNC}
```

in **/etc/turbovncserver-security.conf**, then the server won't ever look for **~/.vnc/passwd**.

**Comment by alaabrh** [comment]
Dear dcommander,
I have uncommented enable-user-acl in /etc/turbovncserver-security.conf but now I need to resart the Turbo VNC session (RHEL 6.7). Cant figure out how to restart the session. May you help me please :)
Thanks

**Comment by dcommander** [comment]
Assuming your session is running on display :1,
```
/opt/TurboVNC/bin/vncserver -kill :1
/opt/TurboVNC/bin/vncserver
```
will restart it.
