### ISSUE TITLE
TurboVNC can't open GNOME session on RHEL 7.2

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#82]
When we configured Gnome in TurboVNC getting below errors.
29/05/2017 11:15:38 VNC extension running!
gnome-session-is-accelerated: No hardware 3D support.
gnome-session-check-accelerated: Helper exited with code 256

OS - RHEL 7.2
TurboVNC 2.1

**Comment by qlux** [comment]
You need to start gnome-classic or a non-accelerated desktop like xfce.

Quentin Lux | Quantum HPC
Tél.: +1 (514) 632-3724
qlux@quantumhpc.com<mailto:qlux@quantumhpc.com>

**Comment by dcommander** [comment]
GNOME 3 works in TurboVNC, but only if you use "3D window manager support", which requires VirtualGL.  Refer to http://www.turbovnc.org/Documentation/Compatibility.  The entry in that table also links to a list of known issues with GNOME 3 in a VNC environment:  https://github.com/TurboVNC/turbovnc/issues?utf8=%E2%9C%93&q=label%3A%22GNOME%203%22, not all of which have workarounds.

I would advise using MATE instead, which is available in EPEL:  https://fedoraproject.org/wiki/EPEL.  MATE is a fork of GNOME 2, so it will behave like the window manager in RHEL 6 and will incur much less system overhead than trying to run GNOME 3 with VirtualGL.

**Comment by amitkumars1985** [comment]
We have a Virtual Env where we are installing TurboVNC. There are no physical servers. Can we use Virtual GL on VMs ? How can we start Gnome Classic ?

**Comment by dcommander** [comment]
Install EPEL and MATE.

**Comment by dcommander** [comment]
As far as using VirtualGL in VMs, it's tricky at best, because most VMs have no access to the physical GPU.  With certain VM software (we support VirtualBox, specifically-- VMWare has known issues in a VNC environment), you can run the VM software in VirtualGL on the host, then use the built-in guest-to-host OpenGL redirection (VirtualBox Guest Additions) to achieve hardware OpenGL acceleration within the guest.  There is a lot of overhead with this solution, however, since all of the OpenGL calls have to be redirected, and it isn't compatible with all OpenGL applications.

**Comment by dcommander** [comment]
In short, if your ultimate goal is to get hardware OpenGL acceleration within the guest, then that's a thorny problem.  But if your ultimate goal is just to run TurboVNC in the guest, that's easy-- use MATE.
