### ISSUE TITLE
Experimental Wacom Support: Breaks with dual-monitor setup on Windows

### ISSUE THREAD

**Issue by sipickles** [TurboVNC/turbovnc#84]
Hi,

Windows 10, TurboVNC 2.1 Native Client, Dual Monitors, Wacom tablet
Fedora 24, TurboVNC 2.1 Server

We've found a problem with using Wacom tablets on Windows clients. With a single monitor, it works well. With two monitors connected to the local machine, the Wacom point frequently gets 'locked' to the edge of the TurboVNC window.

To repro, start the native Windows client and connect to the remote session. The viewer opens on the primary monitor. Maximize window or move to secondary monitor. The pointer become stuck against the right-hand edge of the TurboVNC window

In our tests, it worked initially on the primary monitor, but quickly broke when the TVNC window was moved. The wacom pointer became stuck along the right hand edge of the TVNC window.
 
Moving and maximizing the windows sometimes managed to get the Wacom pointer unstuck and it was useable again.
 
Also, we discovered that when the pointer was stuck, sometimes a drag click seems to release it.
 
Disconnecting the second monitor fixes all problems.

**Comment by dcommander** [comment]
Sorry for the delay.  I spent some time trying to reproduce this but unfortunately can't.  I tried it with my real Windows machine (running Windows 7) and with VMs running Windows 7 and 10 in Parallels Desktop.  Works fine in all cases.  Tried with TurboVNC 2.1 and with the latest version (2.1.1.)  Tried the latest Wacom drivers and the older version I used when developing the feature.  The only issues I observe are the same ones I reported when the feature was completed:

1. Due to buggy Wacom Windows drivers, the tablet will sometimes not be detected the first time the viewer starts.  Restarting the viewer seems to always work around this.
2. On very rare occasions, the viewer will crash when shutting down (also due to Wacom driver bugginess.)
3. The tablet pointer is always confined to the viewer window.  This was the only way I could prevent the Wintab library from generating regular mouse events along with Wacom-specific events, which caused the TurboVNC Viewer to send both events simultaneously, which confused the server.

The only thing I can think of is that perhaps this issue is specific to your tablet model-- i.e. it's a bug or a limitation in the specific code path for your tablet that doesn't affect the code path for mine.  Otherwise, I have no idea.

**Comment by dcommander** [comment]
If you are using an older driver release, then send me the version number.  Perhaps I can repro the problem using the same driver release.

**Comment by dcommander** [comment]
In the process of testing the Xinerama feature, I encountered a similar issue, but only if the monitors were swapped.  If I move the primary monitor to the right of the secondary, then the Wacom drivers no longer recognize the secondary and send all tablet coordinates relative to the primary.  It sounds like you're experiencing a similar issue, but I absolutely cannot reproduce any problems as long as the primary monitor is left of the secondary.  Unless you're willing to share more info on this, there is nothing further I can do.
