### ISSUE TITLE
Provide pre-signed JARs with TurboVNC Helper libraries

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#85]
We are running TurboVNC Native java client to connect to VNC sessions. While pressing ALT+TAB inside VNC session, it switches windows on host machine not on VNC session.

How can I make it work inside VNC. 

TurboVNC 2.1

**Comment by dcommander** [comment]
If you are running the viewer using Java Web Start, then this isn't generally possible.  You have to run the Java viewer as a standalone viewer, using our install packages.  This installs a library called the "TurboVNC Helper", which allows the Java viewer to make the necessary native calls to enable and disable keyboard grabbing, and keyboard grabbing is what allows the viewer to capture and send Alt-Tab keystrokes.  The default behavior is to grab the keyboard only in full-screen mode, but this can be changed in the viewer options.  You can also toggle grabbing at any time by pressing Ctrl-Alt-Shift-G.

**Comment by amitkumars1985** [comment]
Yes, we are using Java Web Start to connect to VNC session. Unfortunately we are not allowed to use standalone viewer which needs installation. Can it be done using VncViewer.jar file ?

**Comment by dcommander** [comment]
It's theoretically possible to use the TurboVNC Helper with JWS.  The general procedure would be as follows:
1. Obtain the TurboVNC Helper libraries from the following official TurboVNC packages:
  * Linux 32-bit
  * Linux 64-bit
  * Windows 32-bit
  * Windows 64-bit
2. For each of these, create a new JAR file containing the helper library and name it accordingly (e.g. "turbovnchelper-win32.jar", "turbovnchelper-linux64.jar", etc.)
3. Sign VncViewer.jar, all of the libjpeg-turbo JARs (ljt*.jar), and the new turbovnchelper*.jar files using the same signing key and deploy them into the same web server directory as your JNLP file.
4. In your JNLP file, add something similar to this:
```
  <resources os="Windows" arch="x86">
    <nativelib href="turbovnchelper-win32.jar"/>
  </resources>

  <resources os="Windows" arch="amd64">
    <nativelib href="turbovnchelper-win64.jar"/>
  </resources>

  <resources os="Linux" arch="i386">
    <nativelib href="turbovnchelper-linux32.jar"/>
  </resources>

  <resources os="Linux" arch="amd64">
    <nativelib href="turbovnchelper-linux64.jar"/>
  </resources>
```

Unfortunately it isn't possible to deploy TurboVNC Helper JARs in our official packages, because the packages for various platforms are built in parallel (thus there would be no way to make the Linux package depend on the TurboVNC Helper Windows build.)  However, I might be able to at least automate Steps 1-3 above and provide a .zip file containing signed TurboVNC Helper JARs for a particular release.  That would at least make it easier to accomplish this.

**Comment by amitkumars1985** [comment]
Thanks for the information..!!

While creating TurboVNC Helper libraries jar, do we need to consider OS were TutboVNC server is installed or client OS from where we are accessing VNC session. 
It is possible to automate ( as you mentioned ) and share .zip file with required JARs.

I still didn't get answer on my second question. Is it possible to use alt+tab if client usages VncViewer.jar to connect to VNC session ?

**Comment by dcommander** [comment]
* The TurboVNC Helper library JAR is downloaded by JWS to the client, so you will need to provide a JAR for every client O/S you wish to support (except macOS-- since Mac doesn't use Alt-Tab, it isn't necessary to grab the keyboard in order to send that key sequence to the server.)
* I did answer your second question, as far as I understand it.  If you aren't satisfied with my answer, then please be more clear about what you are asking.

**Comment by amitkumars1985** [comment]
Thanks for your inputs..!!
Seems I missed that point. I will try to follow the instructions mentioned by you and will share feedback.

Just one last clarification, TurboVNC Helper library JAR needs to be provided based on OS arch not based on OS version.  Will it also work on Windows 10 ?

**Comment by dcommander** [comment]
Yes, the version of turbovnchelper.dll I provide with the official TurboVNC packages is built using Visual C++ 2010, so it should be forward compatible with XP and later.  And yes, you need a different JAR for each O/S architecture, not each O/S version.

**Comment by amitkumars1985** [comment]
In about comment, it was mentioned to obtain the TurboVNC Helper libraries from TurboVNC Official packages but I am not sure while libraries we are referring here and how to get these.  I want to build turbovnchelper-linux64.jar for our environment but not sure which files we need to take. 

Can you suggest ?

**Comment by dcommander** [comment]
Note that

**Comment by amitkumars1985** [comment]
@dcommander Thanks a lot for sharing the script. With this I am able to generate the required jar files. 
Now I would request you to let me know the steps for signing these JARs so that I can use them in jnlp file. 
I have not done signing of any JARs in our Env and using what is default provided in TurboVNC installer.

**Comment by dcommander** [comment]
You would have to obtain your own code signing certificate, first and foremost.  There are plenty of articles online regarding how to sign JARs, once you obtain the certificate.

I would like to eventually supply signed TurboVNC Helper JARs, but I can make no guarantees regarding when that will happen (probably no earlier than TurboVNC 2.2), and there may be some logistical hurdles regarding producing those JARs.  Basically, at the moment, JAR signing in TurboVNC takes place only when I do official Linux builds on my local machine.  That build system can take the (unsigned) JARs that I ship with each release of libjpeg-turbo and sign them along with VncViewer.jar, thus allowing the Java TurboVNC Viewer to be delivered via JWS to Linux, Windows, and Mac clients with full acceleration for JPEG decompression.  Doing the same for TurboVNC Helper is trickier, because it would require adding JAR signing functionality to the TurboVNC build system on Windows as well.  If you want me to do that sooner rather than later, then I'm happy to discuss performing that labor under paid contract with your organization.

**Comment by amitkumars1985** [comment]
In our environment we are using default setup of TurboVNC which doesn't require any certification for connecting TurboVNC. We are connecting through http to open our VNC sessions with built-in htttp provided by TurboVNC. We have not setup and separate HTTP server to distribute those JARs. What is the process to obtain the certificate and will that need to make any changes in the way users are connecting their VNC sessions. ?

**Comment by dcommander** [comment]
How to obtain a code signing certificate and sign JARs is something you will have to Google. I cannot offer that level of individualized consulting for free. Consulting and contract development on this and other open source projects is my only source of income, and the fact that I am able to (barely) support myself by doing that is the only reason I am able to provide TurboVNC free of charge.

What I can tell you is that you don't need a separate web server. You can simply place the TurboVNC Helper JARs in the same directory as VncViewer.jar on the server and modify the server's JNLP template as previously discussed.

**Comment by dcommander** [comment]
Implemented in the official build scripts, and a test build is available here:

https://turbovnc.sourceforge.io/vnc.nightly/

You should be able to distribute the TurboVNC Helper JARs via JWS by:
* Installing the TurboVNC RPM on the server
* Editing **/opt/TurboVNC/java/VncViewer.jnlp** and uncommenting the `<nativelib>` tags that refer to **tvnchelper-*.jar**
* Extracting **turbovnc-2.1.2-jws.zip** into **/opt/TurboVNC/java**

Please let me know ASAP if this doesn't work.

**Comment by amitkumars1985** [comment]
I can confirm that this fix works fine now. I am able to fetch helper Jars while connecting through Java Web Start. GrabJey Option is also available in the viewer and Alt+Tab combination works
