### ISSUE TITLE
'could not acquire name on session bus' using debian stretch / mate 1.16.1 / lightdm 1.18.3

### ISSUE THREAD

**Issue by jacques2020** [TurboVNC/turbovnc#86]
Hi,

I used for a while turbovnc on debian Jessie with mate, without any issue

I recently upgraded to stretch (9.0) for other reasons and now I can open one turbovnc session per user. The second run of vncserver (within the same or an other ssh shell) results in no error at shell but the desktop when connecting is black with a message in the middle 'could not acquire name on session bus'
I use mate (1.16.1) and lightdm (1.18.3) all from official debian repository as well as nvidia-driver (375.66).
Clearing the .vnc to force recreating a new one does not help.
A bit of googling suggested that the issue could come from missing
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
in front of the xstartup.turbovnc but in my case they are there. 
I added -x to the shebang to ensure that it it the correct xstartup and lines above are correctly executed (in the log in .vnc) and the mate wm correctly identified.

I usually pass the flag -geometry but removing it does not make any difference.

Thank you for your help.

Best

Jacques

**Comment by jacques2020** [comment]
A inelegant work around
if you comment out the unset in the ~/.vnc/xstartup.turbovnc
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS
and launch a session by
dbus-launch --exit-with-session vncserver <args>
it seems to fix the issue

Best
Jacques

**Comment by dcommander** [comment]
The lines
```
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
```
were added to xstartup.turbovnc to fix this exact issue under GNOME 2, but the original issue occurred when launching TurboVNC from a local GNOME 2 desktop session when GNOME 2 was also in use in the TurboVNC session.

Since MATE is based on GNOME 2, I would expect similar results if both the local desktop and TurboVNC session are running MATE, but if you're using a different WM on your local desktop, a different incantation may be required.  Which window manager are you using on your local desktop?

**Comment by jacques2020** [comment]
I am unsure that everything is clear for me. The local desktop is the computer where the vnc will act as a server. In this case this is mate (1.16.1) and lightdm (1.18.3) as I was saying in the first post. gdm refuse to run using my nvidia-driver and lightdm is recommended by mate. Or I missed something and an other component come into play ? The workaround in no longer working properly this morning. Issuing a command like bash status in a shell (nothing else opened) hang the session.

**Comment by dcommander** [comment]
I think I was able to reproduce this using MATE 1.16 on Ubuntu 16.04, but I'm not sure.  I don't see the "could not acquire name on session bus" message, but I definitely do see the black screen.  However, dbus-launch doesn't work for me, which makes me suspect that I might be seeing a different issue.  I'm going to try it again tomorrow with the same configuration on one of my nVidia-equipped boxen.

**Comment by dcommander** [comment]
I tried it on an nVidia-equipped machine running Ubuntu 16.04 and MATE 1.16.  It works fine for me.  I can definitely reproduce the failure by commenting out

```
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
```

in **~/.vnc/xstartup.turbovnc** but not otherwise.  Perhaps there is something different about Debian vs. Ubuntu that is causing the failure on your machine but not mine, but I'm not sure what that could be (16.04 is supposed to be based on Stretch.)  Can you try removing everything from **~/.vnc/xstartup.turbovnc** except:

```
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec /usr/bin/mate-session
```

?  This will ensure that MATE is started directly rather than through the xinitrc mechanism.  Perhaps it is the latter mechanism that it causing problems.

**Comment by dcommander** [comment]
Have you tried my advice above?

**Comment by jacques2020** [comment]
Thank you for the suggestion and sorry for the delay due to holidays.
Indeed, your suggestion appear to fix the issue although I am unsure how functional is the create session. The one using dbus-launch as I mentioned above were not running fine with matlab on the long run.
Interestingly, when creating a shell with sudo -u <username> -s from root and creating multiple vncsession from within, even with the original startup.turbovnc, there is no issue creating multiple session. Would it means that there is something with the environment vars ? 

I will let you know about the functionality of the workaround.
Thank you for your help

Best

Jacques

**Comment by dcommander** [comment]
I have seen similar issues on Ubuntu, which is why the default xstartup.turbovnc file has all of the `TVNC_SSHAGENT` stuff in it.  It may be that Debian requires a different incantation than Ubuntu.  At the moment, I still can't reproduce the problem, either in a virtual machine or on a physical nVidia-equipped machine (both with Ubuntu 16.04 LTS.)  It may be because there are subtle differences between that platform and Debian.  I don't have any installations of Debian, unfortunately.

**Comment by dcommander** [comment]
Reproduced with Fedora 26!

**Comment by dcommander** [comment]
I thought I had reproduced the issue with Fedora 26, but unfortunately it wasn't reliably reproducible on that platform, so I broke down and installed Stretch.  Adding

```
unset XDG_RUNTIME_DIR
```

after the existing `unset` lines in **~/.vnc/xstartup.turbovnc** seems to be the magic incantation, but I need to do some further experiments on other platforms to figure out if that's a good approach in general.  There were several issues related to GNOME 3 on RHEL 7 that were affected by the `XDG_RUNTIME_DIR` environment variable, so I want to make sure those don't regress before I push the modification.

**Comment by dcommander** [comment]
Unfortunately, unsetting `XDG_RUNTIME_DIR` proves to be a bad idea in general.  On some platforms, that causes the system to treat the current directory as the XDG runtime directory, which can cause a host of other problems.  Other than the workaround I posted above (modifying **~/.vnc/xstartup.turbovnc** so that it calls mate-session directly), I have no other ideas.  TurboVNC 2.2 will introduce a new environment variable called `TVNC_WM` that will at least facilitate workarounds such as that (you would simply set `TVNC_WM=mate-session` to launch MATE without the xinit junk.)

**Comment by dcommander** [comment]
Added the workaround to the wiki:
https://turbovnc.org/Documentation/Compatibility

**Comment by dcommander** [comment]
Actually, the `TVNC_WM` modification made it into 2.1.2, so you can now specify `TVNC_WM=mate-session` with the latest stable pre-release build to work around this.

**Comment by dcommander** [comment]
NOTE: This seems to be a broader problem.  I now have a good Stretch VM running in VMWare with 3D acceleration, so I can reasonably test both VirtualGL and TurboVNC on that platform.  It suffers from the same problem as other Wayland-enabled distros, vis-a-vis GDM 3 not loading /etc/gdm*/Init/Default, thus necessitating the use of LightDM with VirtualGL.  However, when attempting to log in locally using LightDM, MATE also gives the "Could not acquire name on session bus" error.  It works properly with TurboVNC as long as you set `TVNC_WM=mate-session`.

**Comment by maravento** [comment]
Problem: **Could not acquire name on session bus**
Solution for Ubuntu Mate 18.04x:
Edit:
`sudo nano etc/xrdp/startwm.sh`
Comment this line:
`#test -x /etc/X11/Xsession && /etc/X11/Xsession`
`#exec /bin/sh /etc/X11/Xsession`
Add lines to the end:
`unset DBUS_SESSION_BUS_ADDRESS`
`exec mate-session`
Restart:
`sudo systemctl restart xrdp`
