### ISSUE TITLE
Position of config save button is not intuitive

### ISSUE THREAD

**Issue by ddavidebor** [TurboVNC/turbovnc#91]
The position of the save config button is not intuitive, new users have reported an hard time finding it.

A classic "windows stile" save/apply/close would be more intuitive on most platforms

**Comment by dcommander** [comment]
It's unclear what you mean.  Are you referring to the Windows native viewer or the Java viewer?  I don't understand what you mean about Save/Apply/Close.

**Comment by dcommander** [comment]
Never mind.  From your other bug reports, I gathered that you were using the Java viewer.  What confused me is that there is a "save connection info" function in the Windows native viewer, and I thought that was what you were referring to.

**Comment by ddavidebor** [comment]
I'm referring to both the java and the native viewer, the latter at least on MacOS.

The only option I found to permanently save the config is under the "global" tab of the config window.

**Comment by dcommander** [comment]
MacOS always uses the Java viewer, even though it is packaged as an app.  The native viewer only exists on Windows.

A little background:
Our Windows native viewer was originally based on TightVNC 1.3.x, so its GUI still largely retains that design.  The Java viewer, which is always used on non-Windows platforms and which is provided as an option on Windows, was originally based on the TigerVNC Viewer, so its GUI still largely retains that design.  The viewers handle defaults a bit differently.  The Windows native viewer automatically stores the "Encoding" and "Connection" settings for each hostname/display to which you connect, and its Global tab provides an option for clearing those stored settings.  The Java viewer doesn't store any settings by default.

"Apply" isn't really applicable, because that means "apply the settings without closing the dialog."  We have no analogue of that function.  I would like to eventually modify the Java viewer so that it stores per-connection settings automatically like the Windows viewer does, but that's going to take some effort.  In the meantime, moving the "Save" button so that it's next to "OK/Cancel" seems more awkward than what we're doing now (since it is our convention to put functions for managing global settings under the "Global" tab.)  A lot of modern applications will save options by default when you click "OK" in the Preferences dialog.  I would be open to the TurboVNC Viewer doing likewise.  That seems like it would address your concern and also parallel the behavior of the Windows native viewer a bit more.

**Comment by dcommander** [comment]
The way the Windows native viewer works is that, in the connection dialog, you can select any previous connection from the drop-down list, and when you select a particular connection, clicking "Options" allows you to modify the configuration for only that connection.  That's a much better system than the one the Java viewer uses.

**Comment by ddavidebor** [comment]
I think saving as default when clicking "save" would be more intuitive for most users.
Alternatively, moving the global tab all the way to the right and changing the buttons and labels into something more explicit could also help the user.

**Comment by dcommander** [comment]
It already does save the defaults when clicking "Save".  Did you mean when clicking "OK"?  Your complaint is that the Save button is hard to find, but personally, whenever an application doesn't behave as I expect, the first thing I do is examine all of the tabs in the preferences dialog to see if there's a setting to make it do what I expect.  So to me personally, the current design is quite intuitive.

However, as I said above, I'm open to changing the behavior in a future release.  For TurboVNC 2.2, I would like to make the Java viewer behave like the Windows viewer and store connection-specific settings.  For 2.1.2, I would be open to changing the behavior such that it saves the defaults automatically when clicking "OK", but that's probably the limit of what I'll be willing to do in a bug-fix release.

**Comment by ddavidebor** [comment]
yes i meant "ok" sorry

**Comment by dcommander** [comment]
The Java viewer now saves the defaults when dismissing the Options dialog with OK.  That seems to be the most intuitive thing to do, since it mimics the behavior of most modern applications.
