### ISSUE TITLE
VNC Performance issue

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#93]
VNC version :- TurboVNC 2.1

We are using Java web applet to connect to our VNC sessions. Users have been complaining about slow performance of the VNC. Here is one use case from user :

"User connects VNC session without any issue and it works normally. After he finished his work and is about to leave, he don't close the VNC session and keeps it running. So VNC is kept in idle start over night. Once be comes back to office next day and opens VNC session( which was kept idle over night ) , it take lot of time to open it ( ideally 30 mins ). After loading it finished it starts working normally."

Now user don't want to wait for that long to connect to VNC when he starts his day. 
Is there any way to reduce this loading time after session was kept idle for long time ?

**Comment by amitkumars1985** [comment]
Below is some analysis that we did on VNC logs : 

24/07/2017 11:39:29 New desktop size: 2560 x 1396                   
24/07/2017 11:39:29 Continuous updates enabled    -> **VNC window was in opened state.**
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x16000fc specified for 0x1600108 (IC Manage ).

(rhsm-icon:47307): libnotify-CRITICAL **: notify_notification_close: assertion `notification != NULL' failed

(rhsm-icon:47307): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
.
.
(rhsm-icon:47307): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
end from FAM server connection
end from FAM server connection
end from FAM server connection

(rhsm-icon:47307): libnotify-CRITICAL **: notify_notification_close: assertion `notification != NULL' failed
.
.
(rhsm-icon:47307): libnotify-CRITICAL **: notify_notification_close: assertion `notification != NULL' failed

(rhsm-icon:47307): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
VNC window remained in opened state till here.

25/07/2017 09:29:22 Got connection from client 10.139.87.123  **-> User might have left it untouched for long time. And at this point, reconnection was initiated to the opened turbo VNC window.**
25/07/2017 09:29:22   (other clients 10.139.87.207)
25/07/2017 09:29:22 Using protocol version 3.8
25/07/2017 09:29:22 rfbSendSecurityTypeList: advertise sectype tight
25/07/2017 09:29:22 Enabling TightVNC protocol extensions
25/07/2017 09:29:22 Advertising Tight auth cap 'VENCRYPT'
25/07/2017 09:29:22 Client requested VeNCrypt sub-type 259
25/07/2017 09:29:23 Deferring TLS handshake                  **-> Authentication to the VNC session was done**
25/07/2017 09:29:30 Pixel format for client 10.139.87.123:
25/07/2017 09:29:30   32 bpp, depth 24, little endian
25/07/2017 09:29:30   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
25/07/2017 09:29:30   no translation needed
25/07/2017 09:29:30 Enabling full-color cursor updates for client 10.139.87.123
25/07/2017 09:29:30 Enabling Desktop Size protocol extension for client 10.139.87.123
25/07/2017 09:29:30 Enabling Extended Desktop Size protocol extension for client 10.139.87.123
25/07/2017 09:29:30 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
25/07/2017 09:29:30 Enabling LastRect protocol extension for client 10.139.87.123
25/07/2017 09:29:30 Enabling Continuous Updates protocol extension for client 10.139.87.123
25/07/2017 09:29:30 Enabling Fence protocol extension for client 10.139.87.123
25/07/2017 09:29:30 Enabling GII extension for client 10.139.87.123
25/07/2017 09:29:30 Using tight encoding for client 10.139.87.123
25/07/2017 09:29:30 Using JPEG subsampling 0, Q100 for client 10.139.87.123
25/07/2017 09:29:30 Using JPEG quality 95 for client 10.139.87.123
25/07/2017 09:29:30 Using JPEG subsampling 0 for client 10.139.87.123
25/07/2017 09:29:30 Using Tight compression level 1 for client 10.139.87.123
25/07/2017 09:29:30 Client supports GII version 1
25/07/2017 09:29:30 New desktop size: 2544 x 1340      **-> User connected to VNC session**

**After 15 mins, connection to vnc window is lost with timeout error. So, during this 15 mins, the VNC was in hung state. **
25/07/2017 09:44:56 rfbSendUpdateBuf: write: Connection timed out
25/07/2017 09:44:56 Client 10.139.87.207 gone

**VNC window was closing**
25/07/2017 09:44:56 Statistics:
25/07/2017 09:44:56   key events received 14213, pointer events 33879
25/07/2017 09:44:56   framebuffer updates 26396, rectangles 2027722, bytes -20809674
25/07/2017 09:44:56     LastRect markers 25727, bytes 308724
25/07/2017 09:44:56     cursor shape updates 533, bytes 1272705
25/07/2017 09:44:56     Tight rectangles 2001462, bytes -22391103
25/07/2017 09:44:56   raw equivalent 196408.538336 Mbytes, compression ratio 15.269844
25/07/2017 09:44:56 rfbSendFence: write: Broken pipe
25/07/2017 09:44:56 Client 10.139.87.123 gone
25/07/2017 09:44:56 Statistics:
25/07/2017 09:44:56   framebuffer updates 1, rectangles 87, bytes 357864
25/07/2017 09:44:56     LastRect markers 1, bytes 12
25/07/2017 09:44:56     cursor shape updates 1, bytes 2388
25/07/2017 09:44:56     Tight rectangles 85, bytes 355464
25/07/2017 09:44:56   raw equivalent 14.295052 Mbytes, compression ratio 40.215189
25/07/2017 09:44:56 Could not disable TCP corking: Bad file descriptor 
       
25/07/2017 09:44:56 httpd: get 'ljtwin32.jar' for 10.139.87.123    **-> VNC window was started. Based on the timestamps. We assume the VNC window was restarted automatically.**
25/07/2017 09:44:56 httpd: get 'VncViewer.jar' for 10.139.87.123

25/07/2017 09:45:03 Got connection from client 10.139.87.123
25/07/2017 09:45:03 Using protocol version 3.8
25/07/2017 09:45:03 rfbSendSecurityTypeList: advertise sectype tight
25/07/2017 09:45:03 Enabling TightVNC protocol extensions
25/07/2017 09:45:03 Advertising Tight auth cap 'VENCRYPT'
25/07/2017 09:45:03 Client requested VeNCrypt sub-type 259
25/07/2017 09:45:03 Deferring TLS handshake
25/07/2017 09:45:11 Pixel format for client 10.139.87.123:
25/07/2017 09:45:11   32 bpp, depth 24, little endian
25/07/2017 09:45:11   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
25/07/2017 09:45:11   no translation needed
25/07/2017 09:45:11 Enabling full-color cursor updates for client 10.139.87.123
25/07/2017 09:45:11 Enabling Desktop Size protocol extension for client 10.139.87.123
25/07/2017 09:45:11 Enabling Extended Desktop Size protocol extension for client 10.139.87.123
25/07/2017 09:45:11 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
25/07/2017 09:45:11 Enabling LastRect protocol extension for client 10.139.87.123
25/07/2017 09:45:11 Enabling Continuous Updates protocol extension for client 10.139.87.123
25/07/2017 09:45:11 Enabling Fence protocol extension for client 10.139.87.123
25/07/2017 09:45:11 Enabling GII extension for client 10.139.87.123
25/07/2017 09:45:11 Using tight encoding for client 10.139.87.123
25/07/2017 09:45:11 Using JPEG subsampling 0, Q100 for client 10.139.87.123
25/07/2017 09:45:11 Using JPEG quality 95 for client 10.139.87.123
25/07/2017 09:45:11 Using JPEG subsampling 0 for client 10.139.87.123
25/07/2017 09:45:11 Using Tight compression level 1 for client 10.139.87.123
25/07/2017 09:45:11 Using 1 thread for Tight encoding
25/07/2017 09:45:11 Client supports GII version 1
25/07/2017 09:45:11 Continuous updates enabled
25/07/2017 09:45:12 Continuous updates enabled
25/07/2017 09:45:17 New desktop size: 2560 x 1396
**Connection to VNC session was established again and no errors after this and user has been using VNC normally.**

**Comment by dcommander** [comment]
Unfortunately I have no idea, and the log file doesn't reveal any clues.  You're the first person to report an error like this, and TurboVNC is actively used by many thousands of people worldwide (including some shops with hundreds of users banging away on it daily.)  However, whereas I have a lot of users who use the viewer with Java Web Start, very few use the viewer as an applet anymore, since NPAPI plugin support is going away in most browsers (actually, even the customer who paid for me to implement applet support no longer uses that feature.)  Java 9 will not include a browser plugin at all, so I highly recommend switching to Java Web Start as soon as possible.

Several data points that would help narrow down the cause of the issue:
* Does the issue also occur when using the viewer through Java Web Start or using one of the standalone TurboVNC viewers, or does it just occur when using the viewer in applet mode?
* Which O/S (and version) is running on the client machine (or does the issue occur irrespective of the client O/S?)
* Which version of Java is being used on the client machine?  I have seen connection delays at times with IcedTea, but never of the scale that you are reporting.
* Which window manager is running in the TurboVNC Server session?  I assume some version of GNOME or MATE, based on the log.
* Do you have any customizations in your TurboVNC Server security configuration file (usually **/etc/turbovncserver-security.conf**)?

I'm going to have to be able to reproduce the problem before I can solve it, and at the moment, I don't have enough information to reproduce it.

**Comment by amitkumars1985** [comment]
We are using inbuilt TurboVNC HTTP service to connect to VNC session. For example,  if VNC server is server1 and VNC port is 02 then URL is 
http://server1:5802 
It downloads .jnlp file which users run to connect to VNC session.

Do you mean to say that this method is going to be obsoleted in future ? 
What is Java Web Start Method and how to implement it ? 

Below are the details requested bu you :

- Right now we are using only this .jnlp method to connect to VNC ( Not sure what this method is called technically )
- Windows 7 is running on client machine. We don't have any other OS running in our Env. 
- Java 8 is used on client machines.
- On TurboVNC server we have GNOME and XFCE desktop manager.
- No customization made in /etc/turbovncserver-security.conf. We are just using the standard configuration.

**Comment by dcommander** [comment]
The JNLP file is using Java Web Start.  You confused me by describing it as an "applet."  A Java applet is a completely different thing, and TurboVNC still supports that legacy mode of operation if you add /applet to the URL.  But since you're not using the applet, ignore everything I said about that.  You are using the preferred method of launching the Java viewer.

Many people in the community are using Windows 7 and Java 8, so that's definitely not the problem.  Some of my customers have hundreds of users who keep their TurboVNC Server sessions running for months without shutting them down, so leaving the session running is not the problem either.  Judging from the fact that the 15-minute delay occurred in the body of the rfbSendUpdateBuf() function, my guess would be that the issue is network-related.  Some of your phrasing is still unclear, though.  For instance, I don't know what you mean by "reconnection was initiated to the opened turbo VNC window" or "VNC window was started. Based on the timestamps. We assume the VNC window was restarted automatically."  If you truly mean the VNC window-- that is, the window that the viewer opens on the client machine-- then that window is never opened automatically.  So I still need some clarity regarding exactly what is happening when the issue occurs.

**Comment by amitkumars1985** [comment]
Issue seems to be intermittent. As per user, sometimes when he starts VNC session next day, it is stuck at attached screen for very long time ( almost 20 mins ) and then it starts working normally. And this issue is only observed once when he starts same VNC session which he left open over night. 


![turbovnc](https://user-images.githubusercontent.com/29144771/28655684-121e550e-72bb-11e7-98d3-b911c7635862.jpg)

**Comment by amitkumars1985** [comment]
Also it seems then when ever user tried to connect, it tries to download some files from server which could be a reason for delay. Is there any way to avoid this happening every time ? Like when first time user open .jnlp file , it download the required file and next time when user opens it it should refer to those downloaded files rather that downloading it from servers again.

**Comment by dcommander** [comment]
Java is supposed to cache the JAR file on the client.  Not sure why it isn't, but that setting is configured in the Java control panel under General-->Temporary Internet Files.

The only other thing I can suggest would be to try installing Apache and serving up the Java Web Start files that way.  That would at least tell you whether the problem is in TurboVNC or not.  If it's a bug in our HTTP server, then that's certainly something I want to fix.

**Comment by bphinz** [comment]
> Also it seems then when ever user tried to connect, it tries to download some files from server which could be a reason for delay. Is there any way to avoid this happening every time ?

The `offline-allowed` attribute in jnlp controls this:

```
offline-allowed element: The optional offline-allowed element indicates if the application can be launched offline.

If offline-allowed is specified, then the application can be launched offline by the Java Application Cache Viewer, and shortcuts can be created which launch the application offline.

If an application is launched offline, it will not check for updates and the API call BasicService.isOffline() will return true.

The offline-allowed element also controls how Java Web Start checks for an update to an application. If the element is not specified—i.e., the application is required to be online to run—Java Web Start will always check for an updated version before launching the application. And if an update is found, the new application will be downloaded and launched. Thus, it is guaranteed that the user always runs the latest version of the application. The application, however, must be run online.

If offline-allowed is specified, Java Web Start will also check to see if an update is available. However, if the application is already downloaded the check will timeout after a few seconds, in which case the cached application will be launched instead. Given a reasonably fast server connection, the latest version of the application will usually be run, but it is not guaranteed. The application, however, can be run offline.
```

Furthermore, you can use the `update` element to control (to a certain degree) how JWS performs the update:

```
The update element is used to indicate the preferences for how application updates should be handled by Java Web Start.

The update element can contain the following two optional attributes:

check attribute: The check attribute indicates the preference for when the JNLP Client should check for updates, and can have one of the three values: "always", "timeout", and "background"

A value of "always" means to always check for updates before launching the application.

A value of "timeout" (default) means to check for updates until timeout before launching the application. If the update check is not completed before the timeout, the application is launched, and the update check will continue in the background.

A value of "background" means to launch the application while checking for updates in the background.

policy attribute: The policy attribute indicates the preference for how the JNLP Client should handle an application update when it is known an update is available before the application is launched, and can have one of the following three values: "always", "prompt-update", and "prompt-run"

A value of "always" (default) means to always download updates without any prompt.

A value of "prompt-update" means to ask the user if he/she wants to download and run the updated version, or launch the cached version.

A value of "prompt-run" means to ask the user if he/she wants to download and run the updated version, or cancel and abort running the application.

For example:
<update check="always" policy="prompt-update"> 
```

You might want to try adding `offline-allowed` combined `update check="timeout"` value to your VncViewer.jnlp template and see if that helps.

> Java is supposed to cache the JAR file on the client. Not sure why it isn't, but that setting is configured in the Java control panel under General-->Temporary Internet Files.

With regard to caching, see above for specifics about online vs offline.  However, even in offline mode it's possible that JWS is caching the viewer and then something else is deleting it.  In our environment we had the problem that the java cache was not kept as part of the roaming profile (because it caused profiles to become too large and affected login times) and MS Group Policies were in place that cleared the local cache on logout.

Also, note that some jnlp attributes require a minimum jnlp `spec` attribute, which I don't see in the VncViewer.jnlp.in template.

**Comment by dcommander** [comment]
Excellent info.  I am more than happy to modify the .jnlp template if it fixes this issue.  At first glance, though, it seems like the defaults are probably correct for TurboVNC-- doesn't make much sense to allow a VNC viewer to run offline, and the update check is already timing out.  Since I can't repro the issue, it would be incumbent upon @amitkumars1985 to tinker with some of these settings and see which ones, if any, fix the problem.

I'm not entirely convinced this is JWS-related, though.  In the log file, it's clear that the timeout is occurring in rfbSendUpdateBuf(), which is on the RFB socket.  No way should that socket have a 15-minute timeout, so there's something odd going on.  (Although, now that I think about it, I suppose it could be that JNLP is trying to download the JAR in the background, and this is blocking the RFB socket because the server is single-threaded.  I can look into that.)  One thing I do notice that's different between TigerVNC and TurboVNC is that Turbo does all of its socket checking (for both the RFB and HTTP sockets) in the X.org wakeup handler and doesn't use the block handler at all, but I don't know if that really matters.

**Comment by dcommander** [comment]
@amitkumars1985, specifically I think you should try adding the following to /opt/TurboVNC/java/VncViewer.jnlp after `</information>`:

`<update check="always" policy="always" />`

If my hypothesis is correct and background downloading of the JAR is somehow causing a resource deadlock between the TurboVNC server and the HTTP server, then the above should serialize the JAR download and thus remove the deadlock.  You are the only one who is in a position to evaluate that, since you're currently the only one who can reproduce this issue.

**Comment by amitkumars1985** [comment]
Putting below option is jnlp file doesn't seem to make any improvement. 
<offline-allowed/>
<update check="always" policy="always" />

It still tries to connect to server to download required jar files. May be I am not using write method to to verify it. Can you suggest what should be the steps to validate it properly ?

Also is there any way to increase the timeout value of VNC session. It seems as soon user disconnects network, VNC session it also disconnected and it doesn't reconnect when network is back. Is there any possibility to keep the session alive if user is away for some time or it tries to reconnect automatically.

It's happening that when users are leaving for break of even 10-15 mins, session is getting disconnected and it doesn't reconnect again. Users again need to click on jnlp file to connect again. As soon as they click on jnlp file it starts the entire process of downloading JARs from server which is kind of annoying users.

**Comment by dcommander** [comment]
It's OK if the viewer connects to the server to download the JAR file.  However, I was suspicious that it was trying to download the JAR file in the background, and because the TurboVNC Server is single-threaded, there's a possibility that attempting to download the JAR in the background while connecting to the RFB server was causing a resource deadlock.  As I said above, I was not attempting to disable to the JAR download but rather to serialize it.  But it sounds as if you are having larger problems with your network.  The VNC session should not disconnect like that, and reconnecting should be almost instantaneous, even if the JAR has to be downloaded.

**Comment by amitkumars1985** [comment]
@dcommander It's not a network issue. We have other services running perfectly fine in same network. I think you got the point. It is going into deadlock state ( seen messages in VNC logs too but unable to capture )  and attempting to download JAR at background when it reconnects. After that nothing is happening and it is stuck at same downloading window which I shared earlier. Then the only option is to restart the VNC session. So problem seems to be single-threaded VNC server. 

Is there any possibility to change server setting to multi threaded ? How it will be beneficial in performance of VNC sessions ? 
Is there any recommendation for Performance Tuning of VNC Server ?

**Comment by dcommander** [comment]
But there is no reason why the server connection should disconnect after 15 minutes.  TurboVNC is deployed with JWS in many installations worldwide, including some large-scale commercial and academic installations, and no one has reported an issue like that.

If it is in fact a deadlock, then 

`<update check="always" policy="always" />`

should prevent that.  Your message above said "no improvement", but you were unclear as to what improvement you were expecting.  The improvement I'm expecting is the elimination of the deadlock.  You seemed to be expecting the improvement to be the elimination of downloading the JAR altogether, but I don't think that expectation is reasonable or necessary.  We simply need to eliminate the deadlock, if in fact that is what's causing the delay.  You may not be able to determine whether the JNLP modification above eliminates the delay without trying it in your production environment.

Using libhttpd, it should be possible to multi-thread the HTTP server, but that wouldn't happen until TurboVNC 2.2 at the earliest, and before I would be willing to do that work, I would need solid evidence that this issue is in fact due to a deadlock and that it can't be eliminated in any other way.  You have thus far not provided me with that evidence.  I've suggested a couple of ways that you can do that:

1. Serve up the Java Web Start files using a standalone HTTP server.  If the delay doesn't happen under this deployment scenario, then obviously the delay is caused by TurboVNC's HTTP server.
2. Try the recommended JNLP modification in your production environment and see if it works around the problem.

libhttpd would be too disruptive of a fix for 2.1.2, so if you want this fixed sooner rather than later, we're going to have to find a magic incantation in the .jnlp file that works around it.

**Comment by amitkumars1985** [comment]
I will test it for some time to see if this occurs and try to capture relevant logs.

**Comment by dcommander** [comment]
Any update on this issue?

**Comment by dcommander** [comment]
@amitkumars1985 please indicate whether the proposed patch to the .jnlp file fixes the issue or whether you can still reproduce it with that patch.  I need to know whether I should include that patch in 2.1.2.

**Comment by amitkumars1985** [comment]
Putting below 2 parameter in jnlp seems to work. I have not observed deadlock using jnlp file but still while connecting through VncViewer.jar , sometimes I have observed the issue. Is there any parameter that we can use while invoking jar to enable these options. 

<offline-allowed/>

<update check="always" policy="always" />

**Comment by amitkumars1985** [comment]
These are the parameters used : 
```
<offline-allowed/>

<update check="always" policy="always" />
```

**Comment by dcommander** [comment]
The other lock-up you are experiencing (#102) is a different issue and is probably not related to this one in any way.  Please confine your discussion of that issue to its respective bug report.  Until I can reproduce that other issue, there is no way I can fix it, and at the moment, I do not have enough information to reproduce it.  Until/unless I can get that information, there is nothing further I can do.
